import assert from 'node:assert/strict';
import test from 'node:test';
import { DataType, newDb } from 'pg-mem';
import type { Pool } from 'pg';
import { runSchemaMigrations } from '../server/persistence/migrations.js';
import { BillingAnalyticsRepository, parsePaymentQuery, parseReportingQuery, parseSubscriptionQuery, paymentsCsv, subscriptionsCsv } from '../server/billingAnalytics.js';

function memoryPool(): Pool {
  const database = newDb({ autoCreateForeignKeyIndices: true, noAstCoverageCheck: true });
  database.public.registerFunction({ name: 'hashtext', args: [DataType.text], returns: DataType.integer, implementation: () => 1 });
  database.public.registerFunction({ name: 'pg_advisory_xact_lock', args: [DataType.integer], returns: DataType.integer, implementation: () => 1 });
  const adapter = database.adapters.createPg(); return new adapter.Pool() as unknown as Pool;
}
const iso = (offsetDays = 0) => new Date(Date.now() + offsetDays * 86_400_000).toISOString();
async function seed(pool: Pool) {
  await runSchemaMigrations(pool);
  await pool.query(`INSERT INTO gxa_admin_users (user_id,name,email,email_normalized,created_at,updated_at,workspace_id) VALUES ('user-1','=Customer','customer@example.com','customer@example.com',$1,$1,'workspace-1')`, [iso(-60)]);
}
async function payment(pool: Pool, overrides: Record<string, unknown> = {}) {
  const row: any = { id: `pay-${Math.random()}`, userId: 'user-1', workspaceId: 'workspace-1', tenantType: 'personal', tenantId: 'user-1', plan: 'pro', type: 'one_time_monthly', provider: 'razorpay', paymentId: `rzp-${Math.random()}`, orderId: `order-${Math.random()}`, subscriptionId: null, amount: 9900, expected: 9900, currency: 'INR', status: 'captured', verified: true, verificationState: 'verified', environment: 'test', capturedAt: iso(-1), createdAt: iso(-1), updatedAt: iso(-1), ...overrides };
  await pool.query(`INSERT INTO gxa_billing_payments (id,user_id,workspace_id,tenant_type,tenant_id,internal_plan_key,billing_type,provider,provider_payment_id,provider_order_id,provider_subscription_id,subscription_id,amount_paise,expected_amount_paise,currency,status,signature_verified,verification_state,billing_environment,captured_at,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22)`, [row.id,row.userId,row.workspaceId,row.tenantType,row.tenantId,row.plan,row.type,row.provider,row.paymentId,row.orderId,row.providerSubscriptionId||null,row.subscriptionId,row.amount,row.expected,row.currency,row.status,row.verified,row.verificationState,row.environment,row.capturedAt,row.createdAt,row.updatedAt]); return row;
}
async function subscription(pool: Pool, overrides: Record<string, unknown> = {}) {
  const identifier = String(Math.random()).slice(2); const row: any = { id: `sub-${identifier}`, userId: `sub-user-${identifier}`, workspaceId: `sub-workspace-${identifier}`, status: 'active', mode: 'recurring_subscription', plan: 'pro_plus', amount: 14900, environment: 'test', periodStart: iso(-5), periodEnd: iso(20), ...overrides };
  await pool.query(`INSERT INTO gxa_admin_users (user_id,name,email,email_normalized,created_at,updated_at,workspace_id) VALUES ($1,'Subscriber',$2,$2,$3,$3,$4)`, [row.userId,`${row.userId}@example.com`,iso(-10),row.workspaceId]);
  await pool.query(`INSERT INTO gxa_billing_subscriptions (id,user_id,workspace_id,tenant_type,tenant_id,internal_plan_key,billing_mode,provider,status,amount_paise,currency,current_period_start,current_period_end,created_at,updated_at,billing_environment) VALUES ($1,$2,$3,'personal',$2,$4,$5,'razorpay',$6,$7,'INR',$8,$9,$10,$10,$11)`, [row.id,row.userId,row.workspaceId,row.plan,row.mode,row.status,row.amount,row.periodStart,row.periodEnd,iso(-10),row.environment]); return row;
}

test('reporting queries validate environment, timezone, dates and maximum range', () => {
  assert.equal(parseReportingQuery({ range: '7d', environment: 'test' }).environment, 'test');
  assert.throws(() => parseReportingQuery({ range: 'custom', from: '2026-01-10', to: '2026-01-01' }));
  assert.throws(() => parseReportingQuery({ range: '30d', timezone: 'UTC' }));
  assert.throws(() => parsePaymentQuery({ amountFrom: '200', amountTo: '100' }));
  assert.throws(() => parseSubscriptionQuery({ status: 'invented' }));
});

test('only unique captured, verified, matching INR payments count as revenue', async () => { const pool=memoryPool(); try { await seed(pool); await payment(pool); await payment(pool,{id:'authorized',paymentId:'authorized-provider',status:'authorized',verificationState:'unverified'}); await payment(pool,{id:'failed',paymentId:'failed-provider',status:'failed',verified:false,verificationState:'failed'}); await payment(pool,{id:'pending',paymentId:null,status:'pending',verified:false,verificationState:'unverified'}); await payment(pool,{id:'mismatch',paymentId:'mismatch-provider',amount:14900,expected:9900}); const repository=new BillingAnalyticsRepository(pool); const summary=await repository.summary(parseReportingQuery({range:'30d',environment:'test'})); assert.equal(summary.metrics.totalRevenuePaise,9900); assert.equal(summary.metrics.successfulPayments,1); assert.equal(summary.metrics.failedPayments,1); assert.equal(summary.metrics.pendingPayments,2); } finally { await pool.end(); } });

test('selected reporting range excludes older verified revenue and recent rows', async () => { const pool=memoryPool(); try { await seed(pool); await payment(pool); await payment(pool,{id:'old-capture',paymentId:'old-capture-provider',capturedAt:iso(-45),createdAt:iso(-45),updatedAt:iso(-45)}); const summary=await new BillingAnalyticsRepository(pool).summary(parseReportingQuery({range:'30d',environment:'test'})); assert.equal(summary.metrics.totalRevenuePaise,9900); assert.equal(summary.metrics.successfulPayments,1); assert.equal(summary.recentPayments.length,1); assert.notEqual(summary.recentPayments[0].id,'old-capture'); } finally { await pool.end(); } });

test('provider payment uniqueness prevents duplicate revenue and environments stay isolated', async () => { const pool=memoryPool(); try { await seed(pool); const first=await payment(pool,{paymentId:'unique-payment'}); await assert.rejects(payment(pool,{id:'duplicate',paymentId:first.paymentId})); await payment(pool,{id:'live-payment',paymentId:'live-unique',environment:'live',amount:49900,expected:49900,plan:'business-pro'}); const repository=new BillingAnalyticsRepository(pool); const testSummary=await repository.summary(parseReportingQuery({range:'30d',environment:'test'})); const liveSummary=await repository.summary(parseReportingQuery({range:'30d',environment:'live'})); assert.equal(testSummary.metrics.totalRevenuePaise,9900); assert.equal(liveSummary.metrics.totalRevenuePaise,49900); } finally { await pool.end(); } });

test('revenue trend applies verified-payment predicates and fills missing reporting days', async () => { let sql=''; let parameters: unknown[]=[]; const pool={query:async (statement: string, values: unknown[])=>{sql=statement; parameters=values; return {rows:[{date:'2026-01-02',revenuePaise:'9900',successfulPayments:1,newPaidSubscriptions:1,successfulRenewals:0}]};}} as any; const reporting=parseReportingQuery({range:'custom',from:'2026-01-01',to:'2026-01-03',environment:'test'}); const trend=await new BillingAnalyticsRepository(pool).revenueTrend(reporting); assert.equal(trend.points.length,3); assert.equal(trend.points[0].revenuePaise,0); assert.equal(trend.points[1].revenuePaise,9900); assert.match(sql,/signature_verified=TRUE/); assert.match(sql,/verification_state='verified'/); assert.equal(parameters[0],'test'); });

test('plan distribution excludes failed and out-of-range payments from plan revenue', async () => { const pool=memoryPool(); try { await seed(pool); await payment(pool,{type:'initial_subscription_payment'}); await payment(pool,{id:'failed-plan',paymentId:'failed-plan-provider',status:'failed',verified:false,verificationState:'failed'}); await payment(pool,{id:'old-plan',paymentId:'old-plan-provider',capturedAt:iso(-45),createdAt:iso(-45),updatedAt:iso(-45)}); const distribution=await new BillingAnalyticsRepository(pool).planDistribution(parseReportingQuery({range:'7d',environment:'test'})); assert.equal(distribution.plans.find((plan: any) => plan.planKey==='pro')?.revenuePaise,9900); } finally { await pool.end(); } });

test('MRR includes only active recurring paid periods and ARR is MRR times twelve', async () => { const pool=memoryPool(); try { await seed(pool); await subscription(pool); await subscription(pool,{status:'expired',periodEnd:iso(-1),amount:49900}); await subscription(pool,{status:'pending',amount:9900}); await subscription(pool,{status:'halted',amount:9900}); await subscription(pool,{status:'cancelled',periodEnd:iso(-1),amount:9900}); const repository=new BillingAnalyticsRepository(pool); const summary=await repository.summary(parseReportingQuery({range:'30d',environment:'test'})); assert.equal(summary.metrics.mrrPaise,14900); assert.equal(summary.metrics.estimatedArrPaise,178800); assert.equal(summary.metrics.activePaidSubscriptions,1); assert.equal(summary.metrics.pendingSubscriptions,1); assert.equal(summary.metrics.haltedSubscriptions,1); } finally { await pool.end(); } });

test('payment search, filters, amount sorting, pagination and safe detail work', async () => { const pool=memoryPool(); try { await seed(pool); const first=await payment(pool,{id:'payment-low',paymentId:'provider-low'}); await payment(pool,{id:'payment-high',paymentId:'provider-high',amount:49900,expected:49900,plan:'business-pro'}); const repository=new BillingAnalyticsRepository(pool); const query=parsePaymentQuery({range:'30d',environment:'test',search:'customer@example.com',status:'captured',amountFrom:'9000',amountTo:'50000',sort:'highest_amount',page:'1',pageSize:'25'}); const list=await repository.listPayments(query); assert.equal(list.pagination.total,2); assert.equal(list.payments[0].amountPaise,49900); const detail=await repository.paymentDetail(first.id); assert.equal(detail?.payment.providerPaymentReference,'••••ider-low'); assert.equal('providerPaymentId' in JSON.parse(JSON.stringify(detail)),false); assert.doesNotMatch(JSON.stringify(detail), /razorpay_signature|keySecret|webhookSecret|rawPayload/); } finally { await pool.end(); } });

test('subscription status, plan and attention filters preserve cancelled history', async () => { const pool=memoryPool(); try { await seed(pool); const active=await subscription(pool); await subscription(pool,{status:'cancelled',plan:'business-pro',periodEnd:iso(-2)}); await subscription(pool,{status:'halted',plan:'pro'}); const repository=new BillingAnalyticsRepository(pool); const activeList=await repository.listSubscriptions(parseSubscriptionQuery({environment:'test',status:'active',plan:'pro',page:'1',pageSize:'25'})); const attention=await repository.listSubscriptions(parseSubscriptionQuery({environment:'test',attention:'true',page:'1',pageSize:'25'})); const detail=await repository.subscriptionDetail(active.id); assert.equal(activeList.pagination.total,1); assert.equal(attention.pagination.total,1); assert.equal(detail?.subscription.providerSubscriptionId,undefined); } finally { await pool.end(); } });

test('billing health flags real stale, verification, webhook and paid-period problems only', async () => { const pool=memoryPool(); try { await seed(pool); await payment(pool,{id:'stale',paymentId:null,status:'pending',verified:false,verificationState:'unverified',createdAt:iso(-1),capturedAt:null}); await payment(pool,{id:'bad-signature',paymentId:'bad-signature-provider',status:'verification_failed',verified:false,verificationState:'failed'}); await subscription(pool,{status:'active',periodEnd:iso(-1)}); await pool.query(`INSERT INTO gxa_billing_subscription_events (id,provider_event_id,event_type,payload_hash,processing_status,created_at,billing_environment) VALUES ('event-1','provider-event-1','subscription.charged','hash','failed',$1,'test')`,[iso(-1)]); const health=await new BillingAnalyticsRepository(pool).health(parseReportingQuery({range:'30d',environment:'test'})); assert.equal(health.indicators.stalePendingPayments,1); assert.equal(health.indicators.verificationFailures,1); assert.equal(health.indicators.failedWebhookEvents,1); assert.equal(health.indicators.expiredMarkedActive,1); } finally { await pool.end(); } });

test('payment and subscription CSV exports escape formulas and exclude provider secrets', () => { const paymentCsv=paymentsCsv([{id:'p',userId:'u',customerName:'=Formula',customerEmail:'user@example.com',planKey:'pro',billingType:'one_time_monthly',amountPaise:9900,currency:'INR',status:'captured',providerPaymentReference:'••••12345678',providerOrderReference:'••••87654321',providerSubscriptionReference:null,capturedAt:iso(),createdAt:iso(),environment:'test'}]); const subscriptionCsv=subscriptionsCsv([{id:'s',userId:'u',customerName:'@Formula',customerEmail:'user@example.com',planKey:'pro_plus',amountPaise:14900,currency:'INR',status:'active',billingMode:'recurring_subscription',currentPeriodStart:iso(),currentPeriodEnd:iso(30),nextChargeAt:iso(30),cancelAtPeriodEnd:false,cancelledAt:null,environment:'test',latestPaymentReference:'••••12345678'}]); assert.match(paymentCsv,/"'=Formula"/); assert.match(subscriptionCsv,/"'@Formula"/); assert.doesNotMatch(paymentCsv,/signature|secret|payload/i); });
