import assert from 'node:assert/strict'; import test from 'node:test'; import { analyzeAts, buildCareerPrompt, normalizeCareerProfile, parseResumeText, validateResume } from '../server/career.js'; import { CAREER_TOOLS, RESUME_SECTIONS, RESUME_TEMPLATES } from '../shared/careerRegistry.js';
test('career registry centralizes available tools and hides the incomplete tracker',()=>{assert.ok(CAREER_TOOLS.some(x=>x.id==='resume'&&x.status==='available'));assert.equal(CAREER_TOOLS.find(x=>x.id==='applications')?.status,'unavailable');assert.equal(RESUME_TEMPLATES.length,3)});
test('career profile is structured, owner-bound and validates email',()=>{const profile=normalizeCareerProfile({firstName:'Ada',email:'ada@example.com',skills:['TypeScript']},'owner-a');assert.equal(profile.ownerId,'owner-a');assert.equal(profile.skills[0].verifiedByUser,true);assert.throws(()=>normalizeCareerProfile({email:'not-email'},'owner-a'),/valid email/)});
test('resume validation creates stable structured sections and ignores supplied owner',()=>{const resume=validateResume({ownerId:'attacker',title:'Resume',sections:[{type:'experience',entries:[{company:'GXA'}]}]},'owner-a');assert.equal(resume.ownerId,'owner-a');assert.equal(resume.sections[0].type,'experience');assert.ok(resume.sections[0].id)});
test('parser returns reviewable fields and never auto-accepts low-confidence data',()=>{const parsed=parseResumeText('Ada Lovelace\nada@example.com\nSkills\nMathematics, Writing');assert.equal(parsed.fields.every(x=>x.reviewStatus==='pending'),true);assert.ok(parsed.limitations.length)});
test('ATS guidance is deterministic, evidence-based and not hiring probability',()=>{const resume='Ada Lovelace ada@example.com Experience analytical engine development Education Mathematics Skills TypeScript writing documentation '.repeat(3);const job='Engineer TypeScript documentation analytical systems';const a=analyzeAts(resume,job),b=analyzeAts(resume,job);assert.equal(a.overallGuidanceScore,b.overallGuidanceScore);assert.ok(a.keywordAnalysis.matchedKeywords.includes('typescript'));assert.match(a.limitations.join(' '),/does not predict interviews/);assert.equal('hiringProbability' in a,false)});
test('ATS rejects insufficient resume evidence',()=>assert.throws(()=>analyzeAts('too short','job'),/at least 20 words/));
test('career prompts require facts and prohibit fabricated credentials and outcomes',()=>{assert.throws(()=>buildCareerPrompt({action:'summary',facts:''}),/verified facts/);const built=buildCareerPrompt({action:'bullet',facts:'Built a reporting tool with TypeScript',context:'Target engineering role'});assert.match(built.systemInstruction,/Never invent employers/);assert.match(built.systemInstruction,/Never guarantee ATS acceptance/);assert.equal((built as any).apiKey,undefined)});
test('all required resume section types remain centrally declared',()=>{for(const section of ['header','summary','experience','education','skills','projects','certifications','custom'])assert.ok(RESUME_SECTIONS.includes(section as any))});
