import assert from 'node:assert/strict'; import test from 'node:test';
import { buildTranslationPrompt, detectLanguage, reviewTranslation, TRANSLATION_LANGUAGES, TRANSLATION_MODES, validateTranslationRequest } from '../server/translation.js';

test('backend configuration exposes the approved translation languages and modes', () => { assert.equal(TRANSLATION_LANGUAGES.length, 23); assert.ok(TRANSLATION_LANGUAGES.some(x => x.code === 'hinglish')); assert.ok(TRANSLATION_MODES.includes('Technical')); });
test('translation validation rejects empty, unsupported, same-language and oversized requests', () => { assert.throws(() => validateTranslationRequest({ text: '', targetLanguage: 'hi' })); assert.throws(() => validateTranslationRequest({ text: 'Hello world', sourceLanguage: 'xx', targetLanguage: 'hi' }), /source language/); assert.throws(() => validateTranslationRequest({ text: 'Hello world', sourceLanguage: 'en', targetLanguage: 'en' }), /different/); assert.throws(() => validateTranslationRequest({ text: 'a'.repeat(101), sourceLanguage: 'en', targetLanguage: 'hi' }, 100), /exceeds/); });
test('auto-detection represents uncertainty and mixed language without overclaiming', () => { assert.deepEqual(detectLanguage('hello'), { code: 'en', confidence: 'low', mixed: false }); const mixed = detectLanguage('Yeh kya hai and this is mixed content for aap'); assert.equal(mixed.code, 'hinglish'); assert.equal(mixed.mixed, true); });
test('Hinglish and Hindi prompt instructions preserve requested script', () => { const hinglish = buildTranslationPrompt(validateTranslationRequest({ text: 'This is a useful message.', sourceLanguage: 'en', targetLanguage: 'hinglish', mode: 'Natural' })); assert.match(hinglish.systemInstruction, /Hinglish, use Roman Hindi/); const hindi = buildTranslationPrompt(validateTranslationRequest({ text: 'Yeh ek message hai', sourceLanguage: 'hinglish', targetLanguage: 'hi', mode: 'Formal' })); assert.match(hindi.systemInstruction, /Hindi, use Devanagari/); });
test('mode, glossary and preservation controls influence backend instructions', () => { const built = buildTranslationPrompt(validateTranslationRequest({ text: 'Keep GXA and https://gxa.example at 20%.', sourceLanguage: 'en', targetLanguage: 'fr', mode: 'Technical', preserve: { urls: true, numbers: true, keywords: ['GXA'] }, glossary: [{ source: 'Workspace', target: 'Espace de travail' }] })); assert.match(built.systemInstruction, /technical terminology/); assert.match(built.prompt, /Espace de travail/); assert.match(built.prompt, /"urls":true/); });
test('quality review reports missing protected values without inventing quality scores', () => { const request = validateTranslationRequest({ text: 'GXA costs 20% at https://gxa.example', sourceLanguage: 'en', targetLanguage: 'fr', preserve: { keywords: ['GXA'], numbers: true, urls: true } }); const review = reviewTranslation(request.text, 'Le prix est différent.', request.preserve); assert.equal(review.warnings.length, 3); assert.equal('score' in review, false); });
test('request validation ignores provider keys and unknown privileged fields', () => { const request: any = validateTranslationRequest({ text: 'Translate this text.', sourceLanguage: 'en', targetLanguage: 'de', apiKey: 'secret', ownerId: 'other-user' }); assert.equal(request.apiKey, undefined); assert.equal(request.ownerId, undefined); });
