import type { Pool } from 'pg';
import { PLAN_REGISTRY, resolvePlanKey, type PlanId } from '../shared/platformRegistry.js';
import { activeBillingEnvironment, type BillingEnvironment } from './billing.js';
import { PlatformError } from './platform.js';

export const BILLING_REPORTING_TIMEZONE = 'Asia/Kolkata';
export const BILLING_HEALTH_THRESHOLDS = Object.freeze({ pendingMinutes: 30, webhookMinutes: 5, reconciliationHours: 24, exportRows: 10_000, maximumRangeDays: 732 });
const PAYMENT_STATUSES = new Set(['pending', 'checkout_created', 'authorized', 'captured', 'failed', 'verification_failed', 'webhook_rejected']);
const SUBSCRIPTION_STATUSES = new Set(['created', 'authenticated', 'active', 'pending', 'halted', 'paused', 'cancelled', 'completed', 'expired', 'replaced', 'trialing']);
const BILLING_TYPES = new Set(['one_time_monthly', 'initial_subscription_payment', 'recurring_renewal']);
const ENVIRONMENTS = new Set(['test', 'live', 'unknown']);
const PLAN_FILTERS: Record<string, PlanId> = { starter: 'pro', pro: 'pro_plus', 'business-pro': 'business-pro', free: 'free' };
const PAYMENT_SORTS: Record<string, string> = { newest: 'payments.created_at DESC', oldest: 'payments.created_at ASC', highest_amount: 'payments.amount_paise DESC, payments.created_at DESC', lowest_amount: 'payments.amount_paise ASC, payments.created_at DESC', status: 'payments.status, payments.created_at DESC', plan: 'payments.internal_plan_key, payments.created_at DESC' };
const SUBSCRIPTION_SORTS: Record<string, string> = { newest: 'subscriptions.created_at DESC', oldest: 'subscriptions.created_at ASC', recently_updated: 'subscriptions.updated_at DESC', period_end: 'subscriptions.current_period_end ASC NULLS LAST', status: 'subscriptions.status, subscriptions.updated_at DESC', plan: 'subscriptions.internal_plan_key, subscriptions.updated_at DESC' };
const safeText = (value: unknown, maximum = 200) => String(value ?? '').trim().replace(/[\u0000-\u001f\u007f]/g, ' ').slice(0, maximum);
const value = (raw: unknown) => Array.isArray(raw) ? raw[0] : raw;
const dateOnly = (raw: unknown, label: string) => {
  const text = safeText(value(raw), 10); if (!text) return '';
  if (!/^\d{4}-\d{2}-\d{2}$/.test(text) || !Number.isFinite(Date.parse(`${text}T00:00:00Z`))) throw new PlatformError(`${label} is invalid.`, 422, 'VALIDATION_FAILED');
  return text;
};
const integer = (raw: unknown, label: string, minimum = 0, maximum = Number.MAX_SAFE_INTEGER) => {
  if (raw === undefined || raw === null || raw === '') return null;
  const parsed = Number(value(raw)); if (!Number.isSafeInteger(parsed) || parsed < minimum || parsed > maximum) throw new PlatformError(`${label} is invalid.`, 422, 'VALIDATION_FAILED'); return parsed;
};
const localDate = (timezone = BILLING_REPORTING_TIMEZONE, instant = new Date()) => {
  const parts = new Intl.DateTimeFormat('en-CA', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(instant);
  const get = (type: string) => parts.find(part => part.type === type)?.value || ''; return `${get('year')}-${get('month')}-${get('day')}`;
};
const shiftDays = (date: string, days: number) => { const result = new Date(`${date}T00:00:00Z`); result.setUTCDate(result.getUTCDate() + days); return result.toISOString().slice(0, 10); };
const firstOfMonth = (date: string) => `${date.slice(0, 7)}-01`;
const previousMonth = (date: string) => { const result = new Date(`${firstOfMonth(date)}T00:00:00Z`); result.setUTCMonth(result.getUTCMonth() - 1); return result.toISOString().slice(0, 10); };
const endOfMonth = (date: string) => shiftDays(firstOfMonth(shiftDays(firstOfMonth(date), 32)), -1);
const reportingInstant = (date: string) => new Date(`${date}T00:00:00+05:30`).toISOString();
const reportingBounds = (query: ReportingQuery) => ({ start: reportingInstant(query.dateFrom), end: reportingInstant(shiftDays(query.dateTo, 1)) });
const startOfWeek = (date: string) => { const day = new Date(`${date}T00:00:00Z`).getUTCDay(); return shiftDays(date, -(day === 0 ? 6 : day - 1)); };

export interface ReportingQuery { range: string; dateFrom: string; dateTo: string; timezone: string; environment: BillingEnvironment }
export function parseReportingQuery(raw: Record<string, unknown>, configured = activeBillingEnvironment()): ReportingQuery {
  const timezone = safeText(value(raw.timezone), 80) || BILLING_REPORTING_TIMEZONE;
  if (timezone !== BILLING_REPORTING_TIMEZONE) throw new PlatformError('The reporting timezone is not supported.', 422, 'VALIDATION_FAILED');
  const environment = (safeText(value(raw.environment), 20) || configured) as BillingEnvironment;
  if (!ENVIRONMENTS.has(environment)) throw new PlatformError('Billing environment is invalid.', 422, 'VALIDATION_FAILED');
  const range = safeText(value(raw.range), 30) || '30d'; const today = localDate(timezone); let dateFrom = ''; let dateTo = today;
  if (range === 'today') dateFrom = today;
  else if (range === 'yesterday') dateFrom = dateTo = shiftDays(today, -1);
  else if (range === '7d') dateFrom = shiftDays(today, -6);
  else if (range === '30d') dateFrom = shiftDays(today, -29);
  else if (range === '90d') dateFrom = shiftDays(today, -89);
  else if (range === 'current_month') dateFrom = firstOfMonth(today);
  else if (range === 'previous_month') { dateFrom = previousMonth(today); dateTo = endOfMonth(dateFrom); }
  else if (range === 'custom') { dateFrom = dateOnly(raw.from, 'From date'); dateTo = dateOnly(raw.to, 'To date'); if (!dateFrom || !dateTo) throw new PlatformError('Custom reports require both dates.', 422, 'VALIDATION_FAILED'); }
  else throw new PlatformError('Reporting range is invalid.', 422, 'VALIDATION_FAILED');
  const duration = Math.round((Date.parse(`${dateTo}T00:00:00Z`) - Date.parse(`${dateFrom}T00:00:00Z`)) / 86_400_000);
  if (duration < 0 || duration > BILLING_HEALTH_THRESHOLDS.maximumRangeDays) throw new PlatformError('Reporting date range is invalid or too large.', 422, 'VALIDATION_FAILED');
  return { range, dateFrom, dateTo, timezone, environment };
}

export interface PaymentListQuery extends ReportingQuery { search: string; status: string; plan: string; billingType: string; verified: string; relationship: string; amountFrom: number | null; amountTo: number | null; sort: string; page: number; pageSize: number }
export function parsePaymentQuery(raw: Record<string, unknown>, configured?: BillingEnvironment): PaymentListQuery {
  const hasExplicitDates = Boolean(raw.dateFrom || raw.dateTo || raw.from || raw.to);
  const reporting = parseReportingQuery({ ...raw, range: raw.range || (hasExplicitDates ? 'custom' : '30d'), from: raw.dateFrom || raw.from, to: raw.dateTo || raw.to }, configured);
  const status = safeText(value(raw.status), 40); const planValue = safeText(value(raw.plan), 40); const billingType = safeText(value(raw.billingType), 60);
  const verified = safeText(value(raw.verified), 10); const relationship = safeText(value(raw.relationship), 30); const sort = safeText(value(raw.sort), 40) || 'newest';
  if (status && !PAYMENT_STATUSES.has(status)) throw new PlatformError('Payment status filter is invalid.', 422, 'VALIDATION_FAILED');
  if (planValue && !PLAN_FILTERS[planValue] && !resolvePlanKey(planValue)) throw new PlatformError('Payment plan filter is invalid.', 422, 'VALIDATION_FAILED');
  if (billingType && !BILLING_TYPES.has(billingType)) throw new PlatformError('Billing type filter is invalid.', 422, 'VALIDATION_FAILED');
  if (verified && !['true', 'false'].includes(verified)) throw new PlatformError('Verification filter is invalid.', 422, 'VALIDATION_FAILED');
  if (relationship && !['subscription', 'one_time'].includes(relationship)) throw new PlatformError('Payment relationship filter is invalid.', 422, 'VALIDATION_FAILED');
  if (!PAYMENT_SORTS[sort]) throw new PlatformError('Payment sorting is invalid.', 422, 'VALIDATION_FAILED');
  const amountFrom = integer(raw.amountFrom, 'Minimum amount'); const amountTo = integer(raw.amountTo, 'Maximum amount'); if (amountFrom !== null && amountTo !== null && amountFrom > amountTo) throw new PlatformError('Payment amount range is invalid.', 422, 'VALIDATION_FAILED');
  const page = integer(raw.page || 1, 'Page', 1, 1_000_000)!; const pageSize = integer(raw.pageSize || 25, 'Page size', 1, 100)!; if (![25, 50, 100].includes(pageSize)) throw new PlatformError('Page size is invalid.', 422, 'VALIDATION_FAILED');
  return { ...reporting, search: safeText(value(raw.search), 160), status, plan: PLAN_FILTERS[planValue] || resolvePlanKey(planValue) || '', billingType, verified, relationship, amountFrom, amountTo, sort, page, pageSize };
}

export interface SubscriptionListQuery extends ReportingQuery { search: string; status: string; plan: string; billingMode: string; cancelled: string; attention: string; periodEndFrom: string; periodEndTo: string; sort: string; page: number; pageSize: number }
export function parseSubscriptionQuery(raw: Record<string, unknown>, configured?: BillingEnvironment): SubscriptionListQuery {
  const reporting = parseReportingQuery({ ...raw, range: raw.range || '30d' }, configured); const status = safeText(value(raw.status), 40); const planValue = safeText(value(raw.plan), 40);
  const billingMode = safeText(value(raw.billingMode), 60); const cancelled = safeText(value(raw.cancelled), 10); const attention = safeText(value(raw.attention), 10); const sort = safeText(value(raw.sort), 40) || 'recently_updated';
  if (status && !SUBSCRIPTION_STATUSES.has(status)) throw new PlatformError('Subscription status filter is invalid.', 422, 'VALIDATION_FAILED');
  if (planValue && !PLAN_FILTERS[planValue] && !resolvePlanKey(planValue)) throw new PlatformError('Subscription plan filter is invalid.', 422, 'VALIDATION_FAILED');
  if (billingMode && !['one_time_monthly', 'recurring_subscription'].includes(billingMode)) throw new PlatformError('Billing mode filter is invalid.', 422, 'VALIDATION_FAILED');
  if (cancelled && !['true', 'false'].includes(cancelled)) throw new PlatformError('Cancellation filter is invalid.', 422, 'VALIDATION_FAILED');
  if (attention && !['true', 'false'].includes(attention)) throw new PlatformError('Attention filter is invalid.', 422, 'VALIDATION_FAILED');
  if (!SUBSCRIPTION_SORTS[sort]) throw new PlatformError('Subscription sorting is invalid.', 422, 'VALIDATION_FAILED');
  const periodEndFrom = dateOnly(raw.periodEndFrom, 'Period end start'); const periodEndTo = dateOnly(raw.periodEndTo, 'Period end finish'); if (periodEndFrom && periodEndTo && periodEndFrom > periodEndTo) throw new PlatformError('Subscription period range is invalid.', 422, 'VALIDATION_FAILED');
  const page = integer(raw.page || 1, 'Page', 1, 1_000_000)!; const pageSize = integer(raw.pageSize || 25, 'Page size', 1, 100)!; if (![25, 50, 100].includes(pageSize)) throw new PlatformError('Page size is invalid.', 422, 'VALIDATION_FAILED');
  return { ...reporting, search: safeText(value(raw.search), 160), status, plan: PLAN_FILTERS[planValue] || resolvePlanKey(planValue) || '', billingMode, cancelled, attention, periodEndFrom, periodEndTo, sort, page, pageSize };
}

const verifiedRevenueSql = `payments.status='captured' AND payments.signature_verified=TRUE AND payments.verification_state='verified' AND payments.currency='INR' AND payments.provider_payment_id IS NOT NULL AND payments.amount_paise=payments.expected_amount_paise`;
const paymentColumns = `payments.id, payments.user_id AS "userId", users.name AS "customerName", users.email AS "customerEmail", payments.workspace_id AS "workspaceId", payments.internal_plan_key AS "planKey", payments.billing_type AS "billingType", payments.amount_paise::int AS "amountPaise", payments.currency, payments.status, payments.provider, payments.provider_payment_id AS "providerPaymentId", payments.provider_order_id AS "providerOrderId", payments.provider_subscription_id AS "providerSubscriptionId", payments.subscription_id AS "subscriptionId", payments.signature_verified AS "signatureVerified", payments.verification_state AS "verificationState", payments.captured_at AS "capturedAt", payments.access_period_start AS "accessPeriodStart", payments.access_period_end AS "accessPeriodEnd", payments.failure_code AS "failureCode", payments.reconciliation_status AS "reconciliationStatus", payments.last_reconciled_at AS "lastReconciledAt", payments.billing_environment AS environment, payments.created_at AS "createdAt", payments.updated_at AS "updatedAt"`;
const subscriptionColumns = `subscriptions.id, subscriptions.user_id AS "userId", users.name AS "customerName", users.email AS "customerEmail", users.effective_plan AS "currentEffectivePlan", subscriptions.workspace_id AS "workspaceId", subscriptions.internal_plan_key AS "planKey", subscriptions.billing_mode AS "billingMode", subscriptions.provider, subscriptions.provider_plan_id AS "providerPlanId", subscriptions.provider_subscription_id AS "providerSubscriptionId", subscriptions.status, subscriptions.amount_paise::int AS "amountPaise", subscriptions.currency, subscriptions.billing_interval AS "billingInterval", subscriptions.current_period_start AS "currentPeriodStart", subscriptions.current_period_end AS "currentPeriodEnd", subscriptions.next_charge_at AS "nextChargeAt", subscriptions.cancel_at_period_end AS "cancelAtPeriodEnd", subscriptions.cancelled_at AS "cancelledAt", subscriptions.latest_payment_id AS "latestPaymentId", subscriptions.latest_payment_at AS "latestPaymentAt", subscriptions.verification_error AS "verificationError", subscriptions.reconciliation_status AS "reconciliationStatus", subscriptions.last_reconciled_at AS "lastReconciledAt", subscriptions.last_provider_event_at AS "lastProviderEventAt", subscriptions.billing_environment AS environment, subscriptions.created_at AS "createdAt", subscriptions.updated_at AS "updatedAt"`;
const maskReference = (input: unknown) => { const text = safeText(input, 180); return text ? `••••${text.slice(-8)}` : null; };
const safePayment = (row: any) => ({ ...row, providerPaymentReference: maskReference(row.providerPaymentId), providerOrderReference: maskReference(row.providerOrderId), providerSubscriptionReference: maskReference(row.providerSubscriptionId), providerPaymentId: undefined, providerOrderId: undefined, providerSubscriptionId: undefined });
const safeSubscription = (row: any) => ({ ...row, providerSubscriptionReference: maskReference(row.providerSubscriptionId), providerPlanReference: maskReference(row.providerPlanId), latestPaymentReference: maskReference(row.latestPaymentId), providerSubscriptionId: undefined, providerPlanId: undefined, latestPaymentId: undefined });

function paymentWhere(query: PaymentListQuery) { const conditions = ['payments.billing_environment = $1']; const values: unknown[] = [query.environment]; const add = (sql: string, item: unknown) => { values.push(item); conditions.push(sql.replaceAll('?', `$${values.length}`)); };
  if (query.search) add("(users.name ILIKE '%'||?||'%' OR users.email ILIKE '%'||?||'%' OR payments.user_id ILIKE '%'||?||'%' OR payments.provider_payment_id ILIKE '%'||?||'%' OR payments.provider_order_id ILIKE '%'||?||'%' OR payments.provider_subscription_id ILIKE '%'||?||'%')", query.search);
  if (query.status) add('payments.status=?', query.status); if (query.plan) add('payments.internal_plan_key=?', query.plan); if (query.billingType) add('payments.billing_type=?', query.billingType);
  if (query.verified) conditions.push(query.verified === 'true' ? `(${verifiedRevenueSql})` : `NOT (${verifiedRevenueSql})`); if (query.relationship) conditions.push(query.relationship === 'subscription' ? 'payments.subscription_id IS NOT NULL' : 'payments.subscription_id IS NULL');
  if (query.amountFrom !== null) add('payments.amount_paise>=?', query.amountFrom); if (query.amountTo !== null) add('payments.amount_paise<=?', query.amountTo);
  const bounds = reportingBounds(query); add('payments.created_at >= ?::timestamptz', bounds.start); add('payments.created_at < ?::timestamptz', bounds.end);
  return { sql: conditions.join(' AND '), values };
}
function subscriptionWhere(query: SubscriptionListQuery) { const conditions = ['subscriptions.billing_environment = $1']; const values: unknown[] = [query.environment]; const add = (sql: string, item: unknown) => { values.push(item); conditions.push(sql.replaceAll('?', `$${values.length}`)); };
  if (query.search) add("(users.name ILIKE '%'||?||'%' OR users.email ILIKE '%'||?||'%' OR subscriptions.user_id ILIKE '%'||?||'%' OR subscriptions.provider_subscription_id ILIKE '%'||?||'%')", query.search);
  if (query.status) add('subscriptions.status=?', query.status); if (query.plan) add('subscriptions.internal_plan_key=?', query.plan); if (query.billingMode) add('subscriptions.billing_mode=?', query.billingMode);
  if (query.cancelled) conditions.push(query.cancelled === 'true' ? '(subscriptions.cancel_at_period_end=TRUE OR subscriptions.cancelled_at IS NOT NULL)' : '(subscriptions.cancel_at_period_end=FALSE AND subscriptions.cancelled_at IS NULL)');
  if (query.attention) { const expression = "(subscriptions.status IN ('pending','halted') OR subscriptions.reconciliation_status='attention' OR (subscriptions.status='active' AND (subscriptions.current_period_end IS NULL OR subscriptions.current_period_end<=NOW())))"; conditions.push(query.attention === 'true' ? expression : `NOT ${expression}`); }
  if (query.periodEndFrom) add('subscriptions.current_period_end >= ?::timestamptz', reportingInstant(query.periodEndFrom)); if (query.periodEndTo) add('subscriptions.current_period_end < ?::timestamptz', reportingInstant(shiftDays(query.periodEndTo, 1)));
  return { sql: conditions.join(' AND '), values };
}

export class BillingAnalyticsRepository {
  constructor(private readonly pool: Pool) {}
  async summary(query: ReportingQuery) {
    const today = localDate(query.timezone); const selected = reportingBounds(query);
    const todayStart = reportingInstant(today); const weekStart = reportingInstant(startOfWeek(today)); const monthStart = reportingInstant(firstOfMonth(today)); const previousMonthStart = reportingInstant(previousMonth(today));
    const result = await this.pool.query(`SELECT
      coalesce(sum(CASE WHEN ${verifiedRevenueSql} AND captured_at >= $6::timestamptz AND captured_at < $7::timestamptz THEN amount_paise ELSE 0 END),0)::bigint AS "totalRevenuePaise",
      coalesce(sum(CASE WHEN ${verifiedRevenueSql} AND captured_at >= $2::timestamptz THEN amount_paise ELSE 0 END),0)::bigint AS "revenueTodayPaise",
      coalesce(sum(CASE WHEN ${verifiedRevenueSql} AND captured_at >= $3::timestamptz THEN amount_paise ELSE 0 END),0)::bigint AS "revenueThisWeekPaise",
      coalesce(sum(CASE WHEN ${verifiedRevenueSql} AND captured_at >= $4::timestamptz THEN amount_paise ELSE 0 END),0)::bigint AS "revenueThisMonthPaise",
      coalesce(sum(CASE WHEN ${verifiedRevenueSql} AND captured_at >= $5::timestamptz AND captured_at < $4::timestamptz THEN amount_paise ELSE 0 END),0)::bigint AS "previousMonthRevenuePaise",
      coalesce(sum(CASE WHEN ${verifiedRevenueSql} AND captured_at >= $6::timestamptz AND captured_at < $7::timestamptz THEN amount_paise ELSE 0 END),0)::bigint AS "selectedRevenuePaise",
      sum(CASE WHEN ${verifiedRevenueSql} AND captured_at >= $6::timestamptz AND captured_at < $7::timestamptz THEN 1 ELSE 0 END)::int AS "successfulPayments",
      sum(CASE WHEN status IN ('failed','verification_failed','webhook_rejected') AND created_at >= $6::timestamptz AND created_at < $7::timestamptz THEN 1 ELSE 0 END)::int AS "failedPayments",
      sum(CASE WHEN status IN ('pending','checkout_created','authorized') AND created_at >= $6::timestamptz AND created_at < $7::timestamptz THEN 1 ELSE 0 END)::int AS "pendingPayments"
      FROM gxa_billing_payments payments WHERE payments.billing_environment=$1`, [query.environment, todayStart, weekStart, monthStart, previousMonthStart, selected.start, selected.end]);
    const subscriptions = await this.pool.query(`SELECT coalesce(sum(CASE WHEN billing_mode='recurring_subscription' AND status='active' AND currency='INR' AND current_period_end>NOW() THEN amount_paise ELSE 0 END),0)::bigint AS "mrrPaise", sum(CASE WHEN status='active' AND current_period_end>NOW() THEN 1 ELSE 0 END)::int AS "activePaidSubscriptions", sum(CASE WHEN status='pending' THEN 1 ELSE 0 END)::int AS "pendingSubscriptions", sum(CASE WHEN status='halted' THEN 1 ELSE 0 END)::int AS "haltedSubscriptions", sum(CASE WHEN status='paused' THEN 1 ELSE 0 END)::int AS "pausedSubscriptions", sum(CASE WHEN status='cancelled' THEN 1 ELSE 0 END)::int AS "cancelledSubscriptions", sum(CASE WHEN status='expired' THEN 1 ELSE 0 END)::int AS "expiredSubscriptions", sum(CASE WHEN status IN ('pending','halted') OR reconciliation_status='attention' THEN 1 ELSE 0 END)::int AS "renewalFailures" FROM gxa_billing_subscriptions WHERE billing_environment=$1`, [query.environment]);
    const payment = result.rows[0]; const subscription = subscriptions.rows[0]; const total = Number(payment.totalRevenuePaise || 0); const successful = Number(payment.successfulPayments || 0); const current = Number(payment.revenueThisMonthPaise || 0); const previous = Number(payment.previousMonthRevenuePaise || 0); const mrr = Number(subscription.mrrPaise || 0);
    const recent = await this.pool.query(`SELECT ${paymentColumns} FROM gxa_billing_payments payments LEFT JOIN gxa_admin_users users ON users.user_id=payments.user_id WHERE payments.billing_environment=$1 AND payments.created_at >= $2::timestamptz AND payments.created_at < $3::timestamptz ORDER BY payments.created_at DESC LIMIT 10`, [query.environment, selected.start, selected.end]);
    const reconciliation = await this.pool.query(`SELECT id,status,records_checked AS "recordsChecked",records_unchanged AS "recordsUnchanged",records_synchronized AS "recordsSynchronized",records_attention AS "recordsAttention",error_count AS "errorCount",started_at AS "startedAt",completed_at AS "completedAt" FROM gxa_billing_reconciliation_runs WHERE billing_environment=$1 ORDER BY created_at DESC LIMIT 1`, [query.environment]);
    return { reporting: query, generatedAt: new Date().toISOString(), metrics: { ...payment, ...subscription, totalRevenuePaise: total, revenueTodayPaise: Number(payment.revenueTodayPaise || 0), revenueThisWeekPaise: Number(payment.revenueThisWeekPaise || 0), revenueThisMonthPaise: current, previousMonthRevenuePaise: previous, selectedRevenuePaise: Number(payment.selectedRevenuePaise || 0), averageSuccessfulPaymentPaise: successful ? Math.round(total / successful) : 0, monthOverMonthPercent: previous ? Number((((current - previous) / previous) * 100).toFixed(2)) : null, mrrPaise: mrr, estimatedArrPaise: mrr * 12, refundsConfigured: false }, recentPayments: recent.rows.map(safePayment), latestReconciliation: reconciliation.rows[0] || null };
  }
  async revenueTrend(query: ReportingQuery) {
    const bounds = reportingBounds(query);
    const rows = await this.pool.query(`SELECT (captured_at AT TIME ZONE $2)::date::text date,coalesce(sum(CASE WHEN ${verifiedRevenueSql} THEN amount_paise ELSE 0 END),0)::bigint AS "revenuePaise",sum(CASE WHEN ${verifiedRevenueSql} THEN 1 ELSE 0 END)::int AS "successfulPayments",sum(CASE WHEN ${verifiedRevenueSql} AND billing_type='initial_subscription_payment' THEN 1 ELSE 0 END)::int AS "newPaidSubscriptions",sum(CASE WHEN ${verifiedRevenueSql} AND billing_type='recurring_renewal' THEN 1 ELSE 0 END)::int AS "successfulRenewals" FROM gxa_billing_payments payments WHERE billing_environment=$1 AND captured_at >= $3::timestamptz AND captured_at < $4::timestamptz GROUP BY 1 ORDER BY 1`, [query.environment, query.timezone, bounds.start, bounds.end]);
    const byDate = new Map(rows.rows.map(row => [String(row.date), row])); const points = [];
    for (let date = query.dateFrom; date <= query.dateTo; date = shiftDays(date, 1)) {
      const point: any = byDate.get(date); points.push({ date, revenuePaise: Number(point?.revenuePaise || 0), successfulPayments: Number(point?.successfulPayments || 0), newPaidSubscriptions: Number(point?.newPaidSubscriptions || 0), successfulRenewals: Number(point?.successfulRenewals || 0) });
    }
    return { reporting: query, points };
  }
  async planDistribution(query: ReportingQuery) {
    const bounds = reportingBounds(query); const rows = await this.pool.query(`WITH plans AS (SELECT 'pro'::text AS plan_key UNION ALL SELECT 'pro_plus'::text UNION ALL SELECT 'business-pro'::text), revenue AS (SELECT internal_plan_key,sum(CASE WHEN ${verifiedRevenueSql} THEN 1 ELSE 0 END)::int payments,coalesce(sum(CASE WHEN ${verifiedRevenueSql} THEN amount_paise ELSE 0 END),0)::bigint revenue,sum(CASE WHEN ${verifiedRevenueSql} AND billing_type='recurring_renewal' THEN 1 ELSE 0 END)::int renewals FROM gxa_billing_payments payments WHERE billing_environment=$1 AND captured_at >= $2::timestamptz AND captured_at < $3::timestamptz GROUP BY internal_plan_key), subscriptions AS (SELECT internal_plan_key,sum(CASE WHEN status='active' AND current_period_end>NOW() THEN 1 ELSE 0 END)::int active,sum(CASE WHEN status='cancelled' THEN 1 ELSE 0 END)::int cancelled,sum(CASE WHEN status IN ('pending','halted') THEN 1 ELSE 0 END)::int renewal_failures FROM gxa_billing_subscriptions WHERE billing_environment=$1 GROUP BY internal_plan_key) SELECT plans.plan_key AS "planKey",coalesce(revenue.payments,0)::int AS "successfulPayments",coalesce(revenue.revenue,0)::bigint AS "revenuePaise",coalesce(subscriptions.active,0)::int AS "activeSubscribers",coalesce(subscriptions.cancelled,0)::int AS "cancelledSubscribers",coalesce(revenue.renewals,0)::int AS "renewalSuccesses",coalesce(subscriptions.renewal_failures,0)::int AS "renewalFailures" FROM plans LEFT JOIN revenue ON revenue.internal_plan_key=plans.plan_key LEFT JOIN subscriptions ON subscriptions.internal_plan_key=plans.plan_key`, [query.environment, bounds.start, bounds.end]);
    const total = rows.rows.reduce((sum, row) => sum + Number(row.revenuePaise || 0), 0); return { reporting: query, plans: rows.rows.map(row => ({ ...row, planName: PLAN_REGISTRY[row.planKey as PlanId]?.name || row.planKey, revenuePaise: Number(row.revenuePaise || 0), revenuePercent: total ? Number((Number(row.revenuePaise || 0) / total * 100).toFixed(2)) : 0 })) };
  }
  async listPayments(query: PaymentListQuery, exportLimit?: number) { const where = paymentWhere(query); const count = await this.pool.query(`SELECT count(*)::int total FROM gxa_billing_payments payments LEFT JOIN gxa_admin_users users ON users.user_id=payments.user_id WHERE ${where.sql}`, where.values); const values = [...where.values]; const limit = exportLimit || query.pageSize; values.push(limit, exportLimit ? 0 : (query.page - 1) * query.pageSize); const rows = await this.pool.query(`SELECT ${paymentColumns} FROM gxa_billing_payments payments LEFT JOIN gxa_admin_users users ON users.user_id=payments.user_id WHERE ${where.sql} ORDER BY ${PAYMENT_SORTS[query.sort]} LIMIT $${values.length - 1} OFFSET $${values.length}`, values); const total = Number(count.rows[0]?.total || 0); return { payments: rows.rows.map(safePayment), pagination: { page: query.page, pageSize: query.pageSize, total, totalPages: Math.max(1, Math.ceil(total / query.pageSize)) }, filters: query }; }
  async paymentDetail(id: string) { const result = await this.pool.query(`SELECT ${paymentColumns} FROM gxa_billing_payments payments LEFT JOIN gxa_admin_users users ON users.user_id=payments.user_id WHERE payments.id=$1`, [safeText(id, 180)]); if (!result.rowCount) return null; const row = result.rows[0]; const events = row.subscriptionId ? await this.pool.query(`SELECT event_type AS "eventType",processing_status AS "processingStatus",processing_error AS "processingError",provider_created_at AS "providerCreatedAt",processed_at AS "processedAt",created_at AS "createdAt" FROM gxa_billing_subscription_events WHERE subscription_id=$1 ORDER BY created_at DESC LIMIT 25`, [row.subscriptionId]) : { rows: [] }; return { payment: safePayment(row), lifecycleEvents: events.rows, idempotency: { uniqueProviderPayment: Boolean(row.providerPaymentId), result: row.providerPaymentId ? 'enforced' : 'not_available' } }; }
  async listSubscriptions(query: SubscriptionListQuery, exportLimit?: number) { const where = subscriptionWhere(query); const count = await this.pool.query(`SELECT count(*)::int total FROM gxa_billing_subscriptions subscriptions LEFT JOIN gxa_admin_users users ON users.user_id=subscriptions.user_id WHERE ${where.sql}`, where.values); const values = [...where.values]; const limit = exportLimit || query.pageSize; values.push(limit, exportLimit ? 0 : (query.page - 1) * query.pageSize); const rows = await this.pool.query(`SELECT ${subscriptionColumns} FROM gxa_billing_subscriptions subscriptions LEFT JOIN gxa_admin_users users ON users.user_id=subscriptions.user_id WHERE ${where.sql} ORDER BY ${SUBSCRIPTION_SORTS[query.sort]} LIMIT $${values.length - 1} OFFSET $${values.length}`, values); const total = Number(count.rows[0]?.total || 0); return { subscriptions: rows.rows.map(safeSubscription), pagination: { page: query.page, pageSize: query.pageSize, total, totalPages: Math.max(1, Math.ceil(total / query.pageSize)) }, filters: query }; }
  async subscriptionDetail(id: string) { const result = await this.pool.query(`SELECT ${subscriptionColumns} FROM gxa_billing_subscriptions subscriptions LEFT JOIN gxa_admin_users users ON users.user_id=subscriptions.user_id WHERE subscriptions.id=$1`, [safeText(id, 180)]); if (!result.rowCount) return null; const row = result.rows[0]; const [payments, events] = await Promise.all([this.pool.query(`SELECT ${paymentColumns} FROM gxa_billing_payments payments LEFT JOIN gxa_admin_users users ON users.user_id=payments.user_id WHERE payments.subscription_id=$1 ORDER BY payments.created_at DESC LIMIT 50`, [row.id]), this.pool.query(`SELECT event_type AS "eventType",processing_status AS "processingStatus",processing_error AS "processingError",provider_created_at AS "providerCreatedAt",processed_at AS "processedAt",created_at AS "createdAt" FROM gxa_billing_subscription_events WHERE subscription_id=$1 ORDER BY created_at DESC LIMIT 50`, [row.id])]); return { subscription: safeSubscription(row), renewalHistory: payments.rows.map(safePayment), lifecycleEvents: events.rows }; }
  async health(query: ReportingQuery) { const payment = await this.pool.query(`SELECT sum(CASE WHEN status IN ('pending','checkout_created') AND created_at<NOW()-interval '${BILLING_HEALTH_THRESHOLDS.pendingMinutes} minutes' THEN 1 ELSE 0 END)::int AS "stalePendingPayments",sum(CASE WHEN status='authorized' THEN 1 ELSE 0 END)::int AS "authorizedUncaptured",sum(CASE WHEN status='verification_failed' THEN 1 ELSE 0 END)::int AS "verificationFailures",sum(CASE WHEN failure_code ILIKE '%mismatch%' OR amount_paise<>expected_amount_paise OR currency<>'INR' THEN 1 ELSE 0 END)::int AS "amountMismatches",sum(CASE WHEN user_id IS NULL THEN 1 ELSE 0 END)::int AS "missingPaymentUsers",sum(CASE WHEN workspace_id IS NULL THEN 1 ELSE 0 END)::int AS "missingPaymentWorkspaces" FROM gxa_billing_payments WHERE billing_environment=$1`, [query.environment]); const events = await this.pool.query(`SELECT sum(CASE WHEN processing_status='failed' THEN 1 ELSE 0 END)::int AS "failedWebhookEvents",sum(CASE WHEN processing_status='processing' AND created_at<NOW()-interval '${BILLING_HEALTH_THRESHOLDS.webhookMinutes} minutes' THEN 1 ELSE 0 END)::int AS "unprocessedWebhookEvents",sum(CASE WHEN processing_status='rejected' THEN 1 ELSE 0 END)::int AS "rejectedWebhookEvents" FROM gxa_billing_subscription_events WHERE billing_environment=$1`, [query.environment]); const subscriptions = await this.pool.query(`SELECT sum(CASE WHEN billing_mode='recurring_subscription' AND status IN ('created','authenticated','active','pending','halted','paused') AND (last_reconciled_at IS NULL OR last_reconciled_at<NOW()-interval '${BILLING_HEALTH_THRESHOLDS.reconciliationHours} hours') THEN 1 ELSE 0 END)::int AS "staleSubscriptions",sum(CASE WHEN status='halted' THEN 1 ELSE 0 END)::int AS "haltedSubscriptions",sum(CASE WHEN status IN ('pending','halted') THEN 1 ELSE 0 END)::int AS "renewalFailures",sum(CASE WHEN status='active' AND current_period_end<=NOW() THEN 1 ELSE 0 END)::int AS "expiredMarkedActive",sum(CASE WHEN status='active' AND (current_period_end IS NULL OR current_period_end<=NOW()) THEN 1 ELSE 0 END)::int AS "activeWithoutPaidPeriod",sum(CASE WHEN reconciliation_status='attention' THEN 1 ELSE 0 END)::int AS "providerStateMismatches",sum(CASE WHEN user_id IS NULL THEN 1 ELSE 0 END)::int AS "missingSubscriptionUsers",sum(CASE WHEN workspace_id IS NULL THEN 1 ELSE 0 END)::int AS "missingSubscriptionWorkspaces" FROM gxa_billing_subscriptions WHERE billing_environment=$1`, [query.environment]); return { reporting: query, thresholds: BILLING_HEALTH_THRESHOLDS, indicators: { ...payment.rows[0], ...events.rows[0], ...subscriptions.rows[0], duplicateProviderEventsPrevented: 0 }, notes: { duplicateProviderEventsPrevented: 'Unique provider event and payment constraints are active; duplicate attempts are not stored as financial records.' } }; }
}

const csvCell = (input: unknown) => { let text = String(input ?? '').replace(/\r?\n/g, ' '); if (/^[=+\-@]/.test(text)) text = `'${text}`; return `"${text.replace(/"/g, '""')}"`; };
const csv = (headers: string[], rows: unknown[][]) => `\uFEFF${[headers, ...rows].map(row => row.map(csvCell).join(',')).join('\r\n')}\r\n`;
export function paymentsCsv(rows: any[]) { return csv(['payment_id','user_id','customer_name','customer_email','plan','billing_type','amount_paise','formatted_amount','currency','status','provider_payment_reference','provider_order_reference','provider_subscription_reference','captured_at','created_at','environment'], rows.map(row => [row.id,row.userId,row.customerName,row.customerEmail,PLAN_REGISTRY[row.planKey as PlanId]?.name || row.planKey,row.billingType,row.amountPaise,new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(row.amountPaise || 0)/100),row.currency,row.status,row.providerPaymentReference,row.providerOrderReference,row.providerSubscriptionReference,row.capturedAt,row.createdAt,row.environment])); }
export function subscriptionsCsv(rows: any[]) { return csv(['subscription_id','user_id','customer_name','customer_email','plan','amount_paise','currency','status','billing_mode','current_period_start','current_period_end','next_charge_at','cancel_at_period_end','cancelled_at','environment','latest_payment_reference'], rows.map(row => [row.id,row.userId,row.customerName,row.customerEmail,PLAN_REGISTRY[row.planKey as PlanId]?.name || row.planKey,row.amountPaise,row.currency,row.status,row.billingMode,row.currentPeriodStart,row.currentPeriodEnd,row.nextChargeAt,row.cancelAtPeriodEnd,row.cancelledAt,row.environment,row.latestPaymentReference])); }
