export type SupportedLanguage = 'English' | 'Hindi' | 'Hinglish';
export type ConfidenceBand = 'Low confidence' | 'Moderate confidence' | 'Higher confidence';
export type DetectionClassification = 'Strong AI-like indicators' | 'Moderate AI-like indicators' | 'Mixed indicators' | 'Mostly human-like indicators' | 'Insufficient evidence' | 'Unable to determine';

export interface TextSegment { id: string; type: 'sentence' | 'paragraph'; startOffset: number; endOffset: number; text: string; classification: DetectionClassification; confidenceBand: ConfidenceBand; estimatedAiLikelihood?: number; indicators: string[]; explanation: string }
export interface WritingMetrics { words: number; characters: number; charactersWithoutSpaces: number; sentences: number; paragraphs: number; readingMinutes: number; speakingMinutes: number; averageWordsPerSentence: number; averageSentencesPerParagraph: number; uniqueWords: number; lexicalDiversity: number; repeatedWords: Array<{ word: string; count: number }>; questions: number; exclamations: number; readingEase?: number; gradeLevel?: number }

export class OriginalityValidationError extends Error { constructor(message: string, public status = 400, public code = 'INVALID_ORIGINALITY_REQUEST') { super(message); } }
export const MIN_DETECTION_WORDS = 50;
export const DETECTOR_VERSION = 'gxa-indicator-model-1.0';
export const DETECTOR_LIMITATIONS = [
  'AI detection is an estimate; false positives and false negatives are possible.',
  'Edited AI content may appear human-like, while formal or non-native writing may be misclassified.',
  'Do not use this result as the sole basis for academic, employment, legal or disciplinary decisions.'
];

export function normalizeText(value: unknown, maxCharacters = 30_000) { if (typeof value !== 'string' || !value.trim()) throw new OriginalityValidationError('Enter text to analyze.'); const text = value.replace(/\r\n/g, '\n').trim(); if (text.length > maxCharacters) throw new OriginalityValidationError(`Text exceeds the configured ${maxCharacters.toLocaleString()} character limit.`, 413, 'INPUT_TOO_LARGE'); return text; }
export function detectContentLanguage(text: string): SupportedLanguage { const devanagari = (text.match(/[\u0900-\u097F]/g) || []).length; const romanHindi = (text.toLowerCase().match(/\b(hai|hain|kya|aur|lekin|nahi|ka|ki|ke|mein|mera|aap)\b/g) || []).length; if (devanagari > Math.max(3, text.length * .08)) return 'Hindi'; if (romanHindi >= 3) return 'Hinglish'; return 'English'; }
const wordsOf = (text: string): string[] => text.toLowerCase().match(/[\p{L}\p{N}']+/gu) || [];
export function segmentText(text: string, type: 'sentence' | 'paragraph') {
  const pattern = type === 'paragraph' ? /[^\n]+(?:\n+|$)/g : /[^.!?\n]+(?:[.!?]+|\n+|$)/g; const result: Array<{ text: string; startOffset: number; endOffset: number }> = []; let match: RegExpExecArray | null;
  while ((match = pattern.exec(text))) { const raw = match[0]; const leading = raw.search(/\S/); if (leading < 0) continue; const trimmed = raw.trim(); result.push({ text: trimmed, startOffset: match.index + leading, endOffset: match.index + leading + trimmed.length }); }
  return result;
}
export function calculateWritingMetrics(text: string, language: SupportedLanguage = detectContentLanguage(text)): WritingMetrics {
  const words = wordsOf(text); const sentences = segmentText(text, 'sentence'); const paragraphs = segmentText(text, 'paragraph'); const frequencies = new Map<string, number>(); words.forEach(word => frequencies.set(word, (frequencies.get(word) || 0) + 1)); const unique = frequencies.size;
  const metrics: WritingMetrics = { words: words.length, characters: text.length, charactersWithoutSpaces: text.replace(/\s/g, '').length, sentences: sentences.length, paragraphs: paragraphs.length, readingMinutes: Math.max(1, Math.ceil(words.length / 225)), speakingMinutes: Math.max(1, Math.ceil(words.length / 130)), averageWordsPerSentence: sentences.length ? Math.round(words.length / sentences.length) : 0, averageSentencesPerParagraph: paragraphs.length ? Math.round((sentences.length / paragraphs.length) * 10) / 10 : 0, uniqueWords: unique, lexicalDiversity: words.length ? Math.round(unique / words.length * 100) : 0, repeatedWords: [...frequencies].filter(([, count]) => count >= 3).sort((a, b) => b[1] - a[1]).slice(0, 12).map(([word, count]) => ({ word, count })), questions: (text.match(/\?/g) || []).length, exclamations: (text.match(/!/g) || []).length };
  if (language === 'English' && words.length) { const syllables = words.reduce((total, word) => total + Math.max(1, (word.match(/[aeiouy]+/g) || []).length - (/e$/.test(word) ? 1 : 0)), 0); metrics.readingEase = Math.round(Math.max(0, Math.min(100, 206.835 - 1.015 * (words.length / Math.max(1, sentences.length)) - 84.6 * (syllables / words.length)))); metrics.gradeLevel = Math.round(Math.max(0, .39 * (words.length / Math.max(1, sentences.length)) + 11.8 * (syllables / words.length) - 15.59)); }
  return metrics;
}
function indicatorsFor(text: string) { const words = wordsOf(text); const sentences = segmentText(text, 'sentence'); const indicators: string[] = []; const buzz = ['delve', 'landscape', 'leveraging', 'unlock', 'unprecedented', 'furthermore', 'moreover', 'robust', 'seamless']; const buzzCount = buzz.filter(word => words.includes(word)).length; const lengths = sentences.map(sentence => wordsOf(sentence.text).length); const average = lengths.reduce((sum, value) => sum + value, 0) / Math.max(1, lengths.length); const variance = lengths.reduce((sum, value) => sum + Math.pow(value - average, 2), 0) / Math.max(1, lengths.length); if (buzzCount >= 2) indicators.push('Several formulaic transition or promotional terms appear.'); if (sentences.length >= 4 && variance < 12) indicators.push('Sentence lengths are unusually uniform.'); if (new Set(words).size / Math.max(1, words.length) < .42) indicators.push('Vocabulary variation is limited for this sample.'); if ((text.match(/\b(furthermore|moreover|additionally|in conclusion)\b/gi) || []).length >= 2) indicators.push('Transitions follow a repeated formal pattern.'); return indicators; }
function segmentResult(segment: { text: string; startOffset: number; endOffset: number }, type: 'sentence' | 'paragraph', language: SupportedLanguage, index: number): TextSegment { const indicators = indicatorsFor(segment.text); const likelihood = Math.min(78, 30 + indicators.length * 14); const classification: DetectionClassification = likelihood >= 65 ? 'Moderate AI-like indicators' : likelihood >= 45 ? 'Mixed indicators' : 'Mostly human-like indicators'; return { id: `${type}-${index + 1}`, type, ...segment, classification, confidenceBand: language === 'English' && wordsOf(segment.text).length >= 20 ? 'Moderate confidence' : 'Low confidence', estimatedAiLikelihood: likelihood, indicators, explanation: indicators.length ? 'These patterns may contribute to the estimate; none proves authorship.' : 'This segment has limited measurable AI-like pattern evidence.' }; }
export function analyzeDetection(value: unknown, requestedLanguage?: string, maxCharacters = 30_000) {
  const text = normalizeText(value, maxCharacters); const language = (requestedLanguage === 'Auto' || !requestedLanguage ? detectContentLanguage(text) : requestedLanguage) as SupportedLanguage; if (language !== 'English' && language !== 'Hindi' && language !== 'Hinglish') throw new OriginalityValidationError('Supported languages are English, Hindi and Hinglish.', 400, 'UNSUPPORTED_LANGUAGE'); const metrics = calculateWritingMetrics(text, language); const sentenceResults = segmentText(text, 'sentence').map((segment, index) => segmentResult(segment, 'sentence', language, index)); const paragraphResults = segmentText(text, 'paragraph').map((segment, index) => segmentResult(segment, 'paragraph', language, index));
  if (metrics.words < MIN_DETECTION_WORDS) return { id: crypto.randomUUID(), classification: 'Insufficient evidence' as DetectionClassification, confidenceBand: 'Low confidence' as ConfidenceBand, language, metrics, sentenceResults: [], paragraphResults: [], indicators: [], limitations: DETECTOR_LIMITATIONS, modelVersion: DETECTOR_VERSION, createdAt: new Date().toISOString(), minimumUsefulWords: MIN_DETECTION_WORDS };
  const allIndicators = [...sentenceResults, ...paragraphResults].flatMap(segment => segment.indicators); const estimate = Math.min(82, Math.round(28 + allIndicators.length / Math.max(1, sentenceResults.length + paragraphResults.length) * 35)); const classification: DetectionClassification = estimate >= 68 ? 'Strong AI-like indicators' : estimate >= 55 ? 'Moderate AI-like indicators' : estimate >= 40 ? 'Mixed indicators' : 'Mostly human-like indicators'; const confidenceBand: ConfidenceBand = language === 'English' && metrics.words >= 150 ? 'Higher confidence' : language === 'English' ? 'Moderate confidence' : 'Low confidence';
  return { id: crypto.randomUUID(), classification, confidenceBand, estimatedAiLikelihood: estimate, language, metrics, sentenceResults, paragraphResults, indicators: [...new Set(allIndicators)], limitations: [...DETECTOR_LIMITATIONS, ...(language !== 'English' ? ['Hindi and Hinglish detection has limited calibration; English readability formulas are not applied.'] : [])], modelVersion: DETECTOR_VERSION, createdAt: new Date().toISOString(), minimumUsefulWords: MIN_DETECTION_WORDS };
}
export const HUMANIZER_MODES = ['Natural', 'Light Rewrite', 'Moderate Rewrite', 'Strong Rewrite', 'Professional', 'Academic', 'Conversational', 'Simple', 'Confident', 'Friendly'] as const;
export function validateHumanizerRequest(body: any, maxCharacters = 30_000) { const text = normalizeText(body.text, maxCharacters); const mode = HUMANIZER_MODES.includes(body.mode) ? body.mode : 'Natural'; const strength = ['Light', 'Moderate', 'Strong'].includes(body.strength) ? body.strength : 'Moderate'; const language = ['English', 'Hindi', 'Hinglish'].includes(body.language) ? body.language : detectContentLanguage(text); const preserve = { keywords: Array.isArray(body.preserve?.keywords) ? body.preserve.keywords.map(String).filter(Boolean).slice(0, 30) : [], headings: body.preserve?.headings !== false, citations: body.preserve?.citations !== false, urls: body.preserve?.urls !== false, numbers: body.preserve?.numbers !== false, code: body.preserve?.code !== false, formatting: body.preserve?.formatting !== false }; return { text, mode, strength, language, tone: String(body.tone || mode), audience: String(body.audience || 'General'), preserve }; }
export function buildHumanizerPrompt(request: ReturnType<typeof validateHumanizerRequest>) { return `Rewrite the user text for naturalness, clarity and audience fit. Mode: ${request.mode}. Strength: ${request.strength}. Language: ${request.language}. Tone: ${request.tone}. Audience: ${request.audience}. Preserve controls: ${JSON.stringify(request.preserve)}.\n\n<untrusted_user_text>\n${request.text}\n</untrusted_user_text>`; }
export function validateHumanizerOutput(request: ReturnType<typeof validateHumanizerRequest>, output: string) { if (!output.trim()) throw new OriginalityValidationError('The rewrite provider returned empty output.', 502, 'EMPTY_OUTPUT'); const missingKeywords = request.preserve.keywords.filter((keyword: string) => !output.toLowerCase().includes(keyword.toLowerCase())); const sourceUrls = request.preserve.urls ? request.text.match(/https?:\/\/[^\s)]+/g) || [] : []; const missingUrls = sourceUrls.filter(url => !output.includes(url)); const sourceNumbers = request.preserve.numbers ? request.text.match(/\b\d[\d,.%/-]*\b/g) || [] : []; const missingNumbers = sourceNumbers.filter(number => !output.includes(number)); return { text: output.trim(), warnings: [...(missingKeywords.length ? [`Missing protected keywords: ${missingKeywords.join(', ')}`] : []), ...(missingUrls.length ? ['One or more protected URLs changed or are missing.'] : []), ...(missingNumbers.length ? ['One or more protected numeric values changed or are missing.'] : [])] }; }
export function internalSimilarity(leftValue: unknown, rightValue: unknown) { const left = normalizeText(leftValue); const right = normalizeText(rightValue); const leftWords = new Set(wordsOf(left)); const rightWords = new Set(wordsOf(right)); const intersection = [...leftWords].filter(word => rightWords.has(word) && word.length > 3); const union = new Set([...leftWords, ...rightWords]); return { method: 'Jaccard unique-word overlap', estimatedSimilarity: Math.round(intersection.length / Math.max(1, union.size) * 100), sharedTerms: intersection.slice(0, 30), externalSources: [], limitations: ['This compares only the two texts provided. It is not an internet plagiarism scan and does not prove copying.'] }; }
