import React, { useEffect, useState } from 'react';
import { ArrowRight, KeyRound, Mail, Moon, Sun, UserRound } from 'lucide-react';

type Mode = 'login' | 'register' | 'forgot' | 'reset' | 'verify';
interface Props { onLoginSuccess: (user: any) => void; theme: 'light' | 'dark'; onToggleTheme: () => void; initialAuthMode?: 'view' | 'login' | 'register' }

export default function LandingPage({ onLoginSuccess, theme, onToggleTheme, initialAuthMode }: Props) {
  const query = new URLSearchParams(typeof window === 'undefined' ? '' : window.location.search); const requested = query.get('auth');
  const [mode, setMode] = useState<Mode>(requested === 'reset' || requested === 'verify' ? requested : initialAuthMode === 'register' ? 'register' : 'login');
  const [form, setForm] = useState({ name: '', email: '', password: '', confirm: '' }); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  const update = (key: string, value: string) => { setForm(current => ({ ...current, [key]: value })); setError(''); setMessage(''); };
  const request = async (url: string, body: any) => { const response = await fetch(url, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'The request could not be completed.'); return result; };
  useEffect(() => { if (mode !== 'verify') return; setLoading(true); request('/api/auth/email-verification/confirm', { token: query.get('token') }).then(() => { window.history.replaceState({}, '', '/'); setMessage('Email verified. You can now log in.'); }).catch(reason => setError(reason.message)).finally(() => setLoading(false)); }, [mode]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setMessage(''); if (mode === 'register' && !form.name.trim()) return setError('Please enter your name.'); if (mode !== 'reset' && !form.email.trim()) return setError('Please enter your email address.'); if (mode !== 'forgot' && form.password.length < 10) return setError('Password must contain at least 10 characters.'); if (mode === 'reset' && form.password !== form.confirm) return setError('Passwords do not match.'); setLoading(true); try { if (mode === 'login' || mode === 'register') { const result = await request(`/api/auth/${mode}`, form); onLoginSuccess(result.user); } else if (mode === 'forgot') { const result = await request('/api/auth/forgot-password', { email: form.email }); setMessage(result.message); } else if (mode === 'reset') { await request('/api/auth/reset-password', { token: query.get('token'), password: form.password }); window.history.replaceState({}, '', '/'); setMode('login'); setForm(current => ({ ...current, password: '', confirm: '' })); setMessage('Password reset. You can now log in.'); } } catch (reason: any) { setError(reason.message || 'The request could not be completed.'); } finally { setLoading(false); } };
  const title = mode === 'login' ? 'Welcome back' : mode === 'register' ? 'Create your account' : mode === 'forgot' ? 'Forgot password' : mode === 'reset' ? 'Choose a new password' : 'Verify your email';
  const description = mode === 'login' ? 'Sign in to open your saved workspace.' : mode === 'register' ? 'Create a personal workspace and start on the Free plan.' : mode === 'forgot' ? 'If this email has an account, we will send a secure reset link.' : mode === 'reset' ? 'Use at least 10 characters for your new password.' : 'Checking your secure verification link.';
  return <div className={`min-h-screen ${theme === 'dark' ? 'dark bg-zinc-950 text-white' : 'bg-slate-50 text-slate-900'}`}><header className="flex h-16 items-center justify-between border-b border-slate-200 bg-white px-5 dark:border-zinc-800 dark:bg-zinc-900 sm:px-10"><button onClick={() => onLoginSuccess({ id: 'guest', guest: true })} className="flex items-center gap-3"><span className="theme-brand-mark flex h-9 w-9 items-center justify-center rounded-xl text-xs font-black">GX</span><span className="text-sm font-black">GXA AI Workspace</span></button><div className="flex items-center gap-2"><button onClick={onToggleTheme} className="rounded-xl p-2" aria-label="Toggle theme">{theme === 'light' ? <Moon className="h-4 w-4" /> : <Sun className="h-4 w-4" />}</button><button onClick={() => onLoginSuccess({ id: 'guest', guest: true })} className="text-xs font-bold text-slate-500">Guest workspace</button></div></header><main className="flex min-h-[calc(100vh-4rem)] items-center justify-center p-5"><section className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-7 shadow-xl dark:border-zinc-800 dark:bg-zinc-900"><p className="text-xs font-bold uppercase tracking-widest text-teal-600">Secure account</p><h1 className="mt-2 text-2xl font-black">{title}</h1><p className="mt-2 text-sm text-slate-500 dark:text-zinc-400">{description}</p>{error && <p id="auth-form-error" role="alert" className="mt-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-950/30 dark:text-rose-300">{error}</p>}{message && <p role="status" className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300">{message}</p>}
      {mode !== 'verify' && <form noValidate onSubmit={submit} className="mt-6 space-y-4">{mode === 'register' && <Field label="Full name" icon={UserRound} value={form.name} describedBy={error ? 'auth-form-error' : undefined} onChange={(value: string) => update('name', value)} />}{mode !== 'reset' && <Field label="Email" icon={Mail} type="email" value={form.email} describedBy={error ? 'auth-form-error' : undefined} onChange={(value: string) => update('email', value)} />}{mode !== 'forgot' && <Field label="Password" icon={KeyRound} type="password" value={form.password} describedBy={error ? 'auth-form-error' : undefined} onChange={(value: string) => update('password', value)} />}{mode === 'reset' && <Field label="Confirm password" icon={KeyRound} type="password" value={form.confirm} describedBy={error ? 'auth-form-error' : undefined} onChange={(value: string) => update('confirm', value)} />}<button disabled={loading} className="theme-primary-action flex w-full items-center justify-center gap-2 rounded-xl py-3 text-sm font-black disabled:opacity-50">{loading ? 'Please wait…' : mode === 'login' ? 'Log in' : mode === 'register' ? 'Create account' : mode === 'forgot' ? 'Send reset link' : 'Reset password'}<ArrowRight className="h-4 w-4" /></button></form>}
      {mode === 'login' && <button onClick={() => setMode('forgot')} className="mt-4 w-full text-center text-xs font-bold text-teal-600">Forgot password?</button>}{(mode === 'login' || mode === 'register') && <p className="mt-5 text-center text-xs text-slate-500">{mode === 'login' ? 'New to GXA? ' : 'Already registered? '}<button onClick={() => setMode(mode === 'login' ? 'register' : 'login')} className="font-bold text-teal-600">{mode === 'login' ? 'Create an account' : 'Log in'}</button></p>}{!['login', 'register'].includes(mode) && <button onClick={() => { window.history.replaceState({}, '', '/'); setError(''); setMessage(''); setMode('login'); }} className="mt-5 w-full text-center text-xs font-bold text-teal-600">Back to login</button>}
    </section></main></div>;
}
function Field({ label, icon: Icon, value, onChange, type = 'text', describedBy }: any) { const id = `auth-${label.toLowerCase().replaceAll(' ', '-')}`; return <label htmlFor={id} className="block space-y-1.5 text-xs font-bold"><span>{label}</span><span className="relative block"><Icon className="absolute left-3.5 top-3 h-4 w-4 text-slate-400" /><input id={id} required aria-describedby={describedBy} aria-invalid={Boolean(describedBy)} type={type} value={value} onChange={event => onChange(event.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-500/20 dark:border-zinc-700 dark:bg-zinc-950" /></span></label>; }
