import React, { useEffect, useRef, useState } from 'react';
import { CreditCard, LayoutDashboard, LogOut, Settings, UserRound } from 'lucide-react';
import { WorkspaceId } from '../types';

export default function ProfileMenu({ user, onSelect, onLogout }: { user: any; onSelect: (route: WorkspaceId) => void; onLogout: () => void }) {
  const [open, setOpen] = useState(false); const root = useRef<HTMLDivElement>(null); const trigger = useRef<HTMLButtonElement>(null);
  useEffect(() => { const click = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); }; const key = (event: KeyboardEvent) => { if (event.key === 'Escape' && open) { setOpen(false); trigger.current?.focus(); } }; document.addEventListener('mousedown', click); document.addEventListener('keydown', key); return () => { document.removeEventListener('mousedown', click); document.removeEventListener('keydown', key); }; }, [open]);
  const choose = (route: WorkspaceId) => { setOpen(false); onSelect(route); };
  const initials = String(user?.name || user?.email || '?').split(/\s+/).slice(0, 2).map((part: string) => part[0]).join('').toUpperCase();
  return <div ref={root} className="relative"><button ref={trigger} onClick={() => setOpen(value => !value)} aria-haspopup="menu" aria-expanded={open} aria-controls="profile-menu" className="flex h-9 w-9 items-center justify-center overflow-hidden rounded-full border border-slate-200 bg-slate-100 text-xs font-black text-teal-700 focus:outline-none focus:ring-2 focus:ring-teal-500 dark:border-zinc-700 dark:bg-zinc-800 dark:text-teal-300" aria-label="Open profile menu">{user?.avatar ? <img src={user.avatar} alt="" className="h-full w-full object-cover" /> : initials}</button>{open && <div id="profile-menu" role="menu" className="absolute right-0 z-50 mt-2 w-56 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl dark:border-zinc-700 dark:bg-zinc-900"><div className="border-b border-slate-100 px-3 py-2 dark:border-zinc-800"><p className="truncate text-xs font-black">{user?.name}</p><p className="truncate text-[10px] text-slate-400">{user?.email}</p></div><Item icon={UserRound} label="My Profile" onClick={() => choose('profile')} /><Item icon={LayoutDashboard} label="Workspace" onClick={() => choose('dashboard')} /><Item icon={CreditCard} label="Plan" onClick={() => choose('billing')} /><Item icon={Settings} label="Settings" onClick={() => choose('settings')} /><div className="my-1 border-t border-slate-100 dark:border-zinc-800" /><Item icon={LogOut} label="Logout" danger onClick={() => { setOpen(false); onLogout(); }} /></div>}</div>;
}
function Item({ icon: Icon, label, onClick, danger = false }: any) { return <button role="menuitem" onClick={onClick} className={`mt-1 flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-left text-xs font-bold focus:outline-none focus:ring-2 focus:ring-teal-500 ${danger ? 'text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/30' : 'text-slate-700 hover:bg-slate-50 dark:text-zinc-200 dark:hover:bg-zinc-800'}`}><Icon className="h-4 w-4" />{label}</button>; }
