import React from 'react';
import { BookOpen, ChevronLeft, ChevronRight, FileText, Folder, Home, Languages, Menu, MessageSquare, Moon, PenLine, Plus, Repeat2, Search, Settings, Sun } from 'lucide-react';
import { WorkspaceId } from '../types';

interface Props { activeWorkspace: WorkspaceId; onSelectWorkspace: (id: WorkspaceId) => void; theme: 'light' | 'dark'; onToggleTheme: () => void; collapsed?: boolean; isAuthenticated: boolean; onOpenTools: () => void; onCollapse?: () => void }
const popular: Array<{ route: WorkspaceId; label: string; icon: React.ComponentType<{ className?: string }> }> = [
  { route: 'paraphrasing', label: 'Paraphraser', icon: Repeat2 }, { route: 'grammar', label: 'Grammar Checker', icon: FileText }, { route: 'ai-chat', label: 'AI Chat', icon: MessageSquare }, { route: 'ai-writing', label: 'AI Writer', icon: PenLine }, { route: 'summarizer', label: 'Summarizer', icon: BookOpen }, { route: 'translation', label: 'Translator', icon: Languages }, { route: 'pdf-intelligence', label: 'PDF Tools', icon: FileText },
];

export default function Sidebar({ activeWorkspace, onSelectWorkspace, theme, onToggleTheme, collapsed = false, isAuthenticated, onOpenTools, onCollapse }: Props) {
  const item = (route: WorkspaceId, label: string, Icon: React.ComponentType<{ className?: string }>) => <button key={route} onClick={() => onSelectWorkspace(route)} title={collapsed ? label : undefined} className={`flex w-full items-center rounded-xl py-2.5 text-xs font-bold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-500 ${collapsed ? 'justify-center px-2' : 'gap-3 px-3'} ${activeWorkspace === route ? 'bg-teal-50 text-teal-700 dark:bg-teal-950/50 dark:text-teal-300' : 'text-slate-600 hover:bg-slate-100 dark:text-zinc-400 dark:hover:bg-zinc-900'}`}><Icon className="h-4 w-4 shrink-0" />{!collapsed && <span>{label}</span>}</button>;
  return <aside className={`${collapsed ? 'w-20' : 'w-64'} flex h-full shrink-0 flex-col border-r border-slate-200 bg-white transition-[width] dark:border-zinc-800 dark:bg-zinc-950`}>
    <div className={`flex h-16 items-center border-b border-slate-200 px-4 dark:border-zinc-800 ${collapsed ? 'justify-center' : 'gap-3'}`}><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-teal-500 text-xs font-black text-white">GX</span>{!collapsed && <div><strong className="block text-sm text-slate-950 dark:text-white">GXA AI Workspace</strong><span className="text-[10px] font-bold uppercase tracking-widest text-slate-400">GXA Technologies</span></div>}</div>
    <nav aria-label="Primary navigation" className="flex-1 overflow-y-auto p-3"><div className="space-y-1">{item('home', 'Home', Home)}<button onClick={() => { onSelectWorkspace('home'); }} className={`flex w-full items-center rounded-xl py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-100 dark:text-zinc-400 dark:hover:bg-zinc-900 ${collapsed ? 'justify-center px-2' : 'gap-3 px-3'}`} title={collapsed ? 'New' : undefined}><Plus className="h-4 w-4" />{!collapsed && 'New'}</button>{isAuthenticated && item('projects', 'Projects', Folder)}</div>
      <div className="my-4 border-t border-slate-200 dark:border-zinc-800" />{!collapsed && <p className="mb-2 px-3 text-[10px] font-black uppercase tracking-widest text-slate-400">Popular tools</p>}<div className="space-y-1">{popular.map(tool => item(tool.route, tool.label, tool.icon))}</div>
      <div className="my-4 border-t border-slate-200 dark:border-zinc-800" /><div className="space-y-1"><button onClick={onOpenTools} className={`flex w-full items-center rounded-xl py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-100 dark:text-zinc-400 dark:hover:bg-zinc-900 ${collapsed ? 'justify-center px-2' : 'gap-3 px-3'}`} title={collapsed ? 'More Tools' : undefined}><Menu className="h-4 w-4" />{!collapsed && 'More Tools'}</button><button onClick={onOpenTools} className={`flex w-full items-center rounded-xl py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-100 dark:text-zinc-400 dark:hover:bg-zinc-900 ${collapsed ? 'justify-center px-2' : 'gap-3 px-3'}`} title={collapsed ? 'Search' : undefined}><Search className="h-4 w-4" />{!collapsed && 'Search'}</button></div>
      {isAuthenticated && <><div className="my-4 border-t border-slate-200 dark:border-zinc-800" />{!collapsed && <p className="mb-2 px-3 text-[10px] font-black uppercase tracking-widest text-slate-400">Your workspace</p>}<div className="space-y-1">{item('documents', 'Documents', FileText)}{item('history', 'History', BookOpen)}{item('favorites', 'Favorites', BookOpen)}{item('shared', 'Shared with Me', Folder)}</div></>}
    </nav>
    <div className="space-y-1 border-t border-slate-200 p-3 dark:border-zinc-800">{isAuthenticated && item('settings', 'Settings', Settings)}<button onClick={onToggleTheme} className={`flex w-full items-center rounded-xl py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-100 dark:text-zinc-400 dark:hover:bg-zinc-900 ${collapsed ? 'justify-center px-2' : 'gap-3 px-3'}`}>{theme === 'light' ? <Moon className="h-4 w-4" /> : <Sun className="h-4 w-4" />}{!collapsed && (theme === 'light' ? 'Dark theme' : 'Light theme')}</button>{onCollapse && <button onClick={onCollapse} className={`hidden w-full items-center rounded-xl py-2.5 text-xs font-bold text-slate-500 hover:bg-slate-100 md:flex dark:hover:bg-zinc-900 ${collapsed ? 'justify-center px-2' : 'gap-3 px-3'}`}>{collapsed ? <ChevronRight className="h-4 w-4" /> : <><ChevronLeft className="h-4 w-4" /> Collapse</>}</button>}</div>
  </aside>;
}
