import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Search, X, LockKeyhole, ArrowUpRight } from 'lucide-react';
import { registryCategories, ToolDefinition, toolRegistry } from '../toolRegistry';
import { WorkspaceId } from '../types';

interface Props { open: boolean; onClose: () => void; onSelect: (route: WorkspaceId) => void; isAuthenticated: boolean }

export default function ToolExplorer({ open, onClose, onSelect, isAuthenticated }: Props) {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All');
  const searchRef = useRef<HTMLInputElement>(null);
  const panelRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!open) return; searchRef.current?.focus(); const handleKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key !== 'Tab' || !panelRef.current) return; const focusable = Array.from(panelRef.current.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled])')); if (!focusable.length) return; const first = focusable[0], last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener('keydown', handleKey); return () => document.removeEventListener('keydown', handleKey); }, [open, onClose]);
  const tools = useMemo(() => toolRegistry.filter(tool => tool.more && (isAuthenticated || tool.guestAccess)).filter(tool => category === 'All' || tool.category === category).filter(tool => { const haystack = `${tool.name} ${tool.description} ${tool.category} ${tool.keywords.join(' ')}`.toLowerCase(); return query.toLowerCase().trim().split(/\s+/).filter(Boolean).every(term => haystack.includes(term)); }), [query, category, isAuthenticated]);
  if (!open) return null;
  const select = (tool: ToolDefinition) => { onSelect(tool.route); onClose(); };
  return <div className="fixed inset-0 z-[80] bg-slate-950/55 backdrop-blur-sm md:p-6" role="dialog" aria-modal="true" aria-labelledby="tool-explorer-title" onMouseDown={event => event.target === event.currentTarget && onClose()}>
    <div ref={panelRef} className="ml-auto flex h-full w-full max-w-3xl flex-col bg-white shadow-2xl dark:bg-zinc-950 md:rounded-3xl md:border md:border-white/10">
      <header className="flex items-start justify-between border-b border-slate-200 p-5 dark:border-zinc-800 sm:p-7"><div><h2 id="tool-explorer-title" className="text-xl font-black text-slate-950 dark:text-white">Explore GXA AI tools</h2><p className="mt-1 text-sm text-slate-500">Search the complete workspace without losing your current input.</p></div><button onClick={onClose} aria-label="Close tool explorer" className="rounded-xl p-2 text-slate-500 hover:bg-slate-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-500 dark:hover:bg-zinc-900"><X className="h-5 w-5" /></button></header>
      <div className="space-y-4 border-b border-slate-200 p-5 dark:border-zinc-800 sm:px-7"><label className="relative block"><Search className="absolute left-4 top-3.5 h-5 w-5 text-slate-400" /><span className="sr-only">Search AI tools</span><input ref={searchRef} value={query} onChange={event => setQuery(event.target.value)} placeholder="Search AI tools..." className="w-full rounded-2xl border border-slate-200 bg-slate-50 py-3 pl-12 pr-4 text-sm outline-none focus:border-teal-500 focus:ring-4 focus:ring-teal-500/10 dark:border-zinc-800 dark:bg-zinc-900" /></label><div className="flex gap-2 overflow-x-auto pb-1">{['All', ...registryCategories].map(item => <button key={item} onClick={() => setCategory(item)} className={`shrink-0 rounded-full px-3 py-1.5 text-xs font-bold ${category === item ? 'bg-slate-950 text-white dark:bg-white dark:text-slate-950' : 'bg-slate-100 text-slate-600 dark:bg-zinc-900 dark:text-zinc-300'}`}>{item}</button>)}</div></div>
      <div className="flex-1 overflow-y-auto p-5 sm:p-7"><div className="grid gap-3 sm:grid-cols-2">{tools.map(tool => <button key={tool.id} onClick={() => select(tool)} className="group rounded-2xl border border-slate-200 p-4 text-left transition hover:-translate-y-0.5 hover:border-teal-400 hover:shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-500 dark:border-zinc-800 dark:bg-zinc-900"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="font-black text-slate-900 dark:text-white">{tool.name}</span>{tool.status === 'beta' && <span className="rounded-full bg-violet-100 px-2 py-0.5 text-[10px] font-black text-violet-700">BETA</span>}</div><p className="mt-1 text-xs leading-5 text-slate-500 dark:text-zinc-400">{tool.description}</p></div><ArrowUpRight className="h-4 w-4 shrink-0 text-slate-300 group-hover:text-teal-500" /></div><div className="mt-3 flex items-center justify-between text-[10px] font-bold uppercase tracking-wide text-slate-400"><span>{tool.category}</span><span className="inline-flex items-center gap-1">{tool.planAccess !== 'Free' && <LockKeyhole className="h-3 w-3" />}{tool.planAccess}</span></div></button>)}</div>{tools.length === 0 && <div className="py-16 text-center"><p className="font-bold text-slate-700 dark:text-zinc-200">No matching tools</p><p className="mt-1 text-sm text-slate-500">Try another name, category or keyword.</p></div>}</div>
    </div>
  </div>;
}
