import React, { useEffect, useState } from 'react';
import { KeyRound, Loader2, Save } from 'lucide-react';
import { authenticatedFetch } from '../../utils/auth';

export default function AccountSettings({ currentUser }: { currentUser: any }) {
  const [profile, setProfile] = useState<any>(null); const [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirm: '' }); const [busy, setBusy] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  useEffect(() => { authenticatedFetch(currentUser, '/api/account/profile').then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setProfile(body.user); }).catch(reason => setError(reason.message || 'Settings could not be loaded.')); }, [currentUser?.id]);
  const request = async (url: string, init: RequestInit) => { const response = await authenticatedFetch(currentUser, url, { ...init, headers: { 'Content-Type': 'application/json', ...(init.headers || {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'The change could not be saved.'); return body; };
  const savePreferences = async (event: React.FormEvent) => { event.preventDefault(); setBusy('preferences'); setError(''); try { const body = await request('/api/account/profile', { method: 'PATCH', body: JSON.stringify(profile) }); setProfile(body.user); setNotice('Settings saved.'); } catch (reason: any) { setError(reason.message); } finally { setBusy(''); } };
  const changePassword = async (event: React.FormEvent) => { event.preventDefault(); setError(''); if (password.newPassword !== password.confirm) { setError('New passwords do not match.'); return; } setBusy('password'); try { await request('/api/auth/password', { method: 'POST', body: JSON.stringify(password) }); setPassword({ currentPassword: '', newPassword: '', confirm: '' }); setNotice('Password changed. Other sessions were signed out.'); } catch (reason: any) { setError(reason.message); } finally { setBusy(''); } };
  if (!profile && !error) return <div className="flex min-h-80 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-teal-500" /></div>;
  return <section className="mx-auto max-w-4xl space-y-6"><div><h1 className="text-2xl font-black">Settings</h1><p className="mt-1 text-sm text-slate-500">Manage personal preferences and account security.</p></div>{error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-950/30 dark:text-rose-300">{error}</p>}{notice && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300">{notice}</p>}
    {profile && <form onSubmit={savePreferences} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h2 className="font-black">Preferences</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Timezone" value={profile.timezone} onChange={(value: string) => setProfile({ ...profile, timezone: value })} /><Field label="Language" value={profile.language} onChange={(value: string) => setProfile({ ...profile, language: value })} /></div><button disabled={busy === 'preferences'} className="theme-primary-action mt-4 inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black disabled:opacity-50">{busy === 'preferences' ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Save settings</button></form>}
    <form onSubmit={changePassword} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h2 className="flex items-center gap-2 font-black"><KeyRound className="h-4 w-4 text-teal-500" />Change password</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><Field label="Current password" type="password" value={password.currentPassword} onChange={(value: string) => setPassword({ ...password, currentPassword: value })} /><Field label="New password" type="password" value={password.newPassword} onChange={(value: string) => setPassword({ ...password, newPassword: value })} /><Field label="Confirm new password" type="password" value={password.confirm} onChange={(value: string) => setPassword({ ...password, confirm: value })} /></div><p className="mt-2 text-xs text-slate-400">Use at least 10 characters. Changing it signs out your other sessions.</p><button disabled={busy === 'password' || !password.currentPassword || password.newPassword.length < 10 || !password.confirm} className="theme-primary-action mt-4 inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black disabled:opacity-50">{busy === 'password' && <Loader2 className="h-4 w-4 animate-spin" />}Change password</button></form>
  </section>;
}
function Field({ label, value, onChange, type = 'text' }: any) { const id = `setting-${label.toLowerCase().replaceAll(' ', '-')}`; return <label htmlFor={id} className="space-y-1.5 text-xs font-bold"><span>{label}</span><input id={id} type={type} required value={value || ''} onChange={event => onChange(event.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-normal outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-500/20 dark:border-zinc-700 dark:bg-zinc-950" /></label>; }
