import React, { useEffect, useMemo, useState } from 'react';
import { BarChart3, BookOpen, Check, Copy, Download, FileSearch, History, Loader2, Save, ShieldAlert, Sparkles, X } from 'lucide-react';
import { fetchSystemConfig, fetchUsage, isUserPremium, SystemConfig, UsageStats } from '../../utils/limits';

type Tab = 'detector' | 'humanizer' | 'plagiarism' | 'citation' | 'insights';
type Mode = 'Standard' | 'Academic' | 'Professional' | 'Business' | 'Creative' | 'Simple';
type Style = 'APA' | 'MLA' | 'Chicago' | 'Harvard' | 'IEEE';
type Report = { id: string; type: string; input: string; output: any; createdAt: string };
interface Props { currentUser?: any; onOpenUpgradeModal?: () => void; initialTab?: Tab }
const tabs: Array<{ id: Tab; label: string }> = [{ id: 'detector', label: 'AI Detector' }, { id: 'humanizer', label: 'AI Humanizer' }, { id: 'plagiarism', label: 'Plagiarism Checker' }, { id: 'citation', label: 'Citation Generator' }, { id: 'insights', label: 'Writing Insights' }];
const modes: Mode[] = ['Standard', 'Academic', 'Professional', 'Business', 'Creative', 'Simple'];

function citation(style: Style, source: Record<string, string>) {
  const author = source.author.trim(), title = source.title.trim(), year = source.year.trim() || 'n.d.', publisher = source.publisher.trim(), url = source.url.trim(), accessed = source.accessed.trim();
  if (!author || !title) return '';
  if (style === 'APA') return `${author}. (${year}). ${title}.${publisher ? ` ${publisher}.` : ''}${url ? ` ${url}` : ''}`;
  if (style === 'MLA') return `${author}. “${title}.”${publisher ? ` ${publisher},` : ''} ${year}.${url ? ` ${url}.` : ''}`;
  if (style === 'Chicago') return `${author}. “${title}.”${publisher ? ` ${publisher}.` : ''} ${year}.${url ? ` ${url}` : ''}${accessed ? ` Accessed ${accessed}.` : ''}`;
  if (style === 'Harvard') return `${author} (${year}) ‘${title}’.${publisher ? ` ${publisher}.` : ''}${url ? ` Available at: ${url}${accessed ? ` (Accessed: ${accessed})` : ''}.` : ''}`;
  return `${author}, “${title},”${publisher ? ` ${publisher},` : ''} ${year}.${url ? ` [Online]. Available: ${url}${accessed ? `. [Accessed: ${accessed}]` : ''}` : ''}`;
}

export default function OriginalityCenter({ currentUser, onOpenUpgradeModal, initialTab = 'detector' }: Props) {
  const [tab, setTab] = useState<Tab>(initialTab), [text, setText] = useState(''), [output, setOutput] = useState<any>(null);
  const [mode, setMode] = useState<Mode>('Standard'), [style, setStyle] = useState<Style>('APA');
  const [source, setSource] = useState({ author: '', title: '', year: '', publisher: '', url: '', accessed: '' });
  const [config, setConfig] = useState<SystemConfig | null>(null), [usage, setUsage] = useState<UsageStats | null>(null);
  const [loading, setLoading] = useState(false), [error, setError] = useState(''), [unavailable, setUnavailable] = useState('');
  const [copied, setCopied] = useState(false), [compare, setCompare] = useState(false), [reports, setReports] = useState<Report[]>([]), [showHistory, setShowHistory] = useState(false);
  const userId = currentUser?.email || currentUser?.id || '', premium = isUserPremium(currentUser);
  const wordCount = text.trim() ? text.trim().split(/\s+/).length : 0, charCount = text.length, wordLimit = config?.originality_word_limit || 1500;
  const dailyLimit = config?.originality_daily_limit || 5, used = usage?.originality_checks || 0, exceeded = wordCount > wordLimit || (!premium && used >= dailyLimit);
  const paidFeatures = config?.originality_paid_features || ['humanizer_advanced', 'plagiarism', 'insights'];
  const locked = (target = tab) => !premium && ((target === 'humanizer' && mode !== 'Standard' && paidFeatures.includes('humanizer_advanced')) || (target === 'plagiarism' && paidFeatures.includes('plagiarism')) || (target === 'insights' && paidFeatures.includes('insights')));

  useEffect(() => { setTab(initialTab); }, [initialTab]);
  useEffect(() => { Promise.all([fetchSystemConfig(), fetchUsage(userId || 'guest')]).then(([c, u]) => { setConfig(c); setUsage(u); }); if (userId) fetch('/api/originality/reports', { headers: { Authorization: `Bearer ${userId}` } }).then(r => r.ok ? r.json() : { reports: [] }).then(data => setReports(data.reports || [])); else setReports([]); }, [userId]);
  useEffect(() => { setOutput(null); setError(''); setUnavailable(''); setCompare(false); }, [tab]);
  const citationOutput = useMemo(() => citation(style, source), [style, source]);
  const selectTab = (next: Tab) => { setTab(next); setShowHistory(false); };
  const run = async () => {
    if (tab === 'citation') { if (!citationOutput) setError('Author and title are required to create a citation.'); else { setOutput({ text: citationOutput }); setError(''); } return; }
    if (!text.trim() || loading) return; if (wordCount > wordLimit) return setError(`Reduce the text to ${wordLimit} words or fewer.`);
    if (locked()) { onOpenUpgradeModal?.(); return; } if (!premium && used >= dailyLimit) { onOpenUpgradeModal?.(); return setError('Your daily originality limit has been reached.'); }
    setLoading(true); setError(''); setUnavailable('');
    try { const response = await fetch('/api/originality/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json', ...(userId ? { Authorization: `Bearer ${userId}` } : {}) }, body: JSON.stringify({ action: tab === 'detector' ? 'detect' : tab, text, mode }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { if (data.code === 'premium_required' || data.code === 'usage_limit') onOpenUpgradeModal?.(); if (data.code === 'service_unavailable') setUnavailable(data.error); else throw new Error(data.error || 'The service could not complete this request.'); return; } setOutput(data.result); setUsage(data.usage); }
    catch (cause: any) { setError(cause?.message || 'The analysis service is unavailable. Your text was preserved.'); } finally { setLoading(false); }
  };
  const outputText = () => output?.text || (tab === 'detector' && output ? `Estimated AI-pattern probability: ${output.probability}% (${output.confidence} confidence)\n\nIndicators:\n${output.indicators?.map((v: string) => `• ${v}`).join('\n') || 'None reported'}\n\nLimitation: ${output.limitations}` : tab === 'plagiarism' && output ? `${output.note}\n${output.matches?.map((m: any) => `${m.similarity}% — ${m.title}\n${m.url}\n${m.excerpt}`).join('\n\n') || ''}` : tab === 'insights' && output ? `Readability: ${output.readability}\nTone: ${output.tone}\nClarity: ${output.clarity}/100\nSentence variety: ${output.sentenceVariety}/100\n\n${output.observations?.map((v: string) => `• ${v}`).join('\n') || ''}` : '');
  const copy = async () => { await navigator.clipboard.writeText(outputText()); setCopied(true); setTimeout(() => setCopied(false), 1500); };
  const exportResult = () => { const blob = new Blob([outputText()], { type: 'text/plain' }); const url = URL.createObjectURL(blob), link = document.createElement('a'); link.href = url; link.download = `originality-${tab}.txt`; link.click(); URL.revokeObjectURL(url); };
  const save = async () => { if (!userId) return setError('Sign in to save reports and view history.'); const response = await fetch('/api/originality/reports', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${userId}` }, body: JSON.stringify({ type: tab, input: tab === 'citation' ? JSON.stringify(source) : text, output }) }); if (response.ok) { const data = await response.json(); setReports(list => [data.report, ...list]); } else setError('The report could not be saved.'); };

  return <div className="flex h-full min-h-0 flex-col bg-slate-50 text-slate-900 dark:bg-zinc-950 dark:text-zinc-100">
    <header className="border-b bg-white px-4 py-3 dark:border-zinc-800 dark:bg-zinc-900"><div className="flex items-center justify-between"><div><h1 className="font-semibold">Originality Center</h1><p className="text-xs text-slate-500">Analyze, revise and reference writing without fabricated evidence.</p></div><button onClick={() => { if (!userId) setError('Sign in to view saved reports.'); else setShowHistory(!showHistory); }} className="flex items-center gap-1 rounded-lg border px-3 py-2 text-xs dark:border-zinc-700"><History className="h-3.5 w-3.5" /> Saved</button></div><nav className="mt-3 flex gap-1 overflow-x-auto">{tabs.map(item => <button key={item.id} onClick={() => selectTab(item.id)} className={`shrink-0 rounded-lg px-3 py-2 text-xs font-semibold ${tab === item.id ? 'bg-teal-600 text-white' : 'bg-slate-100 text-slate-600 dark:bg-zinc-800 dark:text-zinc-300'}`}>{item.label}</button>)}</nav></header>
    {showHistory ? <div className="flex-1 overflow-y-auto p-4"><div className="mx-auto max-w-3xl"><h2 className="mb-3 font-semibold">Saved reports</h2>{!reports.length && <p className="rounded-xl border border-dashed p-8 text-center text-sm text-slate-500 dark:border-zinc-700">No saved reports.</p>}{reports.map(report => <button key={report.id} onClick={() => { setTab(report.type as Tab); setText(report.input); setOutput(report.output); setShowHistory(false); }} className="mb-2 block w-full rounded-xl border bg-white p-3 text-left dark:border-zinc-700 dark:bg-zinc-900"><span className="text-xs font-semibold capitalize">{report.type}</span><span className="ml-2 text-[10px] text-slate-400">{new Date(report.createdAt).toLocaleString()}</span><p className="mt-1 truncate text-xs text-slate-500">{report.input}</p></button>)}</div></div> : <div className="grid min-h-0 flex-1 gap-4 overflow-y-auto p-4 lg:grid-cols-2">
      <section className="flex min-h-[420px] flex-col rounded-2xl border bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900">{tab === 'citation' ? <><div className="mb-3 flex gap-2 overflow-x-auto">{(['APA', 'MLA', 'Chicago', 'Harvard', 'IEEE'] as Style[]).map(item => <button key={item} onClick={() => setStyle(item)} className={`rounded-lg px-3 py-2 text-xs ${style === item ? 'bg-teal-600 text-white' : 'bg-slate-100 dark:bg-zinc-800'}`}>{item}</button>)}</div><div className="grid gap-3 sm:grid-cols-2">{Object.entries(source).map(([key, value]) => <label key={key} className="text-xs capitalize">{key}<input type={key === 'accessed' ? 'date' : 'text'} value={value} onChange={e => setSource(current => ({ ...current, [key]: e.target.value }))} className="mt-1 w-full rounded-lg border p-2.5 dark:border-zinc-700 dark:bg-zinc-950" /></label>)}</div></> : <><div className="mb-2 flex items-center justify-between"><span className="text-xs font-semibold">Source text</span><span className={`text-[11px] ${wordCount > wordLimit ? 'text-red-500' : wordCount > wordLimit * .85 ? 'text-amber-500' : 'text-slate-400'}`}>{wordCount}/{wordLimit} words · {charCount} characters</span></div>{tab === 'humanizer' && <div className="mb-3 flex gap-1 overflow-x-auto">{modes.map(item => <button key={item} onClick={() => { setMode(item); if (!premium && item !== 'Standard' && paidFeatures.includes('humanizer_advanced')) onOpenUpgradeModal?.(); }} className={`shrink-0 rounded-lg px-2.5 py-1.5 text-xs ${mode === item ? 'bg-teal-600 text-white' : 'bg-slate-100 dark:bg-zinc-800'}`}>{item}{!premium && item !== 'Standard' && paidFeatures.includes('humanizer_advanced') ? ' 🔒' : ''}</button>)}</div>}<textarea value={text} onChange={e => setText(e.target.value)} placeholder={tab === 'plagiarism' ? 'Paste text to check against the configured source provider…' : 'Paste or type text here…'} className="min-h-72 flex-1 resize-none rounded-xl border bg-slate-50 p-4 text-sm leading-6 outline-none focus:border-teal-500 dark:border-zinc-700 dark:bg-zinc-950" /></>}<div className="mt-3 flex items-center justify-between"><span className="text-[11px] text-slate-400">{premium ? 'Plan access enabled' : `${Math.max(0, dailyLimit - used)} free analyses remaining today`}</span><button onClick={run} disabled={loading || (tab !== 'citation' && (!text.trim() || wordCount > wordLimit))} className="flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-40">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : tab === 'detector' ? <ShieldAlert className="h-4 w-4" /> : tab === 'humanizer' ? <Sparkles className="h-4 w-4" /> : tab === 'citation' ? <BookOpen className="h-4 w-4" /> : tab === 'plagiarism' ? <FileSearch className="h-4 w-4" /> : <BarChart3 className="h-4 w-4" />}{loading ? 'Working…' : tab === 'citation' ? 'Generate citation' : 'Run analysis'}</button></div></section>
      <section className="flex min-h-[420px] flex-col rounded-2xl border bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold">Result</h2>{output && <div className="flex gap-1"><button onClick={copy} title="Copy" className="p-2">{copied ? <Check className="h-4 w-4 text-emerald-500" /> : <Copy className="h-4 w-4" />}</button><button onClick={save} title="Save" className="p-2"><Save className="h-4 w-4" /></button><button onClick={exportResult} title="Export" className="p-2"><Download className="h-4 w-4" /></button>{tab === 'humanizer' && <button onClick={() => setCompare(!compare)} className="rounded px-2 text-xs">Compare</button>}</div>}</div>{error && <div className="mb-3 flex justify-between rounded-lg bg-red-50 p-3 text-xs text-red-700 dark:bg-red-950/30 dark:text-red-300"><span>{error}</span><button onClick={() => setError('')}><X className="h-4 w-4" /></button></div>}{unavailable && <div className="mb-3 rounded-lg bg-amber-50 p-3 text-xs text-amber-800 dark:bg-amber-950/30 dark:text-amber-300"><strong>Service unavailable.</strong> {unavailable}</div>}{!output && !error && !unavailable && <div className="flex flex-1 items-center justify-center text-center text-sm text-slate-400">No report or score is preloaded. Run a real analysis to see results.</div>}{output && (compare && tab === 'humanizer' ? <div className="grid flex-1 gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-3 dark:bg-zinc-950"><span className="text-[10px] font-semibold uppercase text-slate-400">Original</span><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{text}</p></div><div className="rounded-xl bg-teal-50 p-3 dark:bg-teal-950/20"><span className="text-[10px] font-semibold uppercase text-teal-600">Rewritten</span><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{output.text}</p></div></div> : <div className="flex-1 overflow-y-auto rounded-xl bg-slate-50 p-4 dark:bg-zinc-950"><pre className="whitespace-pre-wrap font-sans text-sm leading-6">{outputText()}</pre>{tab === 'detector' && <p className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200">AI detection is probabilistic. This result is not proof of authorship and should not be used as the sole basis for academic, employment, or disciplinary decisions.</p>}</div>)}</section>
    </div>}
  </div>;
}
