import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Check, ChevronDown, Copy, Download, History, Loader2, Menu, PanelRight, Save, Search, Sparkles, Square, X } from 'lucide-react';
import { fetchSystemConfig, fetchUsage, isUserPremium, SystemConfig, UsageStats } from '../../utils/limits';

type Category = 'General Writing' | 'Academic' | 'Business' | 'Marketing' | 'Career' | 'Social Media' | 'Creative' | 'Productivity';
type Action = 'generate' | 'continue' | 'rewrite' | 'improve' | 'expand' | 'shorten' | 'translate';
type Template = { id: string; name: string; category: Category; description: string };
type Version = { id: string; title: string; content: string; createdAt: string };
type WriterDocument = { id: string; title: string; content: string; templateId: string; versions: Version[]; updatedAt: string };
interface Props { currentUser?: any; onOpenUpgradeModal?: () => void }

const categories: Category[] = ['General Writing', 'Academic', 'Business', 'Marketing', 'Career', 'Social Media', 'Creative', 'Productivity'];
const templates: Template[] = [
  { id: 'blog', name: 'Blog', category: 'General Writing', description: 'Structured blog drafts and outlines' }, { id: 'article', name: 'Article', category: 'General Writing', description: 'Clear long-form articles' }, { id: 'email', name: 'Email', category: 'General Writing', description: 'Purposeful email drafts' }, { id: 'essay', name: 'Essay', category: 'Academic', description: 'Organized essay drafts' }, { id: 'story', name: 'Story', category: 'Creative', description: 'Fiction and narrative writing' },
  { id: 'research-paper', name: 'Research Paper', category: 'Academic', description: 'Research structure with placeholders for evidence' }, { id: 'abstract', name: 'Abstract', category: 'Academic', description: 'Concise academic abstracts' }, { id: 'literature-review', name: 'Literature Review', category: 'Academic', description: 'Evidence-led review structures' },
  { id: 'resume', name: 'Resume', category: 'Career', description: 'Focused resume content' }, { id: 'cover-letter', name: 'Cover Letter', category: 'Career', description: 'Role-specific cover letters' }, { id: 'sop', name: 'SOP', category: 'Career', description: 'Statements of purpose' }, { id: 'lor', name: 'LOR', category: 'Career', description: 'Recommendation letter drafts with placeholders' },
  { id: 'business-proposal', name: 'Business Proposal', category: 'Business', description: 'Client-ready proposal structures' }, { id: 'meeting-notes', name: 'Meeting Notes', category: 'Productivity', description: 'Decisions and action items' }, { id: 'product-description', name: 'Product Description', category: 'Marketing', description: 'Accurate product copy' }, { id: 'landing-page', name: 'Landing Page Copy', category: 'Marketing', description: 'Headlines, benefits and calls to action' },
  { id: 'linkedin', name: 'LinkedIn', category: 'Social Media', description: 'Professional social posts' }, { id: 'instagram', name: 'Instagram', category: 'Social Media', description: 'Captions and post copy' }, { id: 'facebook', name: 'Facebook', category: 'Social Media', description: 'Community-focused posts' }, { id: 'x', name: 'X', category: 'Social Media', description: 'Concise posts and threads' }, { id: 'youtube-script', name: 'YouTube Script', category: 'Creative', description: 'Video narration and scene structure' }, { id: 'newsletter', name: 'Newsletter', category: 'Marketing', description: 'Readable newsletter editions' }
];
const newId = () => `writer-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;

export default function AIWriterStudio({ currentUser, onOpenUpgradeModal }: Props) {
  const [config, setConfig] = useState<SystemConfig | null>(null), [usage, setUsage] = useState<UsageStats | null>(null);
  const [category, setCategory] = useState<Category>('General Writing'), [query, setQuery] = useState(''), [templateId, setTemplateId] = useState('blog');
  const [docId, setDocId] = useState(newId), [title, setTitle] = useState(''), [content, setContent] = useState(''), [instructions, setInstructions] = useState('');
  const [versions, setVersions] = useState<Version[]>([]), [showVersions, setShowVersions] = useState(false), [showLibrary, setShowLibrary] = useState(false), [showOptions, setShowOptions] = useState(false);
  const [purpose, setPurpose] = useState('Inform'), [audience, setAudience] = useState('General'), [tone, setTone] = useState('Professional'), [language, setLanguage] = useState('English'), [length, setLength] = useState('Medium'), [keywords, setKeywords] = useState(''), [readingLevel, setReadingLevel] = useState('General');
  const [selection, setSelection] = useState({ start: 0, end: 0 }), [loading, setLoading] = useState(false), [error, setError] = useState(''), [saved, setSaved] = useState(''), [copied, setCopied] = useState(false);
  const abortRef = useRef<AbortController | null>(null), editorRef = useRef<HTMLTextAreaElement>(null);
  const userId = currentUser?.email || currentUser?.id || '', paid = isUserPremium(currentUser);
  const activeTemplate = templates.find(item => item.id === templateId) || templates[0];
  const premiumTemplates = config?.writer_premium_templates || [], templateLocked = !paid && premiumTemplates.includes(templateId);
  const wordLimit = config?.writer_word_limit || 2000, wordCount = content.trim() ? content.trim().split(/\s+/).length : 0, dailyLimit = config?.writer_daily_limit || 5, used = usage?.writer_generations || 0;
  const selectedText = content.slice(selection.start, selection.end), versionEligible = paid && Boolean(userId);
  const exportFormats = paid ? config?.writer_paid_exports || ['txt', 'md', 'html'] : config?.writer_free_exports || ['txt'];
  const filtered = useMemo(() => templates.filter(item => (category === item.category) && `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase())), [category, query]);

  useEffect(() => { Promise.all([fetchSystemConfig(), fetchUsage(userId || 'guest')]).then(([c, u]) => { setConfig(c); setUsage(u); }); if (userId) fetch('/api/writer/documents', { headers: { Authorization: `Bearer ${userId}` } }).then(r => r.ok ? r.json() : { documents: [] }).then(data => { const doc: WriterDocument | undefined = data.documents?.[0]; if (doc) { setDocId(doc.id); setTitle(doc.title); setContent(doc.content); setTemplateId(doc.templateId); setVersions(doc.versions || []); } }); }, [userId]);
  useEffect(() => { if (!userId || loading || (!title.trim() && !content.trim())) return; const timer = setTimeout(async () => { const response = await fetch(`/api/writer/documents/${docId}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${userId}` }, body: JSON.stringify({ title: title || 'Untitled', content, templateId }) }); if (response.ok) setSaved(new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })); }, 800); return () => clearTimeout(timer); }, [title, content, templateId, docId, userId, loading]);

  const chooseTemplate = (item: Template) => { if (!paid && premiumTemplates.includes(item.id)) { onOpenUpgradeModal?.(); return; } setTemplateId(item.id); setCategory(item.category); setShowLibrary(false); if (!title) setTitle(item.name); };
  const generate = async (action: Action, forcedSelection?: string) => {
    const selectionText = forcedSelection ?? selectedText;
    if (loading) return; if (templateLocked) { onOpenUpgradeModal?.(); return; } if (!paid && used >= dailyLimit) { setError('Your daily writer limit has been reached.'); onOpenUpgradeModal?.(); return; }
    const source = action === 'generate' ? instructions : selectionText || content; if (!source.trim()) return setError(action === 'generate' ? 'Describe what you want to write.' : 'Add editor text first.');
    if (source.trim().split(/\s+/).length > wordLimit) return setError(`The selected source exceeds the ${wordLimit}-word limit.`);
    const controller = new AbortController(); abortRef.current = controller; setLoading(true); setError('');
    const start = selectionText ? selection.start : action === 'continue' ? content.length : 0, end = selectionText ? selection.end : action === 'continue' ? content.length : content.length;
    const before = action === 'generate' ? '' : content.slice(0, start), after = action === 'generate' ? '' : content.slice(end); let streamed = '';
    try { const response = await fetch('/api/writer/stream', { method: 'POST', signal: controller.signal, headers: { 'Content-Type': 'application/json', ...(userId ? { Authorization: `Bearer ${userId}` } : {}) }, body: JSON.stringify({ action, prompt: instructions, content, selectedText: selectionText, templateId, templateName: activeTemplate.name, options: { purpose, audience, tone, language, length, keywords, readingLevel } }) });
      if (!response.ok) { const data = await response.json().catch(() => ({})); if ([403, 429].includes(response.status)) onOpenUpgradeModal?.(); throw new Error(data.error || 'Generation failed.'); } if (!response.body) throw new Error('Streaming is unavailable in this browser.');
      const reader = response.body.getReader(), decoder = new TextDecoder(); let buffer = '', complete = false;
      while (true) { const { done, value } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const events = buffer.split('\n\n'); buffer = events.pop() || ''; for (const event of events) if (event.startsWith('data: ')) { const data = JSON.parse(event.slice(6)); if (data.type === 'delta') { streamed += data.text; setContent(`${before}${streamed}${after}`); } if (data.type === 'done') complete = true; if (data.type === 'error') throw new Error(data.message); } }
      if (complete) { setUsage(current => current ? { ...current, writer_generations: (current.writer_generations || 0) + 1 } : current); if (userId) { const savedResponse = await fetch(`/api/writer/documents/${docId}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${userId}` }, body: JSON.stringify({ title: title || activeTemplate.name, content: `${before}${streamed}${after}`, templateId, createVersion: versionEligible }) }); if (savedResponse.ok) { const data = await savedResponse.json(); setVersions(data.document.versions || []); } } }
    } catch (cause: any) { if (!controller.signal.aborted) setError(cause?.message || 'The writing provider is unavailable. Your draft was preserved.'); } finally { setLoading(false); abortRef.current = null; }
  };
  const copy = async () => { await navigator.clipboard.writeText(content); setCopied(true); setTimeout(() => setCopied(false), 1500); };
  const exportDoc = (format: string) => { if (!exportFormats.includes(format)) { onOpenUpgradeModal?.(); return; } const body = format === 'html' ? `<article><h1>${title.replace(/[<>&]/g, '')}</h1><pre>${content.replace(/&/g, '&amp;').replace(/</g, '&lt;')}</pre></article>` : content; const blob = new Blob([body], { type: format === 'html' ? 'text/html' : 'text/plain' }), url = URL.createObjectURL(blob), link = document.createElement('a'); link.href = url; link.download = `${title || 'draft'}.${format}`; link.click(); URL.revokeObjectURL(url); };

  return <div className="flex h-full min-h-0 bg-slate-50 text-slate-900 dark:bg-zinc-950 dark:text-zinc-100">
    {showLibrary && <button className="fixed inset-0 z-20 bg-black/30 lg:hidden" aria-label="Close template library" onClick={() => setShowLibrary(false)} />}
    <aside className={`${showLibrary ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-30 flex w-72 flex-col border-r bg-white transition-transform lg:static lg:translate-x-0 dark:border-zinc-800 dark:bg-zinc-900`}><div className="flex items-center gap-2 p-3"><Search className="h-4 w-4 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search templates" className="min-w-0 flex-1 bg-transparent text-sm outline-none" /><button className="lg:hidden" onClick={() => setShowLibrary(false)}><X className="h-4 w-4" /></button></div><div className="flex gap-1 overflow-x-auto border-y p-2 dark:border-zinc-800">{categories.map(item => <button key={item} onClick={() => setCategory(item)} className={`shrink-0 rounded-lg px-2 py-1.5 text-[11px] ${category === item ? 'bg-teal-600 text-white' : 'bg-slate-100 dark:bg-zinc-800'}`}>{item}</button>)}</div><div className="flex-1 overflow-y-auto p-2">{filtered.map(item => <button key={item.id} onClick={() => chooseTemplate(item)} className={`mb-1 w-full rounded-xl border p-3 text-left ${templateId === item.id ? 'border-teal-500 bg-teal-50 dark:bg-teal-950/20' : 'border-transparent hover:bg-slate-50 dark:hover:bg-zinc-800'}`}><span className="text-sm font-semibold">{item.name}{!paid && premiumTemplates.includes(item.id) ? ' 🔒' : ''}</span><p className="mt-1 text-xs text-slate-500">{item.description}</p></button>)}</div></aside>
    <main className="flex min-w-0 flex-1 flex-col"><header className="flex min-h-14 items-center gap-2 border-b bg-white px-3 dark:border-zinc-800 dark:bg-zinc-900"><button className="p-2 lg:hidden" onClick={() => setShowLibrary(true)}><Menu className="h-5 w-5" /></button><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Untitled document" className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none" /><span className="hidden text-[11px] text-slate-400 sm:block">{userId ? saved ? `Saved ${saved}` : 'Auto-save on' : 'Guest draft is not saved'}</span><button onClick={() => setShowVersions(!showVersions)} className="p-2" title="Version history"><History className="h-4 w-4" /></button><button onClick={() => setShowOptions(!showOptions)} className="p-2 xl:hidden" title="Writing options"><PanelRight className="h-4 w-4" /></button></header>
      {showVersions && <div className="absolute right-4 top-16 z-20 max-h-80 w-80 overflow-y-auto rounded-xl border bg-white p-3 shadow-xl dark:border-zinc-700 dark:bg-zinc-900"><div className="mb-2 flex justify-between"><span className="text-sm font-semibold">Version history</span><button onClick={() => setShowVersions(false)}><X className="h-4 w-4" /></button></div>{!versionEligible && <p className="text-xs text-slate-500">Version history requires an eligible authenticated plan.</p>}{versionEligible && !versions.length && <p className="text-xs text-slate-500">No previous versions yet.</p>}{versions.map(version => <button key={version.id} onClick={() => { setContent(version.content); setTitle(version.title); setShowVersions(false); }} className="mb-1 block w-full rounded-lg border p-2 text-left text-xs dark:border-zinc-700"><strong>{version.title}</strong><span className="ml-2 text-slate-400">{new Date(version.createdAt).toLocaleString()}</span></button>)}</div>}
      <div className="flex flex-wrap gap-1 border-b bg-white p-2 dark:border-zinc-800 dark:bg-zinc-900"><span className="mr-2 self-center text-[11px] text-slate-400">Selection actions:</span>{(['rewrite', 'improve', 'expand', 'shorten', 'translate'] as Action[]).map(action => <button key={action} disabled={loading || !selectedText} onClick={() => generate(action)} className="rounded-lg px-2.5 py-1.5 text-xs capitalize hover:bg-slate-100 disabled:opacity-35 dark:hover:bg-zinc-800">{action}</button>)}<button disabled={loading || !content} onClick={() => generate('continue')} className="rounded-lg px-2.5 py-1.5 text-xs hover:bg-slate-100 disabled:opacity-35 dark:hover:bg-zinc-800">Continue</button><div className="ml-auto flex"><button onClick={copy} disabled={!content} className="p-2" title="Copy">{copied ? <Check className="h-4 w-4 text-emerald-500" /> : <Copy className="h-4 w-4" />}</button><div className="group relative"><button className="flex items-center gap-1 p-2 text-xs"><Download className="h-4 w-4" /><ChevronDown className="h-3 w-3" /></button><div className="invisible absolute right-0 top-full z-20 w-28 rounded-lg border bg-white p-1 opacity-0 shadow-lg group-hover:visible group-hover:opacity-100 dark:border-zinc-700 dark:bg-zinc-900">{['txt', 'md', 'html'].map(format => <button key={format} onClick={() => exportDoc(format)} className="block w-full rounded px-2 py-1.5 text-left text-xs uppercase hover:bg-slate-100 dark:hover:bg-zinc-800">{format}{!exportFormats.includes(format) ? ' 🔒' : ''}</button>)}</div></div></div></div>
      {error && <div className="mx-3 mt-2 flex justify-between rounded-lg bg-red-50 p-2.5 text-xs text-red-700 dark:bg-red-950/30 dark:text-red-300"><span>{error}</span><button onClick={() => setError('')}><X className="h-4 w-4" /></button></div>}
      <div className="flex min-h-0 flex-1"><section className="flex min-w-0 flex-1 flex-col p-3"><textarea ref={editorRef} value={content} onChange={e => setContent(e.target.value)} onSelect={e => { const target = e.currentTarget; setSelection({ start: target.selectionStart, end: target.selectionEnd }); }} aria-label="Document editor" placeholder="Start writing, or describe a draft below…" className="min-h-0 flex-1 resize-none rounded-2xl border bg-white p-5 text-sm leading-7 outline-none focus:border-teal-500 dark:border-zinc-800 dark:bg-zinc-900" /><div className="mt-2 flex items-center justify-between text-[11px]"><span className={wordCount > wordLimit ? 'text-red-500' : wordCount > wordLimit * .85 ? 'text-amber-500' : 'text-slate-400'}>{wordCount}/{wordLimit} words · {content.length} characters</span><span className="text-slate-400">{paid ? 'Paid access' : `${Math.max(0, dailyLimit - used)} free generations left`}</span></div><div className="mt-2 flex gap-2"><textarea value={instructions} onChange={e => setInstructions(e.target.value)} rows={2} placeholder={`Describe the ${activeTemplate.name.toLowerCase()} you want…`} className="min-w-0 flex-1 resize-none rounded-xl border bg-white p-3 text-sm dark:border-zinc-800 dark:bg-zinc-900" />{loading ? <button onClick={() => abortRef.current?.abort()} className="self-end rounded-xl bg-slate-900 p-3 text-white dark:bg-white dark:text-zinc-900" aria-label="Stop generation"><Square className="h-4 w-4 fill-current" /></button> : <button onClick={() => generate('generate')} disabled={!instructions.trim()} className="flex self-end items-center gap-2 rounded-xl bg-teal-600 px-4 py-3 text-xs font-semibold text-white disabled:opacity-40"><Sparkles className="h-4 w-4" /> Generate</button>}</div></section>
        <aside className={`${showOptions ? 'fixed inset-y-0 right-0 z-30 flex w-80 shadow-xl' : 'hidden'} flex-col border-l bg-white p-4 xl:static xl:flex xl:w-72 xl:shadow-none dark:border-zinc-800 dark:bg-zinc-900`}><div className="mb-3 flex justify-between"><h2 className="text-sm font-semibold">AI options</h2><button className="xl:hidden" onClick={() => setShowOptions(false)}><X className="h-4 w-4" /></button></div>{[['Purpose', purpose, setPurpose, ['Inform', 'Persuade', 'Explain', 'Entertain']], ['Audience', audience, setAudience, ['General', 'Students', 'Professionals', 'Executives']], ['Tone', tone, setTone, ['Professional', 'Friendly', 'Formal', 'Confident', 'Conversational']], ['Language', language, setLanguage, ['English', 'Hindi', 'Spanish', 'French', 'German']], ['Length', length, setLength, ['Short', 'Medium', 'Long']], ['Reading level', readingLevel, setReadingLevel, ['Simple', 'General', 'Advanced', 'Academic']]].map(([label, value, setter, choices]: any) => <label key={label} className="mb-3 text-xs">{label}<select value={value} onChange={e => setter(e.target.value)} className="mt-1 w-full rounded-lg border bg-white p-2 dark:border-zinc-700 dark:bg-zinc-950">{choices.map((choice: string) => <option key={choice}>{choice}</option>)}</select></label>)}<label className="text-xs">Keywords<input value={keywords} onChange={e => setKeywords(e.target.value)} placeholder="Comma-separated" className="mt-1 w-full rounded-lg border p-2 dark:border-zinc-700 dark:bg-zinc-950" /></label></aside>
      </div>
    </main>
  </div>;
}
