import React, { useEffect, useState } from 'react';
import { CreditCard, Loader2, ShieldCheck } from 'lucide-react';

export default function Billing({ currentUser, onOpenPricing }: { currentUser?: any; onOpenPricing?: () => void }) {
  const [data, setData] = useState<any>(null), [error, setError] = useState('');
  const userId = currentUser?.email || currentUser?.id || '';
  useEffect(() => { if (!userId) return; fetch('/api/billing/subscription', { headers: { Authorization: `Bearer ${userId}` } }).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); }).catch(cause => setError(cause.message || 'Billing details are unavailable.')); }, [userId]);
  if (!data && !error) return <div className="flex h-full items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-teal-600" /></div>;
  return <div className="mx-auto max-w-2xl space-y-5"><div><h1 className="text-xl font-semibold">Manage Plan</h1><p className="text-sm text-slate-500">Verified subscription and billing status.</p></div>{error ? <div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div> : <div className="rounded-2xl border bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><div className="flex items-center gap-3"><ShieldCheck className="h-7 w-7 text-teal-600" /><div><p className="text-xs text-slate-500">Current plan</p><h2 className="text-lg font-semibold">{data.plan?.name || data.subscription}</h2></div></div><dl className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-slate-50 p-3 dark:bg-zinc-950"><dt className="text-xs text-slate-500">Status</dt><dd className="font-medium capitalize">{data.billing?.status || 'Free'}</dd></div><div className="rounded-lg bg-slate-50 p-3 dark:bg-zinc-950"><dt className="text-xs text-slate-500">Currency</dt><dd className="font-medium">INR</dd></div></dl><button onClick={onOpenPricing} className="mt-5 flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-semibold text-white"><CreditCard className="h-4 w-4" /> View available plans</button></div>}</div>;
}
