import React, { useEffect, useMemo, useState } from 'react';
import { Download, FileText, Search, Trash2 } from 'lucide-react';

interface DocumentItem { id: string; name: string; type: string; mimeType?: string; size: string; pages: number; status?: string; searchable?: boolean; projectId?: string }

export default function Documents({ currentUser }: { currentUser?: any }) {
  const [documents, setDocuments] = useState<DocumentItem[]>([]); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [confirmDelete, setConfirmDelete] = useState<string | null>(null);
  const headers: Record<string, string> = currentUser?.sessionToken ? { Authorization: `Bearer ${currentUser.sessionToken}` } : {};
  const load = async () => { setLoading(true); try { const response = await fetch('/api/documents', { headers }); if (!response.ok) throw new Error('Document library is unavailable.'); const body = await response.json(); setDocuments(body.documents || []); } catch (cause: any) { setError(cause.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [currentUser?.sessionToken]);
  const filtered = useMemo(() => documents.filter(document => document.name.toLowerCase().includes(search.toLowerCase())), [documents, search]);
  const remove = async (id: string) => { const response = await fetch(`/api/documents/${id}`, { method: 'DELETE', headers }); if (!response.ok) { setError('Document could not be deleted.'); return; } setDocuments(items => items.filter(item => item.id !== id)); setConfirmDelete(null); };
  const download = async (item: DocumentItem) => { const response = await fetch(`/api/documents/${item.id}/download`, { headers }); if (!response.ok) { setError('Original file is unavailable.'); return; } const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = item.name; link.click(); URL.revokeObjectURL(url); };
  return <div className="mx-auto max-w-6xl space-y-5"><header><h1 className="text-2xl font-black">Document Library</h1><p className="mt-1 text-sm text-slate-500 dark:text-zinc-400">Your saved uploads and their real processing status.</p></header><label className="relative block max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><span className="sr-only">Search document names</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search filenames" className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-10 pr-3 text-sm dark:border-zinc-800 dark:bg-zinc-900" /></label>{error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-950/30 dark:text-rose-300">{error}</p>}{loading ? <p className="text-sm text-slate-400">Loading documents…</p> : filtered.length ? <ul className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(document => <li key={document.id} className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><div className="flex items-start gap-3"><span className="rounded-xl bg-teal-50 p-2 text-teal-600 dark:bg-teal-950/30"><FileText className="h-5 w-5" /></span><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{document.name}</strong><p className="mt-1 text-xs text-slate-400">{document.type} · {document.pages} pages · {document.size}</p><p className="mt-1 text-[10px] font-bold uppercase text-slate-500">{document.status || 'Stored'} · {document.searchable ? 'Searchable' : 'Text unavailable'}</p></div></div><div className="mt-4 flex gap-2"><button onClick={() => download(document)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold dark:border-zinc-700"><Download className="h-3.5 w-3.5" /> Download</button><button onClick={() => setConfirmDelete(document.id)} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50" aria-label={`Delete ${document.name}`}><Trash2 className="h-4 w-4" /></button></div></li>)}</ul> : <div className="rounded-2xl border border-dashed border-slate-300 p-12 text-center text-sm text-slate-400 dark:border-zinc-700">No saved documents found.</div>}{confirmDelete && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-4" role="dialog" aria-modal="true" aria-labelledby="delete-document-title"><div className="max-w-sm rounded-2xl bg-white p-5 dark:bg-zinc-900"><h2 id="delete-document-title" className="font-black">Delete document?</h2><p className="mt-2 text-sm text-slate-500">The stored original and extracted data will be removed from normal access.</p><div className="mt-5 flex justify-end gap-2"><button onClick={() => setConfirmDelete(null)} className="rounded-xl px-4 py-2 text-xs font-bold">Cancel</button><button onClick={() => remove(confirmDelete)} className="rounded-xl bg-rose-600 px-4 py-2 text-xs font-black text-white">Delete</button></div></div></div>}</div>;
}
