import React, { useEffect, useMemo, useState } from 'react';
import {
  Activity, AlertTriangle, Archive, Bot, Building2, Check, ChevronRight, Copy,
  CreditCard, Database, Download, Gauge, KeyRound, Loader2, LockKeyhole, Play,
  Plus, RefreshCw, Server, Settings, ShieldCheck, Trash2, UserPlus, Users, Webhook,
  Workflow,
} from 'lucide-react';
import { authHeaders } from '../../utils/auth';

type Section = 'overview' | 'members' | 'billing' | 'developer' | 'automation' | 'security' | 'settings' | 'admin';
interface Props { currentUser: any; initialSection?: Section; onSelectWorkspace?: (id: any) => void }

const sectionItems: Array<{ id: Section; label: string; icon: React.ComponentType<{ className?: string }> }> = [
  { id: 'overview', label: 'Workspace', icon: Building2 }, { id: 'members', label: 'Members & Teams', icon: Users },
  { id: 'billing', label: 'Usage & Billing', icon: CreditCard }, { id: 'developer', label: 'API & Webhooks', icon: KeyRound },
  { id: 'automation', label: 'Automations', icon: Workflow }, { id: 'security', label: 'Security & Data', icon: ShieldCheck },
  { id: 'settings', label: 'Policies', icon: Settings }, { id: 'admin', label: 'Admin Console', icon: LockKeyhole },
];

const Empty = ({ title, text }: { title: string; text: string }) => <div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center dark:border-zinc-700"><p className="text-sm font-black">{title}</p><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></div>;
const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className="block text-xs font-bold text-slate-700 dark:text-zinc-300"><span className="mb-1.5 block">{label}</span>{children}</label>;
const inputClass = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-teal-500 dark:border-zinc-700 dark:bg-zinc-950';
const buttonClass = 'inline-flex items-center justify-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-xs font-black text-white hover:bg-teal-700 disabled:cursor-not-allowed disabled:opacity-45';

export default function EnterprisePlatform({ currentUser, initialSection = 'overview', onSelectWorkspace }: Props) {
  const [section, setSection] = useState<Section>(initialSection);
  const [context, setContext] = useState<any>(null);
  const [workspaces, setWorkspaces] = useState<any[]>([]);
  const [data, setData] = useState<any>({});
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [oneTimeSecret, setOneTimeSecret] = useState('');
  const auth = useMemo(() => authHeaders(currentUser), [currentUser?.sessionToken]);
  const isAdmin = currentUser?.role === 'SuperAdmin' || Boolean(currentUser?.adminRole);

  const request = async (path: string, init: RequestInit = {}) => {
    const headers = new Headers(init.headers); Object.entries(auth).forEach(([key, value]) => headers.set(key, value));
    if (init.body && !headers.has('Content-Type')) headers.set('Content-Type', 'application/json');
    const response = await fetch(path, { ...init, headers }); const body = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(body.error || 'Request failed.'); return body;
  };

  const loadContext = async () => { const body = await request('/api/platform/context'); setContext(body.context); setWorkspaces(body.workspaces || []); return body.context; };
  const loadSection = async (next = section) => {
    setLoading(true); setError(''); setNotice(''); setOneTimeSecret('');
    try {
      const nextContext = await loadContext();
      if (next === 'members' && nextContext.tenantType === 'organization') { const [members, teams] = await Promise.all([request('/api/platform/members'), request('/api/platform/teams')]); setData({ ...members, ...teams }); }
      else if (next === 'billing') { const [billing, usage, plans, selection] = await Promise.all([request('/api/platform/billing'), request('/api/platform/usage'), request('/api/pricing/plans'), request('/api/pricing/selection')]); setData({ ...billing, usage, plans: plans.plans, selection: selection.selection, selectedPlan: selection.plan }); }
      else if (next === 'developer' && nextContext.entitlements.includes('api_access')) { const [keys, hooks, integrations] = await Promise.all([request('/api/platform/api-keys'), request('/api/platform/webhooks'), request('/api/platform/integrations')]); setData({ ...keys, ...hooks, ...integrations }); }
      else if (next === 'automation' && nextContext.entitlements.includes('automations')) setData(await request('/api/platform/automations'));
      else if (next === 'security') { const [sessions, audit, exports] = await Promise.all([request('/api/auth/sessions'), request('/api/platform/audit-logs'), request('/api/platform/data-exports')]); setData({ ...sessions, ...audit, ...exports }); }
      else if (next === 'admin' && isAdmin) setData(await request('/api/admin/platform'));
      else setData({});
    } catch (cause: any) { setError(cause.message); setData({}); }
    finally { setLoading(false); }
  };

  useEffect(() => { setSection(initialSection); loadSection(initialSection); }, [initialSection, currentUser?.sessionToken]);
  const choose = (next: Section) => { if (next === 'admin' && !isAdmin) { setError('Administrative permission required.'); return; } setSection(next); loadSection(next); };
  const mutate = async (action: () => Promise<any>, success: string, reload = true) => { setBusy(true); setError(''); setNotice(''); try { const body = await action(); setNotice(success); if (reload) await loadSection(section); return body; } catch (cause: any) { setError(cause.message); } finally { setBusy(false); } };

  const copySecret = async () => { if (!oneTimeSecret) return; await navigator.clipboard.writeText(oneTimeSecret); setNotice('Copied. Store it securely; it will not be shown again.'); };

  return <div className="mx-auto max-w-7xl space-y-5 pb-12">
    <header className="rounded-3xl bg-slate-950 p-6 text-white sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-teal-300">Enterprise platform</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">Workspace, organization and developer controls</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Tenant-scoped access, billing state, usage, teams, API credentials, webhooks, automation and governance.</p></div>{context && <div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-xs"><p className="font-black">{context.workspace?.name}</p><p className="mt-1 text-slate-400">{context.planId?.replace('_', ' ')} · {context.role}</p></div>}</div></header>
    <div className="grid gap-5 lg:grid-cols-[240px_minmax(0,1fr)]">
      <nav aria-label="Platform sections" className="flex gap-2 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-2 lg:block lg:space-y-1 dark:border-zinc-800 dark:bg-zinc-900">{sectionItems.filter(item => item.id !== 'admin' || isAdmin).map(item => <button key={item.id} onClick={() => choose(item.id)} className={`flex shrink-0 items-center gap-2 rounded-xl px-3 py-2.5 text-xs font-bold lg:w-full ${section === item.id ? 'bg-teal-50 text-teal-700 dark:bg-teal-950 dark:text-teal-300' : 'text-slate-500 hover:bg-slate-50 dark:hover:bg-zinc-800'}`}><item.icon className="h-4 w-4" />{item.label}</button>)}</nav>
      <main className="min-w-0 space-y-4">
        {(error || notice || oneTimeSecret) && <div aria-live="polite" className={`rounded-2xl border p-4 text-sm ${error ? 'border-rose-200 bg-rose-50 text-rose-700 dark:border-rose-900 dark:bg-rose-950' : 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950'}`}>{error || notice}{oneTimeSecret && <div className="mt-3 flex flex-col gap-2 sm:flex-row"><code className="min-w-0 flex-1 overflow-x-auto rounded-lg bg-black/10 p-2 text-xs">{oneTimeSecret}</code><button onClick={copySecret} className="rounded-lg border px-3 py-2 text-xs font-bold"><Copy className="mr-1 inline h-3.5 w-3.5" />Copy once</button></div>}</div>}
        {loading ? <div className="flex min-h-80 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-teal-500" aria-label="Loading platform data" /></div> : <>
          {section === 'overview' && <Overview context={context} workspaces={workspaces} busy={busy} request={request} mutate={mutate} onSelectWorkspace={onSelectWorkspace} />}
          {section === 'members' && <Members data={data} context={context} busy={busy} request={request} mutate={mutate} setSecret={setOneTimeSecret} />}
          {section === 'billing' && <Billing data={data} busy={busy} currentUser={currentUser} request={request} onSelectWorkspace={onSelectWorkspace} />}
          {section === 'developer' && <Developer data={data} context={context} busy={busy} request={request} mutate={mutate} setSecret={setOneTimeSecret} />}
          {section === 'automation' && <Automations data={data} context={context} busy={busy} request={request} mutate={mutate} />}
          {section === 'security' && <Security data={data} busy={busy} request={request} mutate={mutate} setSecret={setOneTimeSecret} />}
          {section === 'settings' && <Policies context={context} busy={busy} request={request} mutate={mutate} />}
          {section === 'admin' && isAdmin && <Admin data={data} busy={busy} request={request} mutate={mutate} />}
        </>}
      </main>
    </div>
  </div>;
}

function Card({ title, icon: Icon, children }: { title: string; icon?: React.ComponentType<{ className?: string }>; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h2 className="flex items-center gap-2 text-sm font-black">{Icon && <Icon className="h-4 w-4 text-teal-600" />}{title}</h2><div className="mt-4">{children}</div></section>; }

function Overview({ context, workspaces, busy, request, mutate, onSelectWorkspace }: any) {
  const [form, setForm] = useState({ name: '', industry: '', timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC' });
  const create = () => mutate(async () => request('/api/platform/organizations', { method: 'POST', body: JSON.stringify(form) }), 'Organization created. Use the workspace switcher to activate it.');
  return <div className="grid gap-4 xl:grid-cols-2"><Card title="Active workspace" icon={Building2}><dl className="grid gap-3 text-xs sm:grid-cols-2"><div><dt className="text-slate-400">Tenant</dt><dd className="mt-1 font-black capitalize">{context?.tenantType}</dd></div><div><dt className="text-slate-400">Plan</dt><dd className="mt-1 font-black capitalize">{context?.planId?.replace('_', ' ')}</dd></div><div><dt className="text-slate-400">Role</dt><dd className="mt-1 font-black capitalize">{context?.role}</dd></div><div><dt className="text-slate-400">Workspaces</dt><dd className="mt-1 font-black">{workspaces.length}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2">{workspaces.map((workspace: any) => <span key={workspace.id} className="rounded-full bg-slate-100 px-3 py-1.5 text-[10px] font-bold dark:bg-zinc-800">{workspace.name} · {workspace.role}</span>)}</div></Card>
    <Card title="Create organization" icon={Plus}>{context?.entitlements?.includes('organizations') ? <form onSubmit={event => { event.preventDefault(); create(); }} className="space-y-3"><Field label="Organization name"><input className={inputClass} value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Industry"><input className={inputClass} value={form.industry} onChange={event => setForm({ ...form, industry: event.target.value })} /></Field><Field label="Timezone"><input className={inputClass} value={form.timezone} onChange={event => setForm({ ...form, timezone: event.target.value })} /></Field></div><button disabled={busy} className={buttonClass}><Building2 className="h-4 w-4" />Create organization</button></form> : <Empty title="Organization access is locked" text="Upgrade to a plan with organization entitlement. Personal Workspace remains available." />}</Card>
    <Card title="Resolved entitlements" icon={Check}><div className="flex flex-wrap gap-2">{(context?.entitlements || []).map((item: string) => <span key={item} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-[10px] font-bold dark:border-zinc-700">{item.replaceAll('_', ' ')}</span>)}</div></Card>
    <Card title="Shared resources" icon={Database}><p className="text-xs leading-5 text-slate-500">Projects, documents, chats, Brand Kits, glossaries, translations, business assets and media assets resolve through the active server-validated tenant context.</p><button onClick={() => onSelectWorkspace?.('projects')} className="mt-4 inline-flex items-center gap-2 text-xs font-black text-teal-700">Open Projects <ChevronRight className="h-4 w-4" /></button></Card></div>;
}

function Members({ data, context, busy, request, mutate, setSecret }: any) {
  const [invite, setInvite] = useState({ email: '', roleId: 'member' }); const [team, setTeam] = useState({ name: '', description: '' }); const [assignment, setAssignment] = useState({ teamId: '', membershipId: '' });
  if (context?.tenantType !== 'organization') return <Empty title="Organization workspace required" text="Switch to an organization to manage members, invitations and teams." />;
  const sendInvite = () => mutate(async () => { const body = await request('/api/platform/invitations', { method: 'POST', body: JSON.stringify(invite) }); setSecret(body.invitationToken); return body; }, 'Invitation created. The one-time token appears below.');
  const update = (id: string, patch: any) => mutate(() => request(`/api/platform/members/${id}`, { method: 'PATCH', body: JSON.stringify(patch) }), 'Membership updated.');
  const resend = (id: string) => mutate(async () => { const body = await request(`/api/platform/invitations/${id}/resend`, { method: 'POST', body: '{}' }); setSecret(body.invitationToken); return body; }, 'Invitation token rotated. Share the new one-time token securely.');
  const assign = () => mutate(() => request(`/api/platform/teams/${assignment.teamId}/members`, { method: 'POST', body: JSON.stringify({ membershipId: assignment.membershipId }) }), 'Team membership updated.');
  return <div className="space-y-4"><div className="grid gap-4 xl:grid-cols-2"><Card title="Invite member" icon={UserPlus}><form onSubmit={event => { event.preventDefault(); sendInvite(); }} className="grid gap-3 sm:grid-cols-[1fr_160px_auto]"><input type="email" aria-label="Member email" className={inputClass} value={invite.email} onChange={event => setInvite({ ...invite, email: event.target.value })} placeholder="person@company.com" required /><select aria-label="Member role" className={inputClass} value={invite.roleId} onChange={event => setInvite({ ...invite, roleId: event.target.value })}>{Object.entries<any>(data.roles || {}).filter(([id]) => id !== 'owner').map(([id, role]) => <option key={id} value={id}>{role.name}</option>)}</select><button disabled={busy} className={buttonClass}>Invite</button></form><p className="mt-3 text-[11px] text-slate-500">Tokens expire after seven days, are hashed in storage, and are invalidated after acceptance or revocation.</p></Card>
    <Card title="Create team" icon={Users}><form onSubmit={event => { event.preventDefault(); mutate(() => request('/api/platform/teams', { method: 'POST', body: JSON.stringify(team) }), 'Team created.'); }} className="space-y-3"><input aria-label="Team name" className={inputClass} value={team.name} onChange={event => setTeam({ ...team, name: event.target.value })} placeholder="Team name" required /><input aria-label="Team description" className={inputClass} value={team.description} onChange={event => setTeam({ ...team, description: event.target.value })} placeholder="Purpose and scope" /><button disabled={busy} className={buttonClass}><Plus className="h-4 w-4" />Create team</button></form></Card></div>
    <Card title="Members" icon={Users}>{data.members?.length ? <div className="space-y-2">{data.members.map((member: any) => <div key={member.id} className="grid gap-3 rounded-xl border border-slate-200 p-3 sm:grid-cols-[1fr_150px_130px] sm:items-center dark:border-zinc-700"><div className="min-w-0"><p className="truncate text-xs font-black">{member.user?.name || member.userId}</p><p className="truncate text-[10px] text-slate-400">{member.user?.email} · {member.status}</p></div><select aria-label={`Role for ${member.user?.name}`} value={member.roleId} onChange={event => update(member.id, { roleId: event.target.value })} className={inputClass} disabled={busy}>{Object.entries<any>(data.roles || {}).map(([id, role]) => <option key={id} value={id}>{role.name}</option>)}</select><button onClick={() => update(member.id, { status: member.status === 'suspended' ? 'active' : 'suspended' })} disabled={busy} className="rounded-xl border px-3 py-2 text-xs font-bold dark:border-zinc-700">{member.status === 'suspended' ? 'Reactivate' : 'Suspend'}</button></div>)}</div> : <Empty title="No members" text="No active organization members were returned." />}</Card>
    <Card title="Pending invitations" icon={UserPlus}>{data.invitations?.length ? <div className="space-y-2">{data.invitations.map((item: any) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 text-xs dark:border-zinc-700"><span><strong>{item.email}</strong><span className="ml-2 text-slate-500">{item.roleId} · expires {new Date(item.expiresAt).toLocaleDateString()}</span></span><span className="flex gap-2"><button onClick={() => resend(item.id)} disabled={busy} className="rounded-lg border px-3 py-2 font-bold dark:border-zinc-700">Resend</button><button onClick={() => mutate(() => request(`/api/platform/invitations/${item.id}`, { method: 'DELETE' }), 'Invitation revoked.')} disabled={busy} className="rounded-lg border px-3 py-2 font-bold text-rose-600 dark:border-zinc-700">Revoke</button></span></div>)}</div> : <Empty title="No pending invitations" text="Outstanding invitations will appear here." />}</Card>
    <Card title="Team access" icon={Users}>{data.teams?.length ? <><div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><select aria-label="Team" className={inputClass} value={assignment.teamId} onChange={event => setAssignment({ ...assignment, teamId: event.target.value })}><option value="">Select team</option>{data.teams.map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Organization member" className={inputClass} value={assignment.membershipId} onChange={event => setAssignment({ ...assignment, membershipId: event.target.value })}><option value="">Select member</option>{(data.members || []).filter((item: any) => item.status === 'active').map((item: any) => <option key={item.id} value={item.id}>{item.user?.name || item.user?.email}</option>)}</select><button onClick={assign} disabled={busy || !assignment.teamId || !assignment.membershipId} className={buttonClass}>Add</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.teams.map((item: any) => <div key={item.id} className="rounded-xl border border-slate-200 p-4 dark:border-zinc-700"><p className="text-xs font-black">{item.name}</p><p className="mt-1 text-[11px] text-slate-500">{item.description || 'No description'} · {item.memberships?.length || 0} member(s)</p><div className="mt-2 space-y-1">{(item.memberships || []).map((teamMember: any) => { const member = (data.members || []).find((candidate: any) => candidate.id === teamMember.membershipId); return <div key={teamMember.id} className="flex items-center justify-between text-[10px]"><span>{member?.user?.name || member?.user?.email || teamMember.membershipId}</span><button onClick={() => mutate(() => request(`/api/platform/teams/${item.id}/members/${teamMember.id}`, { method: 'DELETE' }), 'Team member removed.')} className="font-bold text-rose-600">Remove</button></div>; })}</div></div>)}</div></> : <Empty title="No teams" text="Create the first access group for this organization." />}</Card></div>;
}

function Billing({ data, busy, currentUser, request, onSelectWorkspace }: any) {
  const [checkout, setCheckout] = useState<any>(null); const [stage, setStage] = useState(''); const [localError, setLocalError] = useState(''); const selectedPlan = data.selectedPlan;
  useEffect(() => { setCheckout(null); setStage(''); setLocalError(''); }, [data.selection?.id]);
  const prepareCheckout = async () => { if (!selectedPlan || selectedPlan.contactSales) return; setStage('Preparing checkout'); setLocalError(''); try { const body = await request('/api/billing/checkout', { method: 'POST', body: JSON.stringify({ planKey: selectedPlan.key, billingInterval: 'monthly', idempotencyKey: crypto.randomUUID() }) }); if (body.checkout.planKey !== selectedPlan.key || body.checkout.summary?.planKey !== selectedPlan.key || body.checkout.summary?.amountMinor !== selectedPlan.monthlyPrice * 100) { fetch('/api/pricing/events', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ event: 'plan_mismatch_blocked', metadata: { planKey: selectedPlan.key, sourceTool: 'billing', reason: 'checkout_summary_mismatch' } }) }).catch(() => undefined); throw new Error('Checkout details do not match the selected plan. Payment was stopped.'); } setCheckout(body.checkout); setStage('Ready for secure payment'); } catch (cause: any) { setStage(''); setLocalError(cause.message || 'Checkout could not be prepared.'); } };
  const pay = async () => { if (!checkout) return; setStage('Opening secure payment'); setLocalError(''); try { await openRazorpay(checkout, currentUser, async (response: any) => { setStage('Payment received, verifying'); const verification = await request('/api/billing/verify', { method: 'POST', body: JSON.stringify({ razorpay_order_id: response.razorpay_order_id, razorpay_payment_id: response.razorpay_payment_id, razorpay_signature: response.razorpay_signature, planKey: selectedPlan.key }) }); setStage(verification.status === 'verification_pending' ? 'Verification pending' : 'Updating subscription'); }); } catch (cause: any) { setStage(cause.message === 'Payment was cancelled.' ? 'Payment cancelled' : 'Payment failed'); setLocalError(cause.message || 'Payment could not be completed.'); } };
  return <div className="space-y-4"><div className="grid gap-4 xl:grid-cols-3"><Card title="Current plan" icon={CreditCard}><p className="text-2xl font-black capitalize">{data.plan?.name || 'Free'}</p><p className="mt-2 text-xs text-slate-500">Provider: {data.provider || 'Not configured'}</p><p className="mt-2 text-xs">Status: <strong>{data.subscriptionStatus || 'free'}</strong></p>{data.cancelAtPeriodEnd && <p className="mt-2 text-xs text-amber-700">Cancellation is scheduled at the end of the current period.</p>}</Card><Card title="Usage dimensions" icon={Gauge}><div className="space-y-2 text-xs">{Object.keys(data.usage?.totals || {}).length ? Object.entries(data.usage.totals).map(([key, value]) => <div key={key} className="flex justify-between gap-3"><span>{key.replaceAll('_', ' ')}</span><strong>{String(value)}</strong></div>) : <p className="text-slate-500">No platform usage events yet.</p>}</div></Card><Card title="Billing portal" icon={CreditCard}><p className="text-xs leading-5 text-slate-500">{data.billingPortal?.available ? 'Available' : data.billingPortal?.reason || 'Not configured.'}</p></Card></div>
    <Card title="Selected plan" icon={RefreshCw}>{selectedPlan ? selectedPlan.contactSales ? <div><p className="text-lg font-black">{selectedPlan.name} · {selectedPlan.displayPrice}</p><p className="mt-2 text-xs text-slate-500">This plan uses the Contact Sales flow and cannot start Razorpay checkout.</p><button onClick={() => onSelectWorkspace?.('pricing')} className={`${buttonClass} mt-4`}>Contact Sales</button></div> : <div className="space-y-4"><div className="rounded-2xl border border-slate-200 p-4 dark:border-zinc-700"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Selected plan</p><p className="mt-1 text-xl font-black">{selectedPlan.name}</p><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Price</dt><dd className="font-black">{selectedPlan.displayPrice}/month</dd></div><div><dt className="text-xs text-slate-500">Billing</dt><dd className="font-black">Monthly</dd></div></dl></div>{!checkout ? <button disabled={busy || !data.provider || stage === 'Preparing checkout'} onClick={prepareCheckout} className={buttonClass}>{stage === 'Preparing checkout' && <Loader2 className="h-4 w-4 animate-spin" />}Prepare secure payment</button> : <div className="rounded-2xl border-2 border-teal-500 p-4"><p className="text-xs font-black uppercase tracking-wide text-teal-700">Verified checkout summary</p><p className="mt-2 text-xl font-black">{checkout.summary.planName}</p><p className="mt-1 text-sm">{checkout.summary.displayPrice}/month · {checkout.summary.billingInterval}</p><button disabled={stage === 'Opening secure payment' || stage === 'Payment received, verifying'} onClick={pay} className={`${buttonClass} mt-4`}>{stage === 'Opening secure payment' || stage === 'Payment received, verifying' ? <Loader2 className="h-4 w-4 animate-spin" /> : <ShieldCheck className="h-4 w-4" />}Continue to Secure Payment</button></div>}{stage && stage !== 'Preparing checkout' && <p role="status" className="rounded-xl bg-slate-100 p-3 text-xs font-bold dark:bg-zinc-800">{stage}</p>}{localError && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700 dark:bg-rose-950 dark:text-rose-200">{localError}</p>}{!data.provider && <p className="text-xs text-amber-700">{data.checkoutAvailability?.reason === 'durable_billing_storage_required' ? 'Secure checkout is disabled until durable billing storage is configured.' : 'Checkout is disabled because Razorpay environment variables are not configured.'}</p>}</div> : <div><Empty title="No plan selected" text="Choose a plan on the Pricing page before starting checkout. No default plan will be selected for you." /><button onClick={() => onSelectWorkspace?.('pricing')} className={`${buttonClass} mt-4`}>Compare Plans</button></div>}</Card>
    <Card title="Invoices" icon={Archive}>{data.invoices?.length ? <div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-xs"><thead><tr className="border-b dark:border-zinc-700"><th className="p-2">Invoice</th><th>Amount</th><th>Currency</th><th>Status</th><th>Paid</th></tr></thead><tbody>{data.invoices.map((invoice: any) => <tr key={invoice.id} className="border-b dark:border-zinc-800"><td className="p-2 font-mono">{invoice.id}</td><td>{(Number(invoice.amount || 0) / 100).toFixed(2)}</td><td>{invoice.currency}</td><td>{invoice.status}</td><td>{invoice.paidAt ? new Date(invoice.paidAt).toLocaleDateString() : '—'}</td></tr>)}</tbody></table></div> : <Empty title="No invoices" text="Verified provider invoices will appear here. No invoice data is fabricated." />}</Card></div>;
}

async function openRazorpay(checkout: any, user: any, onSuccess: (response: any) => Promise<void>) {
  const win = window as any; if (!win.Razorpay) await new Promise<void>((resolve, reject) => { const script = document.createElement('script'); script.src = 'https://checkout.razorpay.com/v1/checkout.js'; script.onload = () => resolve(); script.onerror = () => reject(new Error('Razorpay Checkout could not be loaded.')); document.head.appendChild(script); });
  await new Promise<void>((resolve, reject) => { const instance = new win.Razorpay({ key: checkout.keyId, order_id: checkout.orderId, amount: checkout.amount, currency: checkout.currency, name: 'GXA AI Workspace', description: `${checkout.summary?.planName || 'Workspace'} subscription`, prefill: { name: user?.name, email: user?.email }, handler: async (response: any) => { try { await onSuccess(response); resolve(); } catch (error) { reject(error); } }, modal: { ondismiss: () => reject(new Error('Payment was cancelled.')) } }); instance.open(); });
}

function Developer({ data, context, busy, request, mutate, setSecret }: any) {
  const [keyForm, setKeyForm] = useState({ name: '', scopes: ['usage:read'] }); const [hook, setHook] = useState({ name: '', url: '', events: ['project.updated'] });
  const createKey = () => mutate(async () => { const body = await request('/api/platform/api-keys', { method: 'POST', body: JSON.stringify(keyForm) }); setSecret(body.secret); return body; }, 'API key created.');
  const createHook = () => mutate(async () => { const body = await request('/api/platform/webhooks', { method: 'POST', body: JSON.stringify(hook) }); setSecret(body.secret); return body; }, 'Webhook created.');
  if (!context?.entitlements?.includes('api_access')) return <Empty title="Developer API is locked" text="This workspace plan does not include API keys or outgoing webhooks. Existing workspace data is unchanged." />;
  return <div className="space-y-4"><div className="grid gap-4 xl:grid-cols-2"><Card title="Create API key" icon={KeyRound}><form onSubmit={event => { event.preventDefault(); createKey(); }} className="space-y-3"><input aria-label="API key name" className={inputClass} value={keyForm.name} onChange={event => setKeyForm({ ...keyForm, name: event.target.value })} placeholder="Production integration" required /><div className="grid grid-cols-2 gap-2">{(data.scopes || []).map((scope: string) => <label key={scope} className="flex items-center gap-2 text-[11px]"><input type="checkbox" checked={keyForm.scopes.includes(scope)} onChange={event => setKeyForm({ ...keyForm, scopes: event.target.checked ? [...keyForm.scopes, scope] : keyForm.scopes.filter(item => item !== scope) })} />{scope}</label>)}</div><button disabled={busy} className={buttonClass}>Create key</button></form></Card><Card title="Create webhook" icon={Webhook}><form onSubmit={event => { event.preventDefault(); createHook(); }} className="space-y-3"><input aria-label="Webhook name" className={inputClass} value={hook.name} onChange={event => setHook({ ...hook, name: event.target.value })} placeholder="Production webhook" required /><input type="url" aria-label="Webhook URL" className={inputClass} value={hook.url} onChange={event => setHook({ ...hook, url: event.target.value })} placeholder="https://example.com/gxa-events" required /><select aria-label="Webhook event" className={inputClass} value={hook.events[0]} onChange={event => setHook({ ...hook, events: [event.target.value] })}>{(data.events || []).map((event: string) => <option key={event}>{event}</option>)}</select><button disabled={busy} className={buttonClass}>Create webhook</button></form></Card></div>
    <Card title="API keys" icon={KeyRound}>{data.keys?.length ? <div className="space-y-2">{data.keys.map((key: any) => <div key={key.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 dark:border-zinc-700"><div><p className="text-xs font-black">{key.name}</p><p className="text-[10px] text-slate-500">{key.prefix}… · {key.scopes.join(', ')} · {key.status}</p></div><span className="flex gap-2"><button onClick={() => mutate(async () => { const body = await request(`/api/platform/api-keys/${key.id}/rotate`, { method: 'POST', body: '{}' }); setSecret(body.secret); return body; }, 'API key rotated. Store the new secret now.')} className="rounded-lg border px-3 py-2 text-xs font-bold dark:border-zinc-700">Rotate</button><button onClick={() => mutate(() => request(`/api/platform/api-keys/${key.id}`, { method: 'DELETE' }), 'API key revoked.')} className="rounded-lg border px-3 py-2 text-xs font-bold text-rose-600 dark:border-zinc-700">Revoke</button></span></div>)}</div> : <Empty title="No API keys" text="Eligible workspaces can create scoped keys. Secrets are displayed only once." />}</Card>
    <Card title="Webhook endpoints" icon={Webhook}>{data.endpoints?.length ? <div className="space-y-2">{data.endpoints.map((hookItem: any) => <div key={hookItem.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 dark:border-zinc-700"><div className="min-w-0"><p className="text-xs font-black">{hookItem.name}</p><p className="truncate text-[10px] text-slate-500">{hookItem.url} · {hookItem.status}</p></div><span className="flex gap-2"><button onClick={() => mutate(async () => { const body = await request(`/api/platform/webhooks/${hookItem.id}/rotate`, { method: 'POST', body: '{}' }); setSecret(body.secret); return body; }, 'Webhook signing secret rotated. Store it now.')} className="rounded-lg border px-3 py-2 text-xs font-bold dark:border-zinc-700">Rotate secret</button><button onClick={() => mutate(() => request(`/api/platform/webhooks/${hookItem.id}`, { method: 'DELETE' }), 'Webhook disabled.')} className="rounded-lg border px-3 py-2 text-xs font-bold text-rose-600 dark:border-zinc-700">Disable</button></span></div>)}</div> : <Empty title="No webhooks" text="Create an HTTPS endpoint. Private-network destinations are blocked server-side." />}</Card>
    <Card title="Integration framework" icon={Server}>{data.integrations?.length ? data.integrations.map((item: any) => <div key={item.id} className="rounded-xl border p-3 text-xs dark:border-zinc-700"><strong>{item.name}</strong><span className="ml-2 text-slate-500">{item.category} · enabled</span></div>) : <Empty title="No connected integrations" text="Only integrations with working authentication and actions are exposed." />}</Card></div>;
}

function Automations({ data, context, busy, request, mutate }: any) {
  const [form, setForm] = useState({ name: '', description: '', trigger: 'manual', action: 'record_audit_event' });
  const create = () => mutate(() => request('/api/platform/automations', { method: 'POST', body: JSON.stringify({ name: form.name, description: form.description, trigger: form.trigger, conditions: [], steps: [{ id: crypto.randomUUID(), action: form.action, config: form.action === 'record_audit_event' ? { action: 'automation.manual_event' } : { name: 'Automation project' }, errorPolicy: 'stop' }] }) }), 'Automation created in paused state.');
  if (!context?.entitlements?.includes('automations')) return <Empty title="Automations are locked" text="This workspace plan does not include structured automations. No workflow data is simulated." />;
  return <div className="space-y-4"><Card title="Structured workflow builder" icon={Workflow}><form onSubmit={event => { event.preventDefault(); create(); }} className="grid gap-3 md:grid-cols-2"><Field label="Name"><input className={inputClass} value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required /></Field><Field label="Description"><input className={inputClass} value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /></Field><Field label="Trigger"><select className={inputClass} value={form.trigger} onChange={event => setForm({ ...form, trigger: event.target.value })}>{(data.triggers || []).map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Action"><select className={inputClass} value={form.action} onChange={event => setForm({ ...form, action: event.target.value })}>{(data.actions || []).filter((item: any) => item.id !== 'send_webhook').map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><button disabled={busy} className={buttonClass}><Plus className="h-4 w-4" />Create workflow</button></form><p className="mt-3 text-[11px] text-slate-500">Only approved structured conditions and actions are accepted. Arbitrary expressions and code execution are not supported.</p></Card>
    <Card title="Workflows" icon={Bot}>{data.workflows?.length ? <div className="space-y-2">{data.workflows.map((workflow: any) => <div key={workflow.id} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center dark:border-zinc-700"><div><p className="text-xs font-black">{workflow.name}</p><p className="text-[10px] text-slate-500">{workflow.trigger} · {workflow.steps.length} step(s) · {workflow.status} · v{workflow.version}</p></div><button onClick={() => mutate(() => request(`/api/platform/automations/${workflow.id}`, { method: 'PATCH', body: JSON.stringify({ status: workflow.status === 'active' ? 'paused' : 'active' }) }), 'Workflow status updated.')} className="rounded-lg border px-3 py-2 text-xs font-bold dark:border-zinc-700">{workflow.status === 'active' ? 'Pause' : 'Activate'}</button><button onClick={() => mutate(() => request(`/api/platform/automations/${workflow.id}/run`, { method: 'POST', body: JSON.stringify({ payload: {} }) }), 'Workflow execution recorded.')} className={buttonClass}><Play className="h-3.5 w-3.5" />Run</button></div>)}</div> : <Empty title="No workflows" text="Create a workflow. Execution history is recorded only after a real run." />}</Card>
    <Card title="Execution history" icon={Activity}>{data.executions?.length ? <div className="space-y-2">{data.executions.map((item: any) => <div key={item.id} className="rounded-xl border p-3 text-xs dark:border-zinc-700"><strong>{item.status}</strong><span className="ml-2 text-slate-500">{item.steps.length} step(s) · {new Date(item.startedAt).toLocaleString()}</span></div>)}</div> : <Empty title="No executions" text="No workflow has run in this workspace." />}</Card></div>;
}

function Security({ data, busy, request, mutate, setSecret }: any) {
  const [password, setPassword] = useState(''); const [newPassword, setNewPassword] = useState('');
  const exportData = () => mutate(async () => { const queued = await request('/api/platform/data-exports', { method: 'POST', body: '{}' }); for (let attempt = 0; attempt < 12; attempt += 1) { await new Promise(resolve => setTimeout(resolve, 250)); const status = await request('/api/platform/data-exports'); const record = (status.exports || []).find((item: any) => item.id === queued.export.id); if (record?.status === 'failed') throw new Error('The export job failed. Try again later.'); if (record?.status === 'ready') { const body = await request(`/api/platform/data-exports/${record.id}/download-token`, { method: 'POST', body: '{}' }); setSecret(`${window.location.origin}/api/platform/data-exports/${record.id}/download?token=${encodeURIComponent(body.downloadToken)}`); return body; } } throw new Error('The export is still processing. Return to Security & Data to request a fresh link.'); }, 'Export ready. The one-hour download link appears below.', false);
  return <div className="space-y-4"><Card title="Active sessions" icon={ShieldCheck}>{data.sessions?.length ? <><div className="space-y-2">{data.sessions.map((session: any) => <div key={session.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 text-xs dark:border-zinc-700"><span>{session.userAgentSummary || 'Unknown device'} · {new Date(session.lastActiveAt).toLocaleString()}{session.current ? ' · Current' : ''}</span>{!session.current && <button onClick={() => mutate(() => request(`/api/auth/sessions/${session.id}`, { method: 'DELETE' }), 'Session revoked.')} className="rounded-lg border px-3 py-2 font-bold dark:border-zinc-700">Revoke</button>}</div>)}</div><button onClick={() => mutate(() => request('/api/auth/sessions/revoke-others', { method: 'POST', body: '{}' }), 'All other sessions revoked.')} disabled={busy || data.sessions.length <= 1} className="mt-3 rounded-lg border px-3 py-2 text-xs font-bold disabled:opacity-40 dark:border-zinc-700">Revoke all other sessions</button></> : <Empty title="No sessions" text="No active sessions were returned." />}</Card>
    <Card title="Immutable audit trail" icon={Activity}>{data.logs?.length ? <div className="max-h-80 space-y-2 overflow-y-auto">{data.logs.map((log: any) => <div key={log.id} className="rounded-xl border p-3 text-xs dark:border-zinc-700"><strong>{log.action}</strong><p className="mt-1 text-[10px] text-slate-500">{new Date(log.createdAt).toLocaleString()} · {log.resourceType} · {log.resourceId}</p></div>)}</div> : <Empty title="No audit events" text="Sensitive actions will appear here when they occur." />}</Card>
    <div className="grid gap-4 xl:grid-cols-2"><Card title="Change password" icon={LockKeyhole}><div className="space-y-3"><input type="password" aria-label="Current password" className={inputClass} value={password} onChange={event => setPassword(event.target.value)} placeholder="Current password" /><input type="password" aria-label="New password" className={inputClass} value={newPassword} onChange={event => setNewPassword(event.target.value)} placeholder="New password, at least 10 characters" /><button onClick={() => mutate(() => request('/api/auth/password', { method: 'POST', body: JSON.stringify({ currentPassword: password, newPassword }) }), 'Password changed and all other sessions revoked.')} disabled={busy || !password || newPassword.length < 10} className={buttonClass}>Change password</button></div></Card><Card title="Data export" icon={Download}><p className="text-xs leading-5 text-slate-500">Exports exclude password hashes, session hashes, API-key hashes, webhook secrets and internal security metadata.</p><button onClick={exportData} disabled={busy} className={`${buttonClass} mt-4`}><Download className="h-4 w-4" />Request export</button></Card><Card title="Account deletion request" icon={Trash2}><p className="text-xs leading-5 text-slate-500">Deletion is scheduled, not immediate. Organization ownership and retention rules are checked first.</p><input type="password" aria-label="Password for account deletion" className={`${inputClass} mt-3`} value={password} onChange={event => setPassword(event.target.value)} placeholder="Confirm current password" /><button onClick={() => mutate(() => request('/api/platform/deletion-requests', { method: 'POST', body: JSON.stringify({ type: 'account', password }) }), 'Deletion request scheduled.')} disabled={busy || !password} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-rose-600 px-4 py-2.5 text-xs font-black text-white disabled:opacity-40"><Trash2 className="h-4 w-4" />Schedule deletion</button></Card></div></div>;
}

function Policies({ context, busy, request, mutate }: any) {
  const organization = context?.organization; const [policies, setPolicies] = useState<any>(organization?.policies || {});
  useEffect(() => setPolicies(context.entitlements?.includes('custom_retention') ? (organization?.policies || {}) : Object.fromEntries(Object.entries(organization?.policies || {}).filter(([key]) => key !== 'retentionDays'))), [organization?.id, context.planId]);
  if (!organization) return <Empty title="Personal Workspace policies" text="Organization security, sharing and retention policies become available inside an organization workspace." />;
  return <Card title="Organization policies" icon={Settings}><form onSubmit={event => { event.preventDefault(); mutate(() => request(`/api/platform/organizations/${organization.id}`, { method: 'PATCH', body: JSON.stringify({ policies }) }), 'Organization policies updated.'); }} className="space-y-4">{[['externalSharing', 'Allow external sharing'], ['publicLinks', 'Allow public links'], ['apiKeys', 'Allow API keys'], ['automations', 'Allow automations']].map(([key, label]) => <label key={key} className="flex items-center justify-between gap-4 rounded-xl border p-3 text-xs font-bold dark:border-zinc-700"><span>{label}</span><input type="checkbox" checked={Boolean(policies[key])} onChange={event => setPolicies({ ...policies, [key]: event.target.checked })} /></label>)}{context.entitlements?.includes('custom_retention') ? <Field label="Retention days"><input type="number" min={30} max={3650} className={inputClass} value={policies.retentionDays || 365} onChange={event => setPolicies({ ...policies, retentionDays: Number(event.target.value) })} /></Field> : <p className="rounded-xl bg-slate-50 p-3 text-xs text-slate-500 dark:bg-zinc-950">Custom retention is unavailable on this plan. The default policy remains unchanged.</p>}<button disabled={busy} className={buttonClass}>Save policies</button></form></Card>;
}

function Admin({ data, busy, request, mutate }: any) {
  const [reason, setReason] = useState('');
  return <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Users" value={data.users?.length || 0} /><Metric label="Organizations" value={data.organizations?.length || 0} /><Metric label="Subscriptions" value={data.subscriptions?.length || 0} /><Metric label="Usage dimensions" value={Object.keys(data.usageTotals || {}).length} /></div>
    <Card title="Provider status" icon={Server}><div className="grid gap-3 sm:grid-cols-2">{(data.providers || []).map((provider: any) => <div key={provider.id} className="rounded-xl border p-4 text-xs dark:border-zinc-700"><strong className="capitalize">{provider.id}</strong><p className={`mt-1 font-bold ${provider.configured ? 'text-emerald-600' : 'text-amber-600'}`}>{provider.credential}</p></div>)}</div></Card>
    <Card title="System health" icon={Activity}><dl className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(data.health || {}).map(([key, value]) => <div key={key} className="rounded-xl bg-slate-50 p-3 text-xs dark:bg-zinc-950"><dt className="text-slate-400">{key}</dt><dd className="mt-1 font-black">{String(value)}</dd></div>)}</dl></Card>
    <Card title="Users" icon={Users}><Field label="Reason required for status changes"><input className={inputClass} value={reason} onChange={event => setReason(event.target.value)} placeholder="Support or security reason" /></Field><div className="mt-3 space-y-2">{(data.users || []).map((user: any) => <div key={user.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 dark:border-zinc-700"><div><p className="text-xs font-black">{user.name || user.email}</p><p className="text-[10px] text-slate-500">{user.email} · {user.subscription} · {user.status}</p></div><button onClick={() => mutate(() => request(`/api/admin/users/${encodeURIComponent(user.id)}`, { method: 'PATCH', body: JSON.stringify({ status: user.status === 'suspended' ? 'active' : 'suspended', reason }) }), 'User status updated.')} disabled={busy || !reason} className="rounded-lg border px-3 py-2 text-xs font-bold disabled:opacity-40 dark:border-zinc-700">{user.status === 'suspended' ? 'Reactivate' : 'Suspend'}</button></div>)}</div></Card>
    <Card title="Organizations" icon={Building2}>{data.organizations?.length ? <div className="space-y-2">{data.organizations.map((organization: any) => <div key={organization.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 dark:border-zinc-700"><div><p className="text-xs font-black">{organization.name}</p><p className="text-[10px] text-slate-500">{organization.slug} · {organization.memberCount} member(s) · {organization.status}</p></div><button onClick={() => mutate(() => request(`/api/admin/organizations/${organization.id}`, { method: 'PATCH', body: JSON.stringify({ status: organization.status === 'suspended' ? 'active' : 'suspended', reason }) }), 'Organization status updated.')} disabled={busy || !reason} className="rounded-lg border px-3 py-2 text-xs font-bold disabled:opacity-40 dark:border-zinc-700">{organization.status === 'suspended' ? 'Reactivate' : 'Suspend'}</button></div>)}</div> : <Empty title="No organizations" text="No real organization records are available." />}</Card>
    <Card title="Feature flags" icon={RefreshCw}><div className="space-y-2">{(data.flags || []).map((flag: any) => <label key={flag.key} className="flex items-center justify-between gap-4 rounded-xl border p-3 text-xs dark:border-zinc-700"><span><strong>{flag.key}</strong><span className="mt-1 block text-[10px] text-slate-500">{flag.description}</span></span><input type="checkbox" checked={Boolean(flag.enabled)} onChange={event => mutate(() => request(`/api/admin/feature-flags/${encodeURIComponent(flag.key)}`, { method: 'PATCH', body: JSON.stringify({ enabled: event.target.checked }) }), 'Feature flag updated.')} /></label>)}</div></Card>
    <Card title="Security events" icon={AlertTriangle}>{data.security?.length ? data.security.map((item: any) => <div key={item.id} className="rounded-xl border p-3 text-xs dark:border-zinc-700"><strong>{item.type}</strong><span className="ml-2 text-slate-500">{item.outcome} · {new Date(item.createdAt).toLocaleString()}</span></div>) : <Empty title="No security events" text="No recorded security events are available." />}</Card></div>;
}

const Metric = ({ label, value }: { label: string; value: string | number }) => <div className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>;
