import React, { useEffect, useRef, useState } from 'react';
import { Bookmark, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Download, FileText, Languages, Loader2, MessageSquare, Minus, Plus, RotateCw, Scissors, Search, Send, Table, Trash2, UploadCloud, X } from 'lucide-react';
import * as pdfjs from 'pdfjs-dist';
import pdfWorker from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import { degrees, PDFDocument } from 'pdf-lib';
import { fetchSystemConfig, fetchUsage, isUserPremium, SystemConfig, UsageStats } from '../../utils/limits';
import { validatePdfFile } from '../../utils/pdfValidation';

pdfjs.GlobalWorkerOptions.workerSrc = pdfWorker;
type PdfDoc = Awaited<ReturnType<typeof pdfjs.getDocument>['promise']>;
type ChatMessage = { id: string; role: 'user' | 'assistant'; text: string };
type Annotation = { id: string; page: number; text: string };
type MobileTab = 'viewer' | 'chat' | 'summary';
interface Props { currentUser?: any; onOpenUpgradeModal?: () => void }

function download(bytes: Uint8Array, name: string) {
  const blob = new Blob([bytes as BlobPart], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url);
}

function PageCanvas({ document, page, zoom, rotation }: { document: PdfDoc; page: number; zoom: number; rotation: number }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  useEffect(() => { let cancelled = false; let task: any; document.getPage(page).then(pdfPage => { if (cancelled || !canvasRef.current) return; const viewport = pdfPage.getViewport({ scale: zoom / 100 * 1.25, rotation }); const canvas = canvasRef.current; const context = canvas.getContext('2d'); if (!context) return; canvas.width = viewport.width; canvas.height = viewport.height; canvas.style.width = `${viewport.width}px`; canvas.style.height = `${viewport.height}px`; task = pdfPage.render({ canvas, canvasContext: context, viewport }); return task.promise; }).catch(() => undefined); return () => { cancelled = true; task?.cancel?.(); }; }, [document, page, zoom, rotation]);
  return <canvas ref={canvasRef} className="max-w-none bg-white shadow-xl" aria-label={`PDF page ${page}`} />;
}

function Thumbnail({ document, page, active, onClick }: { document: PdfDoc; page: number; active: boolean; onClick: () => void }) {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => { let task: any; document.getPage(page).then(pdfPage => { if (!ref.current) return; const viewport = pdfPage.getViewport({ scale: .18 }); const canvas = ref.current; canvas.width = viewport.width; canvas.height = viewport.height; const context = canvas.getContext('2d'); if (context) { task = pdfPage.render({ canvas, canvasContext: context, viewport }); return task.promise; } }).catch(() => undefined); return () => task?.cancel?.(); }, [document, page]);
  return <button onClick={onClick} className={`w-full rounded-lg border p-1.5 text-center text-[10px] ${active ? 'border-teal-500 bg-teal-50 dark:bg-teal-950/30' : 'border-slate-200 dark:border-zinc-700'}`}><canvas ref={ref} className="mx-auto max-w-full bg-white" /><span>Page {page}</span></button>;
}

export default function PDFIntelligence({ currentUser, onOpenUpgradeModal }: Props) {
  const [config, setConfig] = useState<SystemConfig | null>(null), [usage, setUsage] = useState<UsageStats | null>(null);
  const [file, setFile] = useState<File | null>(null), [bytes, setBytes] = useState<ArrayBuffer | null>(null), [dataUrl, setDataUrl] = useState('');
  const [document, setDocument] = useState<PdfDoc | null>(null), [pageText, setPageText] = useState<string[]>([]), [fingerprint, setFingerprint] = useState('');
  const [page, setPage] = useState(1), [zoom, setZoom] = useState(100), [rotation, setRotation] = useState(0);
  const [query, setQuery] = useState(''), [matches, setMatches] = useState<number[]>([]), [matchIndex, setMatchIndex] = useState(0);
  const [bookmarks, setBookmarks] = useState<number[]>([]), [annotations, setAnnotations] = useState<Annotation[]>([]), [note, setNote] = useState('');
  const [chat, setChat] = useState<ChatMessage[]>([]), [chatInput, setChatInput] = useState(''), [summary, setSummary] = useState(''), [result, setResult] = useState('');
  const [tool, setTool] = useState<'chat' | 'summary' | 'ocr' | 'tables' | 'translate'>('chat'), [language, setLanguage] = useState('Hindi');
  const [loading, setLoading] = useState(''), [error, setError] = useState(''), [blocked, setBlocked] = useState(''), [mobileTab, setMobileTab] = useState<MobileTab>('viewer');
  const fileInput = useRef<HTMLInputElement>(null), mergeInput = useRef<HTMLInputElement>(null);
  const userId = currentUser?.email || currentUser?.id || '', premium = isUserPremium(currentUser);
  const persistenceEligible = premium && Boolean(userId);
  const uploadLimit = config?.pdf_uploads_limit || 3, sizeLimit = config?.pdf_file_size_mb || 10, pageLimit = config?.pdf_pages_limit || 50;

  useEffect(() => { Promise.all([fetchSystemConfig(), fetchUsage(userId || 'guest')]).then(([c, u]) => { setConfig(c); setUsage(u); }); }, [userId]);
  useEffect(() => { if (!persistenceEligible || !fingerprint || !document) return; const timer = setTimeout(() => fetch(`/api/pdf-state/${fingerprint}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${userId}` }, body: JSON.stringify({ page, bookmarks, annotations, chat }) }), 600); return () => clearTimeout(timer); }, [page, bookmarks, annotations, chat, fingerprint, document, persistenceEligible, userId]);

  const openUpgrade = (message: string) => { setBlocked(message); onOpenUpgradeModal?.(); };
  const loadFile = async (selected: File) => {
    setFile(selected); setError(''); setBlocked(''); setSummary(''); setResult(''); setChat([]); setBookmarks([]); setAnnotations([]); setPage(1); setRotation(0); setQuery('');
    if (!config) return setError('Workspace limits are still loading. Please try again.');
    const validation = validatePdfFile(selected, sizeLimit); if (!validation.valid) { setError(validation.message); return; }
    const raw = await selected.arrayBuffer(); setBytes(raw);
    const encoded = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(selected); }); setDataUrl(encoded);
    try {
      const loaded = await pdfjs.getDocument({ data: raw.slice(0) }).promise; setDocument(loaded);
      const texts: string[] = [];
      for (let index = 1; index <= loaded.numPages; index++) { const pdfPage = await loaded.getPage(index); const content = await pdfPage.getTextContent(); texts.push(content.items.map((item: any) => item.str || '').join(' ')); }
      setPageText(texts);
      const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(`${selected.name}:${selected.size}:${selected.lastModified}`)); const key = Array.from(new Uint8Array(digest)).slice(0, 12).map(v => v.toString(16).padStart(2, '0')).join(''); setFingerprint(key);
      const registration = await fetch('/api/pdf/register-upload', { method: 'POST', headers: { 'Content-Type': 'application/json', ...(userId ? { Authorization: `Bearer ${userId}` } : {}) }, body: JSON.stringify({ name: selected.name, type: selected.type, size: selected.size, pages: loaded.numPages }) });
      const registrationData = await registration.json().catch(() => ({}));
      if (!registration.ok) openUpgrade(`${registrationData.error || 'This PDF exceeds your plan limits'} The selected PDF remains open.`);
      else setUsage(registrationData.usage);
      if (persistenceEligible) { const saved = await fetch(`/api/pdf-state/${key}`, { headers: { Authorization: `Bearer ${userId}` } }); if (saved.ok) { const payload = await saved.json(); if (payload.state) { setPage(Math.min(loaded.numPages, payload.state.page || 1)); setBookmarks(payload.state.bookmarks || []); setAnnotations(payload.state.annotations || []); setChat(payload.state.chat || []); } } }
    } catch { setDocument(null); setError('This PDF is damaged, encrypted, or could not be read.'); }
  };

  useEffect(() => { if (!query.trim()) { setMatches([]); return; } const found = pageText.map((text, index) => text.toLowerCase().includes(query.toLowerCase()) ? index + 1 : 0).filter(Boolean); setMatches(found); setMatchIndex(0); if (found[0]) setPage(found[0]); }, [query, pageText]);
  const moveMatch = (direction: number) => { if (!matches.length) return; const next = (matchIndex + direction + matches.length) % matches.length; setMatchIndex(next); setPage(matches[next]); };
  const canAnalyze = () => { if (!document || !dataUrl) return false; if (blocked) { openUpgrade(blocked); return false; } return true; };
  const analyze = async (action: typeof tool, prompt = '') => {
    if (!canAnalyze()) return; setLoading(action); setError('');
    try { const response = await fetch('/api/pdf/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json', ...(userId ? { Authorization: `Bearer ${userId}` } : {}) }, body: JSON.stringify({ action, dataUrl, pageText: pageText.map((text, index) => `[Page ${index + 1}] ${text}`).join('\n'), prompt, pageCount: document!.numPages, targetLanguage: language }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) { if ([403, 413, 429].includes(response.status)) openUpgrade(payload.error || 'This operation requires a higher plan.'); throw new Error(payload.error || 'The PDF operation failed.'); } if (action === 'summary') setSummary(payload.text); else if (action === 'chat') { const next = [...chat, { id: `${Date.now()}-u`, role: 'user' as const, text: prompt }, { id: `${Date.now()}-a`, role: 'assistant' as const, text: payload.text }]; setChat(next); setChatInput(''); } else setResult(payload.text); }
    catch (cause: any) { setError(cause?.message || 'The PDF provider is unavailable. Your file and input were preserved.'); } finally { setLoading(''); }
  };
  const runUtility = async (operation: 'rotate' | 'extract' | 'delete' | 'up' | 'down') => { if (!bytes || !document) return; const pdf = await PDFDocument.load(bytes.slice(0)); if (operation === 'rotate') pdf.getPages().forEach(p => p.setRotation(degrees((p.getRotation().angle + 90) % 360))); if (operation === 'delete') { if (pdf.getPageCount() === 1) return setError('A one-page PDF cannot have its only page deleted.'); pdf.removePage(page - 1); } if (operation === 'up' || operation === 'down') { const target = operation === 'up' ? page - 2 : page; if (target < 0 || target >= pdf.getPageCount()) return; const output = await PDFDocument.create(); const order = Array.from({ length: pdf.getPageCount() }, (_, i) => i); [order[page - 1], order[target]] = [order[target], order[page - 1]]; const copied = await output.copyPages(pdf, order); copied.forEach(p => output.addPage(p)); return download(await output.save(), `reordered-${file?.name}`); } if (operation === 'extract') { const output = await PDFDocument.create(); const [copied] = await output.copyPages(pdf, [page - 1]); output.addPage(copied); return download(await output.save(), `page-${page}-${file?.name}`); } download(await pdf.save(), `${operation}-${file?.name}`); };
  const merge = async (other: File | undefined) => { if (!other || !bytes) return; const validation = validatePdfFile(other, sizeLimit); if (!validation.valid) return setError(validation.message); const first = await PDFDocument.load(bytes.slice(0)), second = await PDFDocument.load(await other.arrayBuffer()), output = await PDFDocument.create(); for (const source of [first, second]) (await output.copyPages(source, source.getPageIndices())).forEach(p => output.addPage(p)); download(await output.save(), `merged-${file?.name}`); };

  if (!file) return <div className="flex h-full items-center justify-center bg-slate-50 p-5 dark:bg-zinc-950"><div className="w-full max-w-xl rounded-3xl border-2 border-dashed border-slate-300 bg-white p-10 text-center dark:border-zinc-700 dark:bg-zinc-900"><UploadCloud className="mx-auto h-10 w-10 text-teal-600" /><h1 className="mt-4 text-xl font-semibold">Upload a PDF</h1><p className="mt-2 text-sm text-slate-500">Choose a real PDF to open the viewer and document tools.</p><input ref={fileInput} hidden type="file" accept="application/pdf,.pdf" onChange={e => e.target.files?.[0] && loadFile(e.target.files[0])} /><button onClick={() => fileInput.current?.click()} className="mt-6 rounded-xl bg-teal-600 px-5 py-2.5 text-sm font-semibold text-white">Choose PDF</button>{config && <p className="mt-3 text-xs text-slate-400">Up to {sizeLimit} MB and {pageLimit} pages · {uploadLimit} free uploads daily</p>}</div></div>;

  return <div className="flex h-full min-h-0 flex-col bg-slate-100 dark:bg-zinc-950">
    <header className="flex min-h-14 flex-wrap items-center gap-2 border-b bg-white px-3 py-2 dark:border-zinc-800 dark:bg-zinc-900"><button onClick={() => { setFile(null); setDocument(null); }} className="rounded-lg p-2 hover:bg-slate-100 dark:hover:bg-zinc-800"><X className="h-4 w-4" /></button><FileText className="h-4 w-4 text-teal-600" /><span className="min-w-0 flex-1 truncate text-sm font-semibold">{file.name}</span>{document && <span className="text-xs text-slate-500">{document.numPages} pages</span>}<button onClick={() => setBookmarks(list => list.includes(page) ? list.filter(p => p !== page) : [...list, page])} className={`rounded-lg p-2 ${bookmarks.includes(page) ? 'text-amber-500' : ''}`} title="Bookmark page"><Bookmark className="h-4 w-4" /></button></header>
    <nav className="grid grid-cols-3 border-b bg-white md:hidden dark:border-zinc-800 dark:bg-zinc-900">{(['viewer', 'chat', 'summary'] as MobileTab[]).map(tab => <button key={tab} onClick={() => { setMobileTab(tab); if (tab !== 'viewer') setTool(tab); }} className={`py-2 text-xs font-semibold capitalize ${mobileTab === tab ? 'border-b-2 border-teal-500 text-teal-600' : ''}`}>{tab}</button>)}</nav>
    {(error || blocked) && <div className={`mx-3 mt-2 rounded-lg px-3 py-2 text-xs ${blocked ? 'bg-amber-50 text-amber-800 dark:bg-amber-950/30 dark:text-amber-300' : 'bg-red-50 text-red-700 dark:bg-red-950/30 dark:text-red-300'}`}>{blocked || error}</div>}
    <div className="flex min-h-0 flex-1">
      <aside className="hidden w-28 shrink-0 overflow-y-auto border-r bg-white p-2 md:block dark:border-zinc-800 dark:bg-zinc-900">{document && Array.from({ length: document.numPages }, (_, i) => <div key={i} className="mb-2"><Thumbnail document={document} page={i + 1} active={page === i + 1} onClick={() => setPage(i + 1)} /></div>)}</aside>
      <section className={`${mobileTab === 'viewer' ? 'flex' : 'hidden'} min-w-0 flex-1 flex-col md:flex`}>
        <div className="flex flex-wrap items-center justify-center gap-1 border-b bg-white p-2 dark:border-zinc-800 dark:bg-zinc-900"><button onClick={() => setPage(p => Math.max(1, p - 1))} className="p-2"><ChevronLeft className="h-4 w-4" /></button><input aria-label="Current page" value={page} onChange={e => setPage(Math.min(document?.numPages || 1, Math.max(1, Number(e.target.value))))} className="w-12 rounded border px-2 py-1 text-center text-xs dark:border-zinc-700 dark:bg-zinc-800" /><span className="text-xs">/ {document?.numPages || 0}</span><button onClick={() => setPage(p => Math.min(document?.numPages || 1, p + 1))} className="p-2"><ChevronRight className="h-4 w-4" /></button><button onClick={() => setZoom(z => Math.max(50, z - 10))} className="p-2"><Minus className="h-4 w-4" /></button><span className="text-xs">{zoom}%</span><button onClick={() => setZoom(z => Math.min(200, z + 10))} className="p-2"><Plus className="h-4 w-4" /></button><button onClick={() => setRotation(r => (r + 90) % 360)} className="p-2" title="Rotate view"><RotateCw className="h-4 w-4" /></button><div className="relative ml-1 flex items-center"><Search className="absolute left-2 h-3.5 w-3.5 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search" className="w-32 rounded-lg border py-1.5 pl-7 pr-2 text-xs dark:border-zinc-700 dark:bg-zinc-800" />{matches.length > 0 && <><span className="ml-1 text-[10px]">{matchIndex + 1}/{matches.length}</span><button onClick={() => moveMatch(-1)}><ChevronUp className="h-3.5 w-3.5" /></button><button onClick={() => moveMatch(1)}><ChevronDown className="h-3.5 w-3.5" /></button></>}</div></div>
        <div className="flex-1 overflow-auto p-5"><div className="mx-auto w-max">{document ? <PageCanvas document={document} page={page} zoom={zoom} rotation={rotation} /> : <Loader2 className="m-10 h-8 w-8 animate-spin" />}</div></div>
        <div className="border-t bg-white p-2 text-xs dark:border-zinc-800 dark:bg-zinc-900"><div className="flex flex-wrap gap-2"><input value={note} onChange={e => setNote(e.target.value)} placeholder={`Add note to page ${page}`} className="min-w-40 flex-1 rounded-lg border px-3 py-1.5 dark:border-zinc-700 dark:bg-zinc-800" /><button disabled={!persistenceEligible || !note.trim()} onClick={() => { setAnnotations(list => [...list, { id: `${Date.now()}`, page, text: note.trim() }]); setNote(''); }} className="rounded-lg bg-slate-800 px-3 text-white disabled:opacity-40">Add note</button></div>{!persistenceEligible && <p className="mt-1 text-[10px] text-slate-400">Sign in with an eligible plan to save notes, bookmarks, chat and reading position.</p>}{annotations.filter(a => a.page === page).map(a => <div key={a.id} className="mt-1 flex justify-between rounded bg-amber-50 p-2 text-amber-900"><span>{a.text}</span><button onClick={() => setAnnotations(list => list.filter(item => item.id !== a.id))}><Trash2 className="h-3.5 w-3.5" /></button></div>)}</div>
      </section>
      <aside className={`${mobileTab === 'viewer' ? 'hidden' : 'flex'} w-full flex-col border-l bg-white md:flex md:w-96 dark:border-zinc-800 dark:bg-zinc-900`}>
        <div className="hidden grid-cols-5 border-b md:grid dark:border-zinc-800">{([['chat', MessageSquare], ['summary', FileText], ['ocr', Check], ['tables', Table], ['translate', Languages]] as const).map(([name, Icon]) => <button key={name} title={name} onClick={() => setTool(name)} className={`flex justify-center p-3 ${tool === name ? 'border-b-2 border-teal-500 text-teal-600' : ''}`}><Icon className="h-4 w-4" /></button>)}</div>
        <div className="flex-1 overflow-y-auto p-4">{(mobileTab === 'summary' || tool === 'summary') && <div><h2 className="font-semibold">PDF Summary</h2><button disabled={Boolean(loading)} onClick={() => analyze('summary')} className="mt-3 rounded-lg bg-teal-600 px-3 py-2 text-xs font-semibold text-white">{loading === 'summary' ? 'Summarizing…' : summary ? 'Regenerate summary' : 'Generate summary'}</button><pre className="mt-4 whitespace-pre-wrap font-sans text-sm leading-6">{summary || 'No summary generated.'}</pre></div>}{mobileTab !== 'summary' && tool === 'chat' && <div className="flex h-full flex-col"><h2 className="font-semibold">PDF Chat</h2><div className="flex-1 py-3">{!chat.length && <p className="text-sm text-slate-500">Ask a question about this PDF. Answers include page references when supported by the document.</p>}{chat.map(message => <div key={message.id} className={`mb-3 rounded-xl p-3 text-sm ${message.role === 'user' ? 'ml-8 bg-slate-100 dark:bg-zinc-800' : 'bg-teal-50 dark:bg-teal-950/20'}`}><pre className="whitespace-pre-wrap font-sans">{message.text}</pre></div>)}</div><div className="flex gap-2"><textarea value={chatInput} onChange={e => setChatInput(e.target.value)} placeholder="Ask about the PDF" className="min-h-16 flex-1 resize-none rounded-xl border p-2 text-sm dark:border-zinc-700 dark:bg-zinc-800" /><button disabled={!chatInput.trim() || Boolean(loading)} onClick={() => analyze('chat', chatInput)} className="self-end rounded-lg bg-teal-600 p-2 text-white"><Send className="h-4 w-4" /></button></div></div>}{mobileTab !== 'summary' && ['ocr', 'tables', 'translate'].includes(tool) && <div><h2 className="font-semibold capitalize">{tool === 'ocr' ? 'OCR scanned PDF' : tool === 'tables' ? 'Table extraction' : 'Translate PDF'}</h2>{tool === 'translate' && <select value={language} onChange={e => setLanguage(e.target.value)} className="mt-3 rounded-lg border p-2 text-sm dark:border-zinc-700 dark:bg-zinc-800"><option>Hindi</option><option>English</option><option>Spanish</option><option>French</option><option>German</option></select>}<button disabled={Boolean(loading)} onClick={() => analyze(tool)} className="mt-3 block rounded-lg bg-teal-600 px-3 py-2 text-xs font-semibold text-white">{loading === tool ? 'Processing…' : 'Run'}</button><pre className="mt-4 whitespace-pre-wrap font-sans text-sm leading-6">{result || 'No result yet.'}</pre></div>}</div>
        <div className="border-t p-3 dark:border-zinc-800"><p className="mb-2 text-[10px] font-semibold uppercase tracking-wide text-slate-400">Implemented PDF tools</p><div className="grid grid-cols-3 gap-1"><button onClick={() => runUtility('rotate')} className="rounded border p-2 text-xs dark:border-zinc-700">Rotate file</button><button onClick={() => runUtility('extract')} className="rounded border p-2 text-xs dark:border-zinc-700">Extract page</button><button onClick={() => runUtility('delete')} className="rounded border p-2 text-xs dark:border-zinc-700">Delete page</button><button onClick={() => runUtility('up')} className="rounded border p-2 text-xs dark:border-zinc-700">Move up</button><button onClick={() => runUtility('down')} className="rounded border p-2 text-xs dark:border-zinc-700">Move down</button><input ref={mergeInput} hidden type="file" accept="application/pdf,.pdf" onChange={e => { merge(e.target.files?.[0]); e.target.value = ''; }} /><button onClick={() => mergeInput.current?.click()} className="rounded border p-2 text-xs dark:border-zinc-700">Merge PDF</button></div></div>
      </aside>
    </div>
  </div>;
}
