import React, { useEffect, useState } from 'react';
import { AlertCircle, Check, Loader2, RefreshCw, ShieldCheck } from 'lucide-react';
import { fetchSystemConfig, SystemConfig } from '../../utils/limits';

declare global { interface Window { Razorpay?: new (options: any) => { open: () => void; on: (event: string, callback: (data: any) => void) => void } } }
type CheckoutState = 'idle' | 'ready' | 'creating' | 'payment' | 'verifying' | 'success' | 'failure';
interface Props { currentUser?: any; onAuthRequired?: (mode: 'login' | 'register') => void; onSubscriptionActivated?: (user: any) => void }

const formatLimit = (value: number, suffix = '') => value < 0 ? 'Unlimited' : `${value.toLocaleString('en-IN')}${suffix}`;
const loadRazorpay = () => new Promise<boolean>(resolve => { if (window.Razorpay) return resolve(true); const script = document.createElement('script'); script.src = 'https://checkout.razorpay.com/v1/checkout.js'; script.onload = () => resolve(true); script.onerror = () => resolve(false); document.head.appendChild(script); });

export default function Pricing({ currentUser, onAuthRequired, onSubscriptionActivated }: Props) {
  const [config, setConfig] = useState<SystemConfig | null>(null), [selected, setSelected] = useState(''), [coupon, setCoupon] = useState('');
  const [state, setState] = useState<CheckoutState>('idle'), [message, setMessage] = useState(''), [pendingVerification, setPendingVerification] = useState<any>(null);
  const userId = currentUser?.email || currentUser?.id || '', guest = !userId || currentUser?.guest;
  useEffect(() => { fetchSystemConfig().then(setConfig); const pending = sessionStorage.getItem('gxa_pending_plan'); if (pending) { setSelected(pending); setState('ready'); } }, []);
  const plans = config?.plans ? Object.entries(config.plans) : [];
  const selectPlan = (id: string) => { const plan = config?.plans?.[id]; if (!plan) return; if (plan.billing === 'contact' || plan.billing === 'custom') { window.location.href = `mailto:sales@gxatechnology.com?subject=${encodeURIComponent(`${plan.name} plan enquiry`)}`; return; } if (id === 'free') return; sessionStorage.setItem('gxa_pending_plan', id); setSelected(id); setState('ready'); setMessage(''); if (guest) onAuthRequired?.('login'); };
  const verify = async (payload = pendingVerification) => { if (!payload || !userId) return; setState('verifying'); setMessage('Confirming payment securely with Razorpay…'); try { const response = await fetch('/api/billing/verify', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${userId}` }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Payment verification failed.'); sessionStorage.removeItem('gxa_pending_plan'); setPendingVerification(null); setState('success'); setMessage('Payment verified. Your subscription is active.'); onSubscriptionActivated?.(data.user); } catch (cause: any) { setState('failure'); setMessage(cause?.message || 'Verification failed. You can retry safely.'); } };
  const checkout = async () => { if (!selected || !config?.plans?.[selected]) return; if (guest) { sessionStorage.setItem('gxa_pending_plan', selected); onAuthRequired?.('login'); return; } setState('creating'); setMessage('Creating a secure INR payment order…'); try { const response = await fetch('/api/billing/orders', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${userId}` }, body: JSON.stringify({ planId: selected, couponCode: coupon }) }); const order = await response.json().catch(() => ({})); if (!response.ok) throw new Error(order.error || 'Could not create payment order.'); if (!(await loadRazorpay()) || !window.Razorpay) throw new Error('Razorpay Checkout could not be loaded.'); setState('payment'); setMessage('Complete payment in the secure Razorpay window.'); const instance = new window.Razorpay({ key: order.keyId, order_id: order.orderId, amount: order.amount, currency: order.currency, name: 'GXA AI Workspace', description: `${order.planName} monthly subscription`, prefill: { name: currentUser?.name, email: currentUser?.email }, theme: { color: '#0d9488' }, handler: (payload: any) => { setPendingVerification(payload); verify(payload); }, modal: { ondismiss: () => { setState('failure'); setMessage('Payment was cancelled. Your selected plan is preserved.'); } } }); instance.on('payment.failed', (event: any) => { setState('failure'); setMessage(event?.error?.description || 'Payment failed. Please retry.'); }); instance.open(); } catch (cause: any) { setState('failure'); setMessage(cause?.message || 'Payment could not start.'); } };

  if (!config) return <div className="flex h-full items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-teal-600" /></div>;
  return <div className="mx-auto max-w-7xl space-y-8 pb-12"><div className="text-center"><h1 className="text-3xl font-bold">Plans that grow with your work</h1><p className="mt-2 text-sm text-slate-500">View and select a plan without signing in. Payment begins only after authentication.</p></div>
    {message && <div className={`mx-auto flex max-w-2xl items-center gap-3 rounded-xl border p-3 text-sm ${state === 'success' ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : state === 'failure' ? 'border-red-200 bg-red-50 text-red-800' : 'border-teal-200 bg-teal-50 text-teal-800'}`}>{state === 'verifying' || state === 'creating' ? <Loader2 className="h-4 w-4 animate-spin" /> : state === 'success' ? <ShieldCheck className="h-4 w-4" /> : <AlertCircle className="h-4 w-4" />}<span className="flex-1">{message}</span>{state === 'failure' && <button onClick={() => pendingVerification ? verify() : checkout()} className="flex items-center gap-1 rounded-lg bg-white px-3 py-1.5 text-xs font-semibold"><RefreshCw className="h-3.5 w-3.5" /> Retry</button>}</div>}
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{plans.map(([id, plan]) => <article key={id} className={`flex flex-col rounded-2xl border bg-white p-5 dark:bg-zinc-900 ${selected === id ? 'border-teal-500 ring-2 ring-teal-500/20' : 'dark:border-zinc-800'}`}><h2 className="font-semibold">{plan.name}</h2><div className="mt-3 min-h-12">{plan.monthlyPrice !== null ? <><span className="text-3xl font-bold">{new Intl.NumberFormat('en-IN', { style: 'currency', currency: config.pricing_currency || 'INR', maximumFractionDigits: 0 }).format(plan.monthlyPrice)}</span><span className="text-xs text-slate-500">/month</span></> : <span className="text-xl font-bold">{plan.priceLabel}</span>}</div><ul className="my-5 flex-1 space-y-2">{plan.features.map(feature => <li key={feature} className="flex gap-2 text-xs text-slate-600 dark:text-zinc-300"><Check className="h-3.5 w-3.5 shrink-0 text-teal-600" />{feature}</li>)}</ul><button onClick={() => selectPlan(id)} disabled={id === currentUser?.subscription || id === 'free'} className="rounded-xl bg-teal-600 px-3 py-2.5 text-xs font-semibold text-white disabled:bg-slate-200 disabled:text-slate-500">{id === currentUser?.subscription ? 'Current plan' : id === 'free' ? 'Free workspace' : plan.monthlyPrice === null ? plan.priceLabel : guest ? 'Select plan' : 'Continue to checkout'}</button></article>)}</div>
    {selected && config.plans?.[selected]?.monthlyPrice !== null && state !== 'success' && <section className="mx-auto max-w-xl rounded-2xl border bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h2 className="font-semibold">Selected: {config.plans[selected].name}</h2><p className="mt-1 text-xs text-slate-500">Your selection is preserved through login or registration.</p><div className="mt-4 flex gap-2"><input value={coupon} onChange={e => setCoupon(e.target.value)} placeholder="Coupon code" className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-950" /><button onClick={checkout} disabled={['creating', 'payment', 'verifying'].includes(state)} className="rounded-lg bg-teal-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{guest ? 'Login to pay' : 'Pay securely'}</button></div></section>}
    <section className="overflow-x-auto rounded-2xl border bg-white dark:border-zinc-800 dark:bg-zinc-900"><table className="min-w-[850px] w-full text-sm"><thead><tr className="border-b dark:border-zinc-800"><th className="p-3 text-left">Plan limits</th>{plans.map(([id, plan]) => <th key={id} className="p-3 text-center">{plan.name}</th>)}</tr></thead><tbody>{([['Words per request', 'words', ''], ['Requests', 'requests', ''], ['PDF uploads', 'pdfUploads', ''], ['PDF size', 'pdfSizeMb', ' MB'], ['PDF pages', 'pdfPages', ''], ['OCR pages', 'ocrPages', ''], ['Storage', 'storageMb', ' MB'], ['History', 'historyDays', ' days']] as const).map(([label, key, suffix]) => <tr key={key} className="border-b last:border-0 dark:border-zinc-800"><td className="p-3 font-medium">{label}</td>{plans.map(([id, plan]) => <td key={id} className="p-3 text-center text-slate-600 dark:text-zinc-300">{formatLimit(plan.limits[key], suffix)}</td>)}</tr>)}</tbody></table></section>
  </div>;
}
