import React, { useEffect, useRef, useState } from 'react';
import { Camera, Loader2, MailCheck, Save } from 'lucide-react';
import { authenticatedFetch } from '../../utils/auth';

const empty = { name: '', email: '', avatar: '', phone: '', company: '', timezone: 'Asia/Kolkata', language: 'English' };
export default function Profile({ currentUser }: { currentUser: any }) {
  const [form, setForm] = useState<any>(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const fileRef = useRef<HTMLInputElement>(null);
  useEffect(() => { authenticatedFetch(currentUser, '/api/account/profile').then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setForm({ ...empty, ...body.user }); }).catch(reason => setError(reason.message || 'Profile could not be loaded.')).finally(() => setLoading(false)); }, [currentUser?.id]);
  const change = (key: string, value: string) => { setForm((current: any) => ({ ...current, [key]: value })); setMessage(''); setError(''); };
  const chooseAvatar = (file?: File) => { if (!file) return; if (!['image/png', 'image/jpeg', 'image/webp'].includes(file.type) || file.size > 250 * 1024) { setError('Choose a PNG, JPEG, or WebP image under 250 KB.'); return; } const reader = new FileReader(); reader.onload = () => change('avatar', String(reader.result || '')); reader.readAsDataURL(file); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const response = await authenticatedFetch(currentUser, '/api/account/profile', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Profile could not be saved.'); setForm({ ...empty, ...body.user }); localStorage.setItem('gxa_user', JSON.stringify(body.user)); window.dispatchEvent(new CustomEvent('gxa:profile-updated', { detail: body.user })); setMessage('Profile saved.'); } catch (reason: any) { setError(`${reason.message} Your previous profile is unchanged.`); } finally { setSaving(false); } };
  const requestVerification = async () => { setSaving(true); setError(''); try { const response = await authenticatedFetch(currentUser, '/api/auth/email-verification/request', { method: 'POST' }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || 'Verification could not be requested.'); setMessage(body.alreadyVerified ? 'Your email is already verified.' : 'Verification email requested. Check your inbox if email delivery is configured.'); } catch (reason: any) { setError(reason.message); } finally { setSaving(false); } };
  if (loading) return <div className="flex min-h-80 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-teal-500" aria-label="Loading profile" /></div>;
  return <section className="mx-auto max-w-3xl"><div className="mb-6"><h1 className="text-2xl font-black">My Profile</h1><p className="mt-1 text-sm text-slate-500">Your account details are saved to your private workspace.</p></div><form onSubmit={save} className="space-y-6 rounded-2xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900 sm:p-7">
    <div className="flex items-center gap-4"><button type="button" onClick={() => fileRef.current?.click()} className="relative flex h-20 w-20 items-center justify-center overflow-hidden rounded-full bg-slate-100 text-xl font-black dark:bg-zinc-800" aria-label="Choose profile picture">{form.avatar ? <img src={form.avatar} alt="Profile" className="h-full w-full object-cover" /> : (form.name || form.email || '?').charAt(0).toUpperCase()}<span className="absolute bottom-0 right-0 rounded-full bg-teal-600 p-1.5 text-white"><Camera className="h-3.5 w-3.5" /></span></button><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={event => chooseAvatar(event.target.files?.[0])} /><div><strong>Profile picture</strong><p className="text-xs text-slate-400">PNG, JPEG or WebP · up to 250 KB</p>{form.avatar && <button type="button" onClick={() => change('avatar', '')} className="mt-1 text-xs font-bold text-rose-600">Remove</button>}</div></div>
    {error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-950/30 dark:text-rose-300">{error}</p>}{message && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300">{message}</p>}
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Name" required value={form.name} onChange={(v: string) => change('name', v)} /><Field label="Email" required type="email" value={form.email} onChange={(v: string) => change('email', v)} /><Field label="Phone" type="tel" value={form.phone} onChange={(v: string) => change('phone', v)} /><Field label="Company" value={form.company} onChange={(v: string) => change('company', v)} /><Field label="Timezone" value={form.timezone} onChange={(v: string) => change('timezone', v)} /><Field label="Language" value={form.language} onChange={(v: string) => change('language', v)} /></div>
    <div className="flex flex-wrap gap-3"><button disabled={saving} className="theme-primary-action inline-flex items-center gap-2 rounded-xl px-5 py-2.5 text-sm font-black disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Save profile</button>{!form.emailVerified && <button type="button" disabled={saving} onClick={requestVerification} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-5 py-2.5 text-sm font-black disabled:opacity-50 dark:border-zinc-700"><MailCheck className="h-4 w-4" />Verify email</button>} {form.emailVerified && <span className="inline-flex items-center gap-2 text-sm font-bold text-emerald-600"><MailCheck className="h-4 w-4" />Email verified</span>}</div>
  </form></section>;
}
function Field({ label, value, onChange, type = 'text', required = false }: any) { const id = `profile-${label.toLowerCase()}`; return <label htmlFor={id} className="space-y-1.5 text-xs font-bold text-slate-600 dark:text-zinc-300"><span>{label}{required ? ' *' : ''}</span><input id={id} type={type} required={required} value={value || ''} onChange={event => onChange(event.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-normal text-slate-900 outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-500/20 dark:border-zinc-700 dark:bg-zinc-950 dark:text-white" /></label>; }
