import React, { useEffect, useState } from 'react';
import { FileText, FolderKanban, Loader2, RefreshCw, RotateCcw, Trash2 } from 'lucide-react';
import { authenticatedFetch } from '../../utils/auth';

export default function ResourceView({ currentUser, title, description, endpoint, trash = false }: { currentUser: any; title: string; description: string; endpoint: string; trash?: boolean }) {
  const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = () => { setLoading(true); setError(''); authenticatedFetch(currentUser, endpoint).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error || 'The page could not be loaded.'); setItems(body.items || []); }).catch(reason => setError(`${reason.message} Your saved data was not changed.`)).finally(() => setLoading(false)); };
  useEffect(load, [currentUser?.id, endpoint]);
  const mutate = async (item: any, permanent = false) => { const url = permanent ? `/api/trash/${item.kind}/${item.id}` : `/api/trash/${item.kind}/${item.id}/restore`; const response = await authenticatedFetch(currentUser, url, { method: permanent ? 'DELETE' : 'POST' }); const body = await response.json().catch(() => ({})); if (!response.ok) { setError(body.error || 'The action could not be completed.'); return; } setItems(current => current.filter(candidate => candidate.id !== item.id)); };
  return <section className="mx-auto max-w-5xl space-y-5"><header><h1 className="text-2xl font-black">{title}</h1><p className="mt-1 text-sm text-slate-500">{description}</p></header>{error && <div role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-950/30 dark:text-rose-300">{error}<button onClick={load} className="ml-3 inline-flex items-center gap-1 font-bold"><RefreshCw className="h-3.5 w-3.5" />Retry</button></div>}{loading ? <div className="flex min-h-60 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-teal-500" /></div> : items.length ? <ul className="grid gap-3 sm:grid-cols-2">{items.map(item => <li key={`${item.kind}-${item.id}`} className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><div className="flex gap-3">{item.kind === 'project' ? <FolderKanban className="h-5 w-5 text-teal-500" /> : <FileText className="h-5 w-5 text-teal-500" />}<div className="min-w-0"><strong className="block truncate capitalize">{item.name || item.title || item.tool || 'Saved item'}</strong><p className="mt-1 text-xs capitalize text-slate-400">{item.kind}{item.status ? ` · ${item.status}` : ''}{item.collection ? ` · ${item.collection}` : ''}</p><p className="mt-1 text-[10px] text-slate-400">{new Date(item.deletedAt || item.updatedAt || item.createdAt).toLocaleString()}</p></div></div>{trash && <div className="mt-4 flex gap-2"><button onClick={() => mutate(item)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold dark:border-zinc-700"><RotateCcw className="h-3.5 w-3.5" />Restore</button><button onClick={() => { if (window.confirm(`Permanently delete ${item.name || 'this item'}?`)) void mutate(item, true); }} className="inline-flex items-center gap-1 rounded-lg px-3 py-2 text-xs font-bold text-rose-600"><Trash2 className="h-3.5 w-3.5" />Delete forever</button></div>}</li>)}</ul> : <div className="rounded-2xl border border-dashed border-slate-300 p-12 text-center text-sm text-slate-400 dark:border-zinc-700">Nothing here yet.</div>}</section>;
}
