import React, { DragEvent, useMemo, useRef, useState } from 'react';
import { ArrowRight, FileText, FolderOpen, MessageSquare, MoreHorizontal, Paperclip, PenLine, Repeat2, Search, ShieldCheck, Sparkles, Upload, WandSparkles } from 'lucide-react';
import { registryCategories, toolRegistry } from '../../toolRegistry';
import { WorkspaceId } from '../../types';

interface Props { sharedText: string; setSharedText: (value: string) => void; onSelectWorkspace: (route: WorkspaceId) => void; onOpenTools: () => void; isAuthenticated: boolean }
const icons: Record<string, React.ComponentType<{ className?: string }>> = { repeat: Repeat2, check: ShieldCheck, chat: MessageSquare, pen: PenLine, summary: FileText, languages: Sparkles, file: FolderOpen };

export default function UniversalHome({ sharedText, setSharedText, onSelectWorkspace, onOpenTools, isAuthenticated }: Props) {
  const inputRef = useRef<HTMLTextAreaElement>(null), fileRef = useRef<HTMLInputElement>(null);
  const [fileMessage, setFileMessage] = useState('Text and Markdown files can be loaded here. Open PDF Intelligence or OCR for document and image uploads.');
  const quickRoutes: WorkspaceId[] = ['ai-writing', 'ai-chat', 'paraphrasing', 'grammar', 'summarizer', 'ai-humanizer', 'ai-detection'];
  const popular = useMemo(() => toolRegistry.filter(tool => tool.primary && (isAuthenticated || tool.guestAccess)).slice(0, 8), [isAuthenticated]);
  const launch = (route: WorkspaceId) => onSelectWorkspace(route);
  const loadTextFile = async (file?: File) => { if (!file) return; if (!/\.(txt|md|csv)$/i.test(file.name) || file.size > 2 * 1024 * 1024) { setFileMessage('This Home input accepts TXT, MD or CSV files up to 2 MB. Use the relevant document workspace for other formats.'); return; } setSharedText(await file.text()); setFileMessage(`${file.name} loaded. Choose a tool to continue.`); inputRef.current?.focus(); };
  const drop = (event: DragEvent) => { event.preventDefault(); loadTextFile(event.dataTransfer.files[0]); };
  return <section className="mx-auto max-w-7xl space-y-12 pb-16 text-slate-900 dark:text-white">
    <div className="relative overflow-hidden rounded-[2rem] bg-slate-950 px-5 py-10 text-white shadow-2xl shadow-slate-950/15 sm:px-10 sm:py-14 lg:px-16"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(20,184,166,.28),transparent_38%),radial-gradient(circle_at_bottom_left,rgba(59,130,246,.18),transparent_38%)]" /><div className="relative mx-auto max-w-4xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-bold text-teal-200"><WandSparkles className="h-4 w-4" /> GXA universal workspace</span><h1 className="mt-5 text-3xl font-black tracking-tight sm:text-5xl">Everything You Need to Create, Write and Work Smarter with AI</h1><p className="mx-auto mt-4 max-w-3xl text-sm leading-6 text-slate-300 sm:text-base">Write, rewrite, analyze documents, create professional content and manage complete AI-powered projects from one intelligent workspace.</p>
      <div onDragOver={event => event.preventDefault()} onDrop={drop} className="mt-8 rounded-3xl bg-white p-3 text-left text-slate-900 shadow-2xl ring-1 ring-white/20"><textarea ref={inputRef} value={sharedText} onChange={event => setSharedText(event.target.value)} placeholder="Write, paste, upload or describe what you need..." aria-label="Universal AI input" className="min-h-36 w-full resize-none rounded-2xl p-4 text-base outline-none placeholder:text-slate-400 focus:ring-2 focus:ring-teal-500" /><div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 px-2 pt-3"><div className="flex items-center gap-2"><input ref={fileRef} type="file" accept=".txt,.md,.csv,text/plain,text/markdown,text/csv" className="hidden" onChange={event => loadTextFile(event.target.files?.[0])} /><button onClick={() => fileRef.current?.click()} className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-xs font-bold text-slate-600 hover:bg-slate-100 focus-visible:ring-2 focus-visible:ring-teal-500"><Paperclip className="h-4 w-4" /> Upload text</button><span className="text-xs text-slate-400">{sharedText.trim().split(/\s+/).filter(Boolean).length} words</span></div><button onClick={() => launch('ai-chat')} className="inline-flex items-center gap-2 rounded-xl bg-teal-500 px-4 py-2.5 text-xs font-black text-white hover:bg-teal-600">Ask GXA AI <ArrowRight className="h-4 w-4" /></button></div></div><p className="mt-3 text-xs text-slate-400" role="status">{fileMessage}</p>
      <div className="mt-5 flex gap-2 overflow-x-auto pb-2">{quickRoutes.map(route => { const tool = toolRegistry.find(item => item.route === route)!; return <button key={route} onClick={() => launch(route)} className="shrink-0 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-bold text-white transition hover:bg-white/20">{tool.name}</button>; })}<button onClick={onOpenTools} className="shrink-0 rounded-full border border-teal-300/40 bg-teal-400/15 px-4 py-2 text-xs font-black text-teal-100">More</button></div></div></div>
    <div><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-teal-600">Start here</p><h2 className="mt-2 text-2xl font-black">Popular tools</h2></div><button onClick={onOpenTools} className="hidden items-center gap-2 text-sm font-bold text-teal-600 sm:flex"><Search className="h-4 w-4" /> Search all tools</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{popular.map(tool => { const Icon = icons[tool.icon] || Sparkles; return <button key={tool.id} onClick={() => launch(tool.route)} className="rounded-2xl border border-slate-200 bg-white p-5 text-left transition hover:-translate-y-1 hover:border-teal-300 hover:shadow-xl dark:border-zinc-800 dark:bg-zinc-900"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-teal-50 text-teal-600 dark:bg-teal-950"><Icon className="h-5 w-5" /></span><h3 className="mt-4 font-black">{tool.name}</h3><p className="mt-1 text-xs leading-5 text-slate-500 dark:text-zinc-400">{tool.description}</p></button>; })}</div></div>
    <div><p className="text-xs font-black uppercase tracking-[.2em] text-teal-600">Discover</p><h2 className="mt-2 text-2xl font-black">Browse by category</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{registryCategories.map(category => { const count = toolRegistry.filter(tool => tool.more && tool.category === category && (isAuthenticated || tool.guestAccess)).length; if (!count) return null; return <button key={category} onClick={onOpenTools} className="flex items-center justify-between rounded-2xl bg-slate-100 p-4 text-left hover:bg-teal-50 dark:bg-zinc-900 dark:hover:bg-teal-950"><span><strong className="block text-sm">{category}</strong><span className="text-xs text-slate-500">{count} available tools</span></span><ArrowRight className="h-4 w-4 text-slate-400" /></button>; })}</div></div>
    {isAuthenticated && <div className="grid gap-4 md:grid-cols-2"><div className="rounded-3xl border border-dashed border-slate-300 p-7 dark:border-zinc-700"><h2 className="font-black">Continue working</h2><p className="mt-2 text-sm text-slate-500">Your saved projects and documents will appear here when available.</p><button onClick={() => launch('projects')} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-teal-600">Open Projects <ArrowRight className="h-4 w-4" /></button></div><div className="rounded-3xl border border-dashed border-slate-300 p-7 dark:border-zinc-700"><h2 className="font-black">Recently used</h2><p className="mt-2 text-sm text-slate-500">No recent authenticated activity yet.</p></div></div>}
    <div className="rounded-3xl bg-teal-50 p-7 dark:bg-teal-950/30"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="font-black">Templates and guided workflows</h2><p className="mt-1 text-sm text-slate-600 dark:text-zinc-400">Start with an existing GXA template without creating a fake document.</p></div><button onClick={() => launch('templates')} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-xs font-black text-white dark:bg-white dark:text-slate-950"><Upload className="h-4 w-4" /> Browse templates</button></div></div>
  </section>;
}
