import React, { useEffect, useState } from 'react';
import { ArrowRight, CalendarDays, FileText, FolderKanban, Loader2, Sparkles } from 'lucide-react';
import { WorkspaceId } from '../../types';
import { authenticatedFetch } from '../../utils/auth';

const date = (value?: string | null) => value ? new Date(value).toLocaleDateString(undefined, { dateStyle: 'medium' }) : 'Not scheduled';

export default function UserDashboard({ currentUser, onSelectWorkspace }: { currentUser: any; onSelectWorkspace: (id: WorkspaceId) => void }) {
  const [data, setData] = useState<any>(null); const [error, setError] = useState('');
  useEffect(() => { let active = true; authenticatedFetch(currentUser, '/api/dashboard').then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Dashboard could not be loaded.'); if (active) setData(body); }).catch(reason => { if (active) setError(reason.message); }); return () => { active = false; }; }, [currentUser?.id]);
  if (error) return <State title="Dashboard unavailable" text={`${error} Your saved work remains safe.`} action={() => window.location.reload()} actionLabel="Try again" />;
  if (!data) return <div className="flex min-h-80 items-center justify-center" aria-live="polite"><Loader2 className="h-6 w-6 animate-spin text-teal-500" /><span className="ml-2 text-sm text-slate-500">Loading your workspace…</span></div>;
  const plan = data.plan; const planName = plan.plan?.displayName || 'Free';
  return <section className="mx-auto max-w-6xl space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-teal-600">Personal Workspace</p><h1 className="mt-1 text-2xl font-black text-slate-900 dark:text-white">Welcome, {data.user.name || 'there'}</h1><p className="mt-1 text-sm text-slate-500 dark:text-zinc-400">Continue your saved work from any signed-in session.</p></div><button onClick={() => onSelectWorkspace('home')} className="theme-primary-action inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black">Create new <ArrowRight className="h-4 w-4" /></button></div>
    <article className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Current plan</p><h2 className="mt-1 text-xl font-black">{planName}</h2><span className="mt-2 inline-flex rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold capitalize text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300">{plan.subscriptionStatus}</span></div><dl className="grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-slate-400">Activation date</dt><dd className="mt-1 font-bold">{date(plan.activationDate)}</dd></div><div><dt className="text-slate-400">Renewal / expiry</dt><dd className="mt-1 font-bold">{date(plan.currentPeriodEnd)}</dd></div></dl><button onClick={() => onSelectWorkspace(plan.currentPlanKey === 'free' ? 'pricing' : 'billing')} className="rounded-xl border border-teal-500 px-4 py-2 text-sm font-black text-teal-700 dark:text-teal-300">{plan.currentPlanKey === 'free' ? 'Upgrade' : 'Manage plan'}</button></div></article>
    <div className="grid gap-5 lg:grid-cols-3"><Recent title="Recent projects" icon={FolderKanban} items={data.recentProjects} empty="No projects yet." onOpen={() => onSelectWorkspace('projects')} render={(item: any) => item.name} /><Recent title="Recent documents" icon={FileText} items={data.recentDocuments} empty="No saved documents yet." onOpen={() => onSelectWorkspace('documents')} render={(item: any) => item.name} /><Recent title="Recent AI history" icon={Sparkles} items={data.recentAIHistory} empty="No AI history yet." onOpen={() => onSelectWorkspace('history')} render={(item: any) => `${String(item.tool || 'AI').replaceAll('_', ' ')} · ${item.status}`} /></div>
  </section>;
}

function Recent({ title, icon: Icon, items, empty, onOpen, render }: any) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-black"><Icon className="h-4 w-4 text-teal-500" />{title}</h2><button onClick={onOpen} className="text-xs font-bold text-teal-600">View all</button></div>{items?.length ? <ul className="space-y-2">{items.map((item: any) => <li key={item.id} className="rounded-xl bg-slate-50 p-3 text-xs dark:bg-zinc-950"><strong className="block truncate capitalize">{render(item)}</strong><span className="mt-1 flex items-center gap-1 text-slate-400"><CalendarDays className="h-3 w-3" />{date(item.updatedAt || item.createdAt)}</span></li>)}</ul> : <p className="rounded-xl border border-dashed border-slate-200 p-5 text-center text-xs text-slate-400 dark:border-zinc-700">{empty}</p>}</article>; }
function State({ title, text, action, actionLabel }: any) { return <div className="mx-auto mt-16 max-w-md rounded-2xl border border-slate-200 bg-white p-8 text-center dark:border-zinc-800 dark:bg-zinc-900"><h1 className="font-black">{title}</h1><p className="mt-2 text-sm text-slate-500">{text}</p><button onClick={action} className="theme-primary-action mt-4 rounded-xl px-4 py-2 text-sm font-bold">{actionLabel}</button></div>; }
